== Template Overview
:noaudio:

.Components continued:

* Labels
** Labels are used to manage and organize generated resources, such as pods. The labels specified in the template are applied to every resource that is generated from the template.
** Labels are used to organize, group, or select objects and resources.  resources and pods are "tagged" with labels, and then services and replication controllers use labels to indicate the pods they relate to. This makes it possible for services and replication controllers to reference groups of pods, or treat pods with potentially different Docker containers as similar entities.

* Parameters
** Parameters are used to "share" configuration values between the different items in the template.
** An easy example would be the database user name, password or port needed by the frontend pods to communicate to our database backend pods.

* Items - Items can be any resources that needs to be created for the template, in our example we will create Pods, Services, Replication controllers and a route for our template.
** Other items can be BuildConfigs, ImageStreams and more.


ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]


