:noaudio:

ifdef::revealjs_slideshow[]

[#cover,data-background-image="image/1156524-bg_redhat.png" data-background-color="#cc0000"]
== &nbsp;


[#cover-h1]
Red Hat OpenShift Enterprise Implementation

[#cover-h2]
Instant Apps and Templates

[#cover-logo]
image::{revealjs_cover_image}[]

endif::[]


== Module Topics
:noaudio:


* Templates Overview
* How to create a Template file
* Creating a Configuration From a Template
* Wiring Disparate Components
* Using Templates from the Web Management Console
* Lab	: Installing a Template
* Lab	: Wiring Templates together


ifdef::showScript[]

=== Transcript

* In this Module we will discuss the following topics:
** Templates Overview
** Templates Structure
** Wiring Disparate Components
** Using Templates from the Web Management Console

endif::showScript[]



== Template Overview
:noaudio:



.What is a Template

* From: link:http://docs.openshift.org/latest/dev_guide/templates.html[docs.openshift.org]
** A template describes a set of `resources` that can be customized and processed to produce a configuration.
** Each template is a parameterized list that is used by OpenShift to create a list of resources, including services, pods, routes, buildconfigs, etc.
** A template also defines a set of labels to apply to every resource created by the template.

ifdef::showScript[]

=== Transcript

* A template describes a set of `resources` that can be customized and processed to produce a configuration.
* Each template is a parameterized list that is used by OpenShift to create a list of resources, including services, pods, routes, buildconfigs, etc.
* A template also defines a set of labels to apply to every resource created by the template.

endif::showScript[]




== Template Overview
:noaudio:

.What are Templates for?

* With Templates we can create instantly deployable apps for our developers or customers.
* A template can use a pre-set variables or randomize values (i.e passwords) according to definition.


ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]


== Template Overview
:noaudio:

.Components

* Review the following sample template file:

[source,json]
----
{
  "kind": "Template",
  "apiVersion": "v1",
  "metadata": {
    "name": "quickstart-keyvalue-application",
    "creationTimestamp": null,
    "annotations": {
      "description": "This is an example of a Ruby and MySQL application on OpenShift 3",
      "iconClass": "icon-ruby",
      "tags": "instant-app,ruby,mysql"

    }
  },
  "parameters": [
    {
      "name": "username"
      "value": "admin"
      "description": "administrative user"
    }
  ],
  "labels": {
    "custom_label": "Label_Name"
  },
  "objects": [
    {
      ...
    }
  ]
}

----

* Notice the following elements:
** *"name":* - The name of the template
** *"description":* - Optional description for the template
** *"parameters":* - A list of parameters for the template (Parameters like Username, Passwords and others)
** *"labels":* - A list of labels to apply to resources
** *"objects":* - list of resources to create (Resources like *Pods*, *Services* and *Routes*)


ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]


== Template Overview
:noaudio:

.Components continued:

* Labels
** Labels are used to manage and organize generated resources, such as pods. The labels specified in the template are applied to every resource that is generated from the template.
** Labels are used to organize, group, or select objects and resources.  resources and pods are "tagged" with labels, and then services and replication controllers use labels to indicate the pods they relate to. This makes it possible for services and replication controllers to reference groups of pods, or treat pods with potentially different Docker containers as similar entities.

ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]


== Template Overview
:noaudio:

.Components continued - Parameters:

* Parameters are used to "share" configuration values between the different items in the template.
* An easy example would be the database user name, password or port needed by the frontend pods to communicate to our database backend pods.

ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]


== Template Overview
:noaudio:

.Components continued - Items:

* tems can be any resources that needs to be created for the template, in our example we will create Pods, Services, Replication controllers and a route for our template.
- Other items can be BuildConfigs, ImageStreams and more.


ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]


== How to create a Template file
:noaudio:

* Template example - Metadata

[source,json]
----
{
  "kind": "Template",
  "apiVersion": "v1",
  "metadata": {
    "name": "quickstart-keyvalue-application",
    "creationTimestamp": null,
    "annotations": {
      "description": "This is an example of a Ruby and MySQL application on OpenShift 3",
      "iconClass": "icon-ruby",
      "tags": "instant-app,ruby,mysql"
    }
  },
----

ifdef::showScript[]

=== Transcript



endif::showScript[]

== How to create a Template file
:noaudio:

* Template example - Objects: Service "web"

[source,json]
----

"objects": [
    {
      "kind": "Service",
      "apiVersion": "v1",
      "metadata": {
        "name": "frontend",
        "creationTimestamp": null
      },
      "spec": {
        "ports": [
          {
            "name": "web",
            "protocol": "TCP",
            "port": 5432,
            "targetPort": 8080,
            "nodePort": 0
          }
        ],
        "selector": {
          "name": "frontend"
        },
        "portalIP": "",
        "type": "ClusterIP",
        "sessionAffinity": "None"
      },
      "status": {
        "loadBalancer": {}
      }
    },

----

ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]

== How to create a Template file
:noaudio:

* Template example - Objects: Service "database"

[source,json]
----
  {
      "kind": "Service",
      "apiVersion": "v1",
      "metadata": {
        "name": "database",
        "creationTimestamp": null
      },
      "spec": {
        "ports": [
          {
            "name": "db",
            "protocol": "TCP",
            "port": 5434,
            "targetPort": 3306,
            "nodePort": 0
          }
        ],
        "selector": {
          "name": "database"
        },
        "portalIP": "",
        "type": "ClusterIP",
        "sessionAffinity": "None"
      },
      "status": {
        "loadBalancer": {}
      }
    },
----

ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]


== How to create a Template file
:noaudio:

* Template example - Objects: Route

[source,json]
----
    {
      "kind": "Route",
      "apiVersion": "v1",
      "metadata": {
        "name": "route-edge",
        "creationTimestamp": null
      },
      "spec": {
        "host": "integrated.cloudapps.example.com",
        "to": {
          "kind": "Service",
          "name": "frontend"
        }
      },
      "status": {}
    },
----

ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]



== How to create a Template file
:noaudio:

* Template example - Objects: ImageStreams "ruby-sample" and "ruby-20-rhel7"

[source,json]
----
 {
"kind": "ImageStream",
      "apiVersion": "v1",
      "metadata": {
        "name": "ruby-sample",
        "creationTimestamp": null
      },
      "spec": {},
      "status": {
        "dockerImageRepository": ""
      }
    },
    {
      "kind": "ImageStream",
      "apiVersion": "v1",
      "metadata": {
        "name": "ruby-20-rhel7",
        "creationTimestamp": null
      },
      "spec": {
        "dockerImageRepository": "registry.access.redhat.com/openshift3_beta/ruby-20-rhel7"
      },
      "status": {
        "dockerImageRepository": ""
      }
    },
----

ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]

== How to create a Template file
:noaudio:

* Template example - Objects: BuildConfig

[source,json]

----
 {
      "kind": "DeploymentConfig",
      "apiVersion": "v1",
      "metadata": {
        "name": "frontend",
        "creationTimestamp": null
      },
      "spec": {
        "strategy": {
          "type": "Recreate"
        },
        "triggers": [
          {
            "type": "ImageChange",
            "imageChangeParams": {
              "automatic": true,
              "containerNames": [
                "ruby-helloworld"
              ],
              "from": {
                "kind": "ImageStreamTag",
                "name": "ruby-sample:latest"
              },
              "lastTriggeredImage": ""
            }
          },
          {
            "type": "ConfigChange"
          }
        ],
        "replicas": 2,
        "selector": {
          "name": "frontend"
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "name": "frontend"
            }
          },
          "nodeSelector": {
            "region": "primary"
          },
          "spec": {
            "containers": [
              {
                "name": "ruby-helloworld",
                "image": "ruby-sample",
                "ports": [
                  {
                    "containerPort": 8080,
                    "protocol": "TCP"
                  }
                ],
                "env": [
                  {
                    "name": "ADMIN_USERNAME",
                    "value": "${ADMIN_USERNAME}"
                  },
                  {
                    "name": "ADMIN_PASSWORD",
                    "value": "${ADMIN_PASSWORD}"
                  },
                  {
                    "name": "MYSQL_USER",
                    "value": "${MYSQL_USER}"
                  },
                  {
                    "name": "MYSQL_PASSWORD",
                    "value": "${MYSQL_PASSWORD}"
                  },
                  {
                    "name": "MYSQL_DATABASE",
                    "value": "${MYSQL_DATABASE}"
                  }
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "IfNotPresent",
                "capabilities": {},
                "securityContext": {
                  "capabilities": {},
                  "privileged": false
                }
              }
            ],
            "restartPolicy": "Always",
            "dnsPolicy": "ClusterFirst",
            "serviceAccount": ""
          }
        }
      },
      "status": {}
    },
    {
----
ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]





== How to create a Template file
:noaudio:

* Template example - Objects: DeploymentConfig "frontend"

[source,json]
----
 {
      "kind": "DeploymentConfig",
      "apiVersion": "v1",
      "metadata": {
        "name": "frontend",
        "creationTimestamp": null
      },
      "spec": {
        "strategy": {
          "type": "Recreate"
        },
        "triggers": [
          {
            "type": "ImageChange",
            "imageChangeParams": {
              "automatic": true,
              "containerNames": [
                "ruby-helloworld"
              ],
              "from": {
                "kind": "ImageStreamTag",
                "name": "ruby-sample:latest"
              },
              "lastTriggeredImage": ""
            }
          },
          {
            "type": "ConfigChange"
          }
        ],
        "replicas": 2,
        "selector": {
          "name": "frontend"
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "name": "frontend"
            }
          },
          "nodeSelector": {
            "region": "primary"
          },
          "spec": {
            "containers": [
              {
                "name": "ruby-helloworld",
                "image": "ruby-sample",
                "ports": [
                  {
                    "containerPort": 8080,
                    "protocol": "TCP"
                  }
                ],
                "env": [
                  {
                    "name": "ADMIN_USERNAME",
                    "value": "${ADMIN_USERNAME}"
                  },
                  {
                    "name": "ADMIN_PASSWORD",
                    "value": "${ADMIN_PASSWORD}"
                  },
                  {
                    "name": "MYSQL_USER",
                    "value": "${MYSQL_USER}"
                  },
                  {
                    "name": "MYSQL_PASSWORD",
                    "value": "${MYSQL_PASSWORD}"
                  },
                  {
                    "name": "MYSQL_DATABASE",
                    "value": "${MYSQL_DATABASE}"
                  }
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "IfNotPresent",
                "capabilities": {},
                "securityContext": {
                  "capabilities": {},
                  "privileged": false
                }
              }
            ],
            "restartPolicy": "Always",
            "dnsPolicy": "ClusterFirst",
            "serviceAccount": ""
          }
        }
      },
      "status": {}
    },
----

ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]







== How to create a Template file
:noaudio:

* Template example - Objects: DeploymentConfig "db"

[source,json]
----
  {
      "kind": "DeploymentConfig",
      "apiVersion": "v1",
      "metadata": {
        "name": "database",
        "creationTimestamp": null
      },
      "spec": {
        "strategy": {
          "type": "Recreate"
        },
        "triggers": [
          {
            "type": "ConfigChange"
          }
        ],
        "replicas": 1,
        "selector": {
          "name": "database"
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "name": "database"
            }
          },
          "nodeSelector": {
            "region": "primary"
          },
          "spec": {
            "containers": [
              {
                "name": "ruby-helloworld-database",
                "image": "registry.access.redhat.com/openshift3_beta/mysql-55-rhel7:latest",
                "ports": [
                  {
                    "containerPort": 3306,
                    "protocol": "TCP"
                  }
                ],
                "env": [
                  {
                    "name": "MYSQL_USER",
                    "value": "${MYSQL_USER}"
                  },
                  {
                    "name": "MYSQL_PASSWORD",
                    "value": "${MYSQL_PASSWORD}"
                  },
                  {
                    "name": "MYSQL_DATABASE",
                    "value": "${MYSQL_DATABASE}"
                  }
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "Always",
                "capabilities": {},
                "securityContext": {
                  "capabilities": {},
                  "privileged": false
                }
              }
            ],
            "restartPolicy": "Always",
            "dnsPolicy": "ClusterFirst",
            "serviceAccount": ""
          }
        }
      },
      "status": {}
    }
----

ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]
== How to create a Template file
:noaudio:

* Template example - Parameters

[source,json]
----
  ],
  "parameters": [
    {
      "name": "ADMIN_USERNAME",
      "description": "administrator username",
      "generate": "expression",
      "from": "admin[A-Z0-9]{3}"
    },
    {
      "name": "ADMIN_PASSWORD",
      "description": "administrator password",
      "generate": "expression",
      "from": "[a-zA-Z0-9]{8}"
    },
    {
      "name": "MYSQL_USER",
      "description": "database username",
      "generate": "expression",
      "from": "user[A-Z0-9]{3}"
    },
    {
      "name": "MYSQL_PASSWORD",
      "description": "database password",
      "generate": "expression",
      "from": "[a-zA-Z0-9]{8}"
    },
    {
      "name": "MYSQL_DATABASE",
      "description": "database name",
      "value": "root"
    }
  ],
  "labels": {
    "template": "application-template-stibuild"
  }
----

ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]


== Creating a Configuration From a Template
:noaudio:

.Uploading a Template

* You can create a configuration from a template using the CLI or, if a template has been uploaded to your project or global template library, using the Management Console.
* You can create a template JSON file, like the above example, then upload it with the CLI using the following process:
** You can upload a template to your current project’s template library by passing a JSON file with the following command:
----

$ oc create -f <filename>

----

** You can upload a template to a different project using the -n option with the name of the project:

----

$ oc create -f <filename> -n <project>

----

** The template would now available to be selected for a configuration using the Management Console or the CLI.

ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]




== Creating a Configuration From a Template
:noaudio:

.Generating a Configuration


* Generate a configuration with the following command:
** oc process will examine a template, generate any desired parameters, and output a JSON configuration that can be created with oc.

----

$ oc process -f <filename>

----

** Alternatively, you can create from a template without uploading it to the template library by processing the template and creating from the same template by piping both commands:

----

$ oc process -f <filename.json> | oc create -f -

----

** You can override any parameters defined in the JSON file by adding the -v option and any desired parameters. For example, you can override the ADMIN_USERNAME and MYSQL_DATABASE parameters to create a configuration with customized environment variables:

----

$ oc process -f examples/sample-app/application-template-dockerbuild.json -v ADMIN_USERNAME=root,MYSQL_DATABASE=admin

----


ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]


== Wiring Disparate Components
:noaudio:

.Overview

* Sometimes a developer wants to build up the various components manually.
* Let's take our example and treat it like two separate "applications" that we want to wire together.
** Process and create a template for the "frontend"
** Extract the values of the *mysql* credentials from the config file
** Process and create a template for the "db" and override the values with the values we extracted from "frontend" config file.

ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]


== Wiring Disparate Components
:noaudio:

.Process "frontend"

* The first step will be to stand up the frontend of our application.
** Process the "frontend" template and create the *config* file.

----

$ oc process -f frontend-template.json > frontend-config.json

----

** create the configuration:
----

$ oc create -f frontend-config.json

----

* As soon as you create this, all of the resources will be created and a build will be started for you.



ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]




== Wiring Disparate Components
:noaudio:

.Extract the values from config file


* Before creating the "db" template we will review the config file for "frontend"
** In the config, you will see that a DB password and other parameters have been generated
----
grep -A 1 MYSQL_* frontend-config.json
                                            "name": "MYSQL_USER",
                                            "key": "MYSQL_USER",
                                            "value": "userMXG"

                                            "name": "MYSQL_PASSWORD",
                                            "key": "MYSQL_PASSWORD",
                                            "value": "slDrggRv"

                                            "name": "MYSQL_DATABASE",
                                            "key": "MYSQL_DATABASE",
                                            "value": "root"

----


ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]






== Wiring Disparate Components
:noaudio:

.Process "db"

* Now that we know the values that were used to create "frontend" we can use them when we process the "db" template
* In this example we are processing and creating the "db" template while overriding the mysql credentials variables.
** Process the "frontend" template and create the *config* file.

----

$ oc process -f db-template.json  -v MYSQL_USER=userMXG,MYSQL_PASSWORD=slDrggRv,MYSQL_DATABASE=root > db-config.json

----

** create the configuration:

----

$ oc create -f frontend-config.json

----

* We can also achieve this in a single step.
** The following will process and create the application:

----

oc process -f db-template.json \
    -v MYSQL_USER=userMXG,MYSQL_PASSWORD=slDrggRv,MYSQL_DATABASE=root \
    | oc create -f -

----


ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]

== Summary
:noaudio:

* Templates Overview
* How to create a Template file
* Creating a Configuration From a Template
* Wiring Disparate Components
* Using Templates from the Web Management Console
* Lab	: Installing a Template
* Lab	: Wiring Templates together




ifdef::showScript[]

=== Transcript

* Place narrator script here

endif::showScript[]
