== Containers and Images


.Containers

* Basic units of OpenShift Enterprise applications
* Lightweight mechanisms for isolating running processes
** Limits processes to interacting with designated resources only
* Can run many application instances in containers on single host
** No visibility into other processes, files, network, etc.
* Container typically provides single service (often called a _microservice_)
** Web server or database
* Can use containers for arbitrary workloads
* More info on Linux container technologies: https://access.redhat.com/articles/1353593

ifdef::showscript[]

=== Transcript

Containers are the basic units of OpenShift Enterprise applications. Containers
 are lightweight mechanisms for isolating running processes so that these
  processes interact only with their designated resources.

You can run many application instances in containers on a single host without
 visibility into each others' processes, files, network, and so on.

Typically, each container provides a single service (often called a
   _microservice_), such as a web server or a database. However, you can also
    use containers for arbitrary workloads.

endif::showscript[]
