== Pods and Services

.Pod Changes and Management

* OpenShift Container Platform treats pods as _static_ objects
** Cannot change pod definition while running

* To implement changes, OpenShift Container Platform:
** Terminates existing pod
** Recreates it with modified configuration, base image(s), or both

* Pods are expendable, do not maintain state when recreated
* Should use higher-level _controllers_ to manage pods
** Pods should usually be managed by higher-level controllers rather than
 directly by users.

ifdef::showscript[]

=== Transcript

OpenShift Container Platform treats pods as _static_ objects. You cannot change a pod
 definition while it is running. When you want to change a pod, you _recreate_
  rather than _modify_ it.

OpenShift Container Platform implements changes by terminating an existing pod and
 recreating it with a modified configuration, base image(s), or both.

OpenShift also treats pods as expendable. Pods do not maintain state when
 recreated.

Because of this, you use higher-level _controllers_, such as
 _deployment configurations_ and _replication controllers_, to manage pods,
  rather than allow users to manage pods directly.


endif::showscript[]
