== Pods and Services


.Pods Definition File/Manifest

* Example definition of pod:
** Part of OpenShift Enterprise infrastructure: _Private Docker integrated registry_
** Demonstrates many pod features
+
[source,yaml]
----
 apiVersion: v1
 kind: Pod
 metadata:
   annotations: { ... }
   labels:                               // <1>
     deployment: docker-registry-1
     deploymentconfig: docker-registry
     docker-registry: default
   generateName: docker-registry-1-     //  <2>

----

ifdef::showscript[]

=== Transcript

Here is an example definition of a pod that provides a long-running service.
 This is actually a part of the OpenShift Enterprise infrastructure, the
  _private Docker integrated registry_.

This example demonstrates many features of pods. The next few slides examine the
 file in smaller chunks to make it easier to follow.

Note the following:

. You can _tag_ pods with one or more _labels_. You can then use the labels to
 select and manage groups of pods in a single operation.

. Pods must have a unique name within their _namespace_. In the pod definition,
 you can specify a base name and use the `generateName` attribute to
  automatically add random characters at the end of the base name,
   thus generating a unique name.


endif::showscript[]
