== Pods and Services

.Pods Definition File/Manifest: Container
[source,yaml]
----
     image: openshift3/example-image:v1.1.0.6 <1>
     imagePullPolicy: IfNotPresent
     name: registry
     ports:                              <2>
     - containerPort: 5000
       protocol: TCP
     resources: {}
     securityContext: { ... }            <3>
     volumeMounts:                       <4>
     - mountPath: /registry
       name: registry-storage
     - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
       name: default-token-br6yz
       readOnly: true
----
<1> Each container in pod is instantiated from its own Docker image
<2> Container can bind to ports, which are available on pod's IP
<3> Container's _security context_ specifies whether it can run as privileged container
<4> External storage volumes should be mounted within container


ifdef::showscript[]

=== Transcript

Here you see a container definition:

. Each container in the pod is instantiated from its own Docker image.
. The container can bind to ports, which are available on the pod's IP.
. OpenShift Container Platform defines a _security context_ for containers that
 specifies whether they can run as privileged containers, run as a user of their
  choice, and more. The default context is highly restrictive, but
   administrators can modify this as needed.
. The container specifies where external storage volumes should be mounted
 within the container. In this case, one volume stores the registry's data,
  another provides access to credentials that the registry needs to make requests
   against the OpenShift Container Platform API.

endif::showscript[]
