== Pods and Services
:noaudio:

.Pods Definition file/Manifest - Continued

[source,yaml]
----
   dnsPolicy: ClusterFirst
   imagePullSecrets:
   - name: default-dockercfg-at06w
   restartPolicy: Always
   serviceAccount: default               <1>
   volumes:                              <2>
   - emptyDir: {}
     name: registry-storage
   - name: default-token-br6yz
     secret:
       secretName: default-token-br6yz
----

<1> Pods making requests against the OpenShift API is a common enough pattern
 that there is a `serviceAccount` field for specifying which _service account_
  user the pod should authenticate as when making the requests. This enables
  fine-grained access control for custom infrastructure components.
<2> The pod defines storage volumes that are available to its container(s) to
 use. In this case, it provides an ephemeral volume for the registry storage and
 a *secret* volume containing the service account credentials.


ifdef::showscript[]
=== Transcript

Pods making requests against the OpenShift API is a common enough pattern
  that there is a `serviceAccount` field for specifying which _service account_
   user the pod should authenticate as when making the requests.

The pod defines storage volumes that are available to its container(s) to use.
In this case, it provides an ephemeral volume for the registry storage and a
*secret* volume containing the service account credentials.

You can learn more about using "secrets" in the developer guide documentation.

endif::showscript[]

