== Pods and Services


.Pods Definition File/Manifest: Requests and Storage Volumes

[source,yaml]
----
   dnsPolicy: ClusterFirst
   imagePullSecrets:
   - name: default-dockercfg-at06w
   restartPolicy: Always
   serviceAccount: default               <1>
   volumes:                              <2>
   - emptyDir: {}
     name: registry-storage
   - name: default-token-br6yz
     secret:
       secretName: default-token-br6yz
----

. Service Account name
. volumes that the pod can use


ifdef::showscript[]

=== Transcript

In this example, you see how pods make requests and define storage volumes:

. Pods commonly make requests against the OpenShift Enterprise API and need
 authentication to do so. The `serviceAccount` field specifies the
  _service account_ user that the pod should use to authenticate when making
   requests. This enables fine-grained access control for custom infrastructure
    components.
. The pod defines storage volumes that its container(s) can use. In this case,
 it provides an ephemeral volume for the registry storage and a `secret` volume
  containing the service account credentials.

You can learn more about using _secrets_ in the developer guide documentation.

endif::showscript[]
