== Pods and Services

.Services
:noaudio:

* A Kubernetes _service_ serves as an *internal* load balancer.
 It identifies a set of replicated _pods_ in order to proxy the connections it
 receives to them.
* Backing pods can be added to or removed from a service arbitrarily while the
 _service_ remains consistently available, enabling anything that depends on the
 _service_ to refer to it at a consistent internal address.

* Services are assigned an IP address and port pair that, when accessed,
 proxy to an appropriate backing pod.
* A service uses a label selector to find  all the containers running that
 provide a certain network service on a certain port.
* A server can be accessed by its IP address and a local DNS name created and
resolved by the local DNS server on the master.

NOTE: When we use the "_Default Router_" (HA-Proxy) we bypass the _Service_ load
balancing. We only use the _Service_ to find out which _Pods_ are represented by
 The Service and load balancing use done by the "_Router_"

ifdef::showscript[]
=== Transcript

A Kubernetes _service_ serves as an *internal* load balancer.
It identifies a set of replicated _pods_ in order to proxy the connections it
receives to them. A service uses a label selector to find  all the containers
running that provide a certain network service on a certain port.

Services are assigned an IP address and port pair that, when accessed,
proxy to an appropriate backing pod. Backing pods can be added to or removed
from a service arbitrarily while the _service_ remains consistently available,
enabling anything that depends on the _service_ to refer to it at a consistent
internal address.

When we use the "_Default Router_" (HA-Proxy) we bypass the _Service_ load
balancing. We only use the _Service_ to find out which _Pods_ are represented by
 The Service and load balancing use done by the "_Router_"

endif::showscript[]
