== Pods and Services


.Service Definition File/Manifest

* Like pods, services are REST objects
* Example: Definition of service for pod defined above:
+
[source,yaml]
----
 apiVersion: v1
 kind: Service
 metadata:
   name: example-name
 spec:
   selector:                  <1>
     example-label: example-value
   portalIP: 172.30.136.123   <2>
   ports:
   - nodePort: 0
     port: 5000               <3>
     protocol: TCP
     targetPort: 5000         <4>
----
<1> `selector` identifies all pods with specified label: `example-label: example-value`
<2> `portalIP` specifies assigned service IP
<3> `Port` specifies port on which service listens
<4> `targetPort` specifies port used to forward connections to backing pods



ifdef::showscript[]

=== Transcript

Like pods, services are REST objects. The example shown here provides the
 definition of a service for the pod defined above.

Note the following:

. The label selector identifies all pods with the `example-label: example-value`
 label as the `Pods` represented by the `service`
. When the service is created, it automatically receives a virtual IP,
 `PortalIP`, chosen from a pool of internal IPs. When you define a new service,
  you leave this blank to be assigned a random IP.
. The `Port` line specifies the port on which the service listens.
. The service uses the `targetPort` to forward connections to the backing pods.
 Those pods should listen on that port.

endif::showscript[]
