== Pods and Services


.Service Definition File/Manifest

* Like pods, services are REST objects
* Example: Definition of service for pod defined above:
+
[source,yaml]
----
 apiVersion: v1
 kind: Service
 metadata:
   name: docker-registry
 spec:
   selector:                  <1>
     docker-registry: default
   portalIP: 172.30.136.123   <2>
   ports:
   - nodePort: 0
     port: 5000               <3>
     protocol: TCP
     targetPort: 5000         <4>
----


ifdef::showscript[]

=== Transcript

Like pods, services are REST objects. The example shown here provides the
 definition of a service for the pod defined above.

. The label selector identifies all pods with the `docker-registry=default`
 label as the `Pods` represented by the `service`
. When the service is created, it automatically receives a virtual IP,
 `PortalIP`, chosen from a pool of internal IPs. When you define a new service,
  you leave this blank to get assigned a random IP.
. The `Port` line specifies the port on which the service listens.
. The service uses the `targetPort` to forward connections to the backing pods.
 Those pods should "listen" on that port.

endif::showscript[]
