== Pods and Services
:noaudio:

.Labels: Examples

* Labels = Simple key/value pairs:
+
[source,yaml]
----
 labels:
   key1: value1
   key2: value2
----

* Scenario:
** Pod consisting of `nginx` Docker container, with `role=webserver` label
** Pod consisting of `Apache httpd` Docker container, also with `role=webserver` label
** Service or replication controller defined to use pods with `role=webserver` label treats both pods as part of same group

* Example: To remove all components with the label `app=mytest`:
+
----
# oc delete all -l app=mytest
----

ifdef::showscript[]

=== Transcript

Labels are simple key/value pairs that you can use in almost every type of object in OpenShift Enterprise.

Labels provide an easy way to manage resources as groups, rather than individually.

For example, say you have two separate pods. One is a `nginx` Docker container, and the other is an `Apache httpd` Docker container. If both are tagged with a `role=webserver` label, the service or replication controller defined to use pods with the `role=webserver` label treats both pods as part of the same group.

The second example here shows how labeing a group of components with `app=mytest` let you delete all of them in one command rather than having to locate and delete each component manually.

endif::showscript[]


