== Scheduler
:noaudio:

.Generic Scheduler

* The existing generic scheduler is the default platform-provided scheduler
"engine" that selects a node to host the pod in a 3-step operation:

- Step 1: Filter the nodes
The available nodes are filtered based on the constraints or requirements
specified. This is done by running each of the nodes through the list of filter
functions called 'predicates'.

- Step 2: Prioritize the filtered list of nodes
This is achieved by passing each node through a series of 'priority' functions
that assign it a score between 0 - 10, with 0 indicating a bad fit and 10
indicating a good fit to host the pod.

- Step 3: Select the best fit node
The nodes are sorted based on their scores and the node with the highest score
is selected to host the pod. If multiple nodes have the same high score, then
one of them is selected at random.

ifdef::showscript[]
=== Transcript
The scheduler configuration can also take
in a simple "weight" (positive numeric value) for each priority function. The
node score provided by each priority function is multiplied by the "weight"
(default weight is 1) and then combined by just adding the scores for each node
provided by all the priority functions. This weight attribute can be used by
administrators to give higher importance to some priority functions.
endif::showscript[]



