== Scheduler

.Generic Scheduler

* OpenShift Enterprise provides generic scheduler
** Default scheduling _engine_
** Selects node to host pod in three-step operation:

. Filter nodes based on specified constraints/requirements

- Runs nodes through list of filter functions called _predicates_

. Prioritize qualifying nodes

- Pass each node through series of _priority_ functions
- Assign node score between 0 - 10
- 0 indicates bad fit, 10 indicates good fit

. Select the best fit node

- Sort nodes based on scores
- Select node with highest score to host pod
- If multiple nodes have same high score, select one at random
- Priority functions equally weighted by default; more important priorities can receive higher weight

ifdef::showscript[]

=== Transcript

OpenShift Enterprise provides a default generic scheduler. It is a scheduling
 _engine_ that selects a node to host the pod in a three-step operation:

. The scheduler filters all of the available nodes based on specified
 constraints and requirements by running them through a list of filter functions
  called _predicates_, and disqualifies the nodes that do not meet the criteria.

. It then prioritizes the qualifying nodes that remain by passing them through
 a series of _priority_ functions that assign each node a score between 0 and
  10, where 0 indicates the worst possible fit and 10 the best possible fit to
   host the pod.

. The scheduler sorts the nodes by scores and selects the node with the highest
 score to host the pod. If multiple nodes have the same high score, the
  scheduler selects one of them at random.

By default, the scheduler considers every priority function to be equally
 important and gives each one a weight, or positive numeric value, of 1.
  Administrators can reconfigure the scheduler to give some priority functions
   more importance by increasing their weight.

endif::showscript[]
