== Scheduler
:noaudio:

.Configurable Predicates - Continued
* *_ServiceAffinity_* filters out nodes that do not belong to the specified
topological level defined by the provided labels.
** This predicate takes in a list of labels and ensures affinity within the nodes
(that have the same label values) for pods belonging to the same service.
** If the pod specifies a value for the labels in its NodeSelector, then the
nodes matching those labels are the ones where the pod is scheduled.

----
{"name" : "Zone", "argument" : {"serviceAffinity" : {"labels" : ["zone"]}}}
----
* *_LabelsPresence_* checks whether a particular node has a certain label defined
or not, regardless of its value.
----
{"name" : "ZoneRequired", "argument" : {"labels" : ["retiring"], "presence" : false}}
----

ifdef::showscript[]
=== Transcript

*_ServiceAffinity_* filters out nodes that do not belong to the specified
topological level defined by the provided labels, This predicate takes in a list
 of labels and ensures affinity within the nodes (that have the same label
   values) for pods belonging to the same service.

If the pod specifies a value for the labels in its NodeSelector, then ONLY
nodes matching those labels are the ones where the pod can be scheduled.

endif::showscript[]


