== Scheduler
:noaudio:

.Use Cases

* One of the important use cases for scheduling within OpenShift is to support
flexible affinity and anti-affinity policies.

* OpenShift can implement multiple Infrastructure Topological Levels
** Administrators can define multiple topological levels for their infrastructure
(nodes).
** This is done by specifying labels on nodes
(eg: region = r1, zone = z1, rack = s1).
** These label names have no particular meaning and administrators are free to
name their infrastructure levels anything (eg, city/building/room).
** Administrators can define any number  of levels for their infrastructure
topology, with three levels usually being
adequate (eg. regions --> zones --> racks).
Administrators can specify affinity and anti-affinity rules at each of these
levels in any combination.

ifdef::showscript[]
=== Transcript

One of the important use cases for scheduling within OpenShift is to support
flexible affinity and anti-affinity policies, By specifiyng labels on the nodes
administrators can define multiple topological levels for their infrastructure.

Look at a few of the examples here, although we are using the "Region" and
"Zones" example in this training, you can use any kind of topology that makes
sense in your environment.

endif::showscript[]


