== Builds and Image Streams

.Builds Overview

* *Build*: Process of transforming input parameters into resulting object
** Most often used to transform source code into runnable image
* `BuildConfig` object: Definition of entire build process

* OpenShift Container Platform build system provides extensible support for
 _build strategies_
** Based on selectable types specified in build API
* Three build strategies available:
** Docker build
** S2I build
** Custom build

* Docker and S2I builds supported by default

ifdef::showscript[]

=== Transcript

A _build_ is the process of transforming input parameters into a resulting
 object. Most often, you use the process to transform source code into a
  runnable image. A _BuildConfig_ object is the definition of the entire build
   process.

The OpenShift Container Platform build system provides extensible support for
 _build strategies_ that are based on selectable types specified in the build
  API. Three build strategies are available:

* *Docker build*: A build based on a _Dockerfile_.
*  *S2I build*: OpenShift Container Platform's built-in builder. It builds an image
 from a base image and source code provided as a Git repository.
*  *Custom build*: Can be any process a user can define. One example is a
 Jenkins server that builds a Docker image outside of the OpenShift Container Platform
  environment.

OpenShift Container Platform supports Docker and S2I builds by default.

endif::showscript[]
