== Builds and Image Streams
:noaudio:

.Builds Overview

* A _build_ is the process of transforming input parameters into a resulting object.
- Most often, the process is used to transform source code into a runnable image.
- A _BuildConfig_ object is the definition of the entire build process.

* The OpenShift build system provides extensible support for _build strategies_
that are based on selectable types specified in the build API. There are three
build strategies available:
- Docker build
- Source-to-Image (S2I) build
- Custom build

By default, Docker builds and S2I builds are supported.

ifdef::showscript[]
=== Transcript

A _build_ is the process of transforming input parameters into a resulting object.
A _BuildConfig_ object is the definition of the entire build process.

The OpenShift build system provides extensible support for _build strategies_
that are based on selectable types specified in the build API. There are three
build strategies available:

- Docker build - A build based on a _Dockerfile_
- Source-to-Image (S2I) build - OpenShift's built-in builder, builds an image
based on a base image and source code provided as a Git repository
- Custom build - This can be any process a user can define, an easy example
would be a Jenkins server that builds a Docker Image outside of the OSE environment.

endif::showscript[]


