== Builds and Image Streams
:noaudio:

.S2I Advantages

[horizontal]
Image flexibility:: S2I scripts can be written to layer application code onto
almost any existing Docker image, taking advantage of the existing ecosystem.
Note that, currently, S2I relies on `tar` to inject application
source, so the image needs to be able to process tarred content.

Speed:: With S2I, the assemble process can perform a large number of complex
operations without creating a new layer at each step, resulting in a fast
process. In addition, S2I scripts can be written to re-use artifacts stored in a
previous version of the application image, rather than having to download or
build them, each time the build is run.

Patchability:: S2I allows you to rebuild the application consistently if an
underlying image needs a patch due to a security issue.

ifdef::showscript[]
=== Transcript
Image flexibility, Speed and Patchability are only some of the advantages that
Using S2I provides, S2I scripts can be written to layer application code onto
almost any existing Docker image, this means you can switch your builder image
from Centos to RHEL of from RHEL7.1 to RHEL7.2 without issues, simply rebuild
 the image and start using it.

S2I's assemble process can perform a large number of complex
operations without creating a new layer at each step, resulting in a fast
process.

An image could be rebuilt quickly in case the base image requires a patch, for
example if there is a new security patch.

endif::showscript[]


