== Builds and Image Streams

.Image Streams

* _Image stream_ similar to Docker image repository
** Contains _Docker images_ identified by tags
** Presents single virtual view of related images
** May contain images from:
*** Own image in OpenShift's integrated Docker Registry
*** Other image streams
*** Docker image repositories from external registries

* OpenShift Container Platform stores complete metadata about each image
** Examples: command, entrypoint, environment variables, etc.

* OpenShift Container Platform images immutable

* OpenShift Container Platform components can:
** Watch for updates in an image stream
** Receive notifications when new images added
** React by performing build or deployment

ifdef::showscript[]

=== Transcript

An _image stream_ is similar to a Docker image repository in that it contains
 one or more _Docker images_ identified by tags. An image stream presents a
  single virtual view of related images. The stream may contain images from any
   of the following:

* Its own image repository in OpenShift Container Platform's integrated Docker Registry
* Other image streams
* Docker image repositories from external registries

OpenShift Container Platform stores complete metadata about each image--for example,
 command, entrypoint, environment variables, and so on. Images in OpenShift
  Enterprise are immutable.

OpenShift Container Platform components such as builds and deployments can watch an
 image stream, receive notifications when new images are added, and react by
  performing a build or a deployment, among other functions.

endif::showscript[]
