== Routers

.Routers: Overview

* Administrators can deploy _routers_ (like HAProxy `Default Router`) in
 OpenShift Container Platform cluster
* Let external clients use `route` resources created by developers

* Routers provide external hostname mapping and load balancing to applications
 over protocols that pass distinguishing information directly to router

* Currently, OpenShift Container Platform routers support these protocols:
** HTTP
** HTTPS (with SNI)
** WebSockets
** TLS with SNI

ifdef::showscript[]

=== Transcript

An OpenShift Container Platform administrator can deploy _routers_ (like the HAProxy
   `Default Router`) in an OpenShift Container Platform cluster. These enable external
    clients to use `route` resources created by developers.

OpenShift Container Platform routers provide external hostname mapping and
 load balancing to applications over protocols that pass distinguishing
  information directly to the router.

Currently, OpenShift Container Platform routers support the following protocols:

* HTTP
* HTTPS (with SNI)




endif::showscript[]
