== Routers

.Routers: Overview

* Administrators can deploy _routers_ (like HAProxy `Default Router`) in
 OpenShift Enterprise cluster
* Let external clients use `route` resources created by developers

* Routers provide external hostname mapping and load balancing to applications
 over protocols that pass distinguishing information directly to router

* Currently, OpenShift Enterprise routers support these protocols:
** HTTP
** HTTPS (with SNI)
** WebSockets
** TLS with SNI

ifdef::showscript[]

=== Transcript

An OpenShift Enterprise administrator can deploy _routers_ (like the HAProxy
   `Default Router`) in an OpenShift Enterprise cluster. These enable external
    clients to use `route` resources created by developers.

OpenShift Enterprise routers provide external hostname mapping and
 load balancing to applications over protocols that pass distinguishing
  information directly to the router.

Currently, OpenShift Enterprise routers support the following protocols:

* HTTP
* HTTPS (with SNI)
* WebSockets
* TLS with SNI



endif::showscript[]
