== Routers
:noaudio:

.Routers: Overview

* Administrators can deploy _routers_ (like HAProxy `Default Router`) in OpenShift Enterprise cluster
* Let external clients use `route` resources created by developers

* Routers provide external hostname mapping and load-balancing to applications over protocols that pass distinguishing information directly to router

* In OpenShift Enterprise 3.0.0.0, `Default Router` supports following protocols only:
** HTTP
** HTTPS

ifdef::showscript[]

=== Transcript

An OpenShift Enterprise administrator can deploy _routers_ (like the HAProxy `Default Router`) in an OpenShift Enterprise cluster. These enable external clients to use `route` resources created by developers.

OpenShift Enterprise routers provide external hostname mapping and load-balancing to applications over protocols that pass distinguishing information directly to the router.

Currently, in OpenShift Enterprise 3.0.0.0, OpenShift Enterprise's `Default Router` supports only HTTP and HTTPS.

endif::showscript[]

