== Routers

.Sticky Sessions

* Underlying router configuration determines sticky session implementation
* Default HAProxy template implements sticky sessions using _balance source_
 directive
** Balances based on source IP
* Template router plug-in provides service name and namespace to underlying
 implementation
** Can use for advanced configuration such as implementing stick-tables that
 synchronize between set of peers

* Specific configuration for router implementation stored in
 `haproxy-config.template`, located in `/var/lib/haproxy/conf` directory of
  router container

ifdef::showscript[]

=== Transcript

The underlying router configuration determines implementation of sticky sessions.

The default HAProxy template implements sticky sessions using the
 _balance source_ directive, which balances based on the source IP.

In addition, the template router plug-in provides the service name and namespace
 to the underlying implementation.

You can use this for more advanced configuration such as implementing
 stick-tables that synchronize between a set of peers.

The specific configuration for this router implementation is stored in the
 `haproxy-config.template` file, located in the `/var/lib/haproxy/conf`
  directory of the router container.

endif::showscript[]
