
:noaudio:

ifdef::revealjs_slideshow[]

[#cover,data-background-image="image/1156524-bg_redhat.png" data-background-color="#cc0000"]

== &nbsp;
:noaudio:

[#cover-h1]
Red Hat OpenShift Enterprise

[#cover-h2]
OpenShift 3 Application Life Cycle
[#cover-logo]
image::{revealjs_cover_image}[]

endif::[]
== Module Topics

:numbered!:

* Deployments
* Strategies
* Life-cycle Hooks
* Build Triggers


ifdef::showscript[]

=== Transcript
Welcome to module eight of the OpenShift Enterprise Implementation course.

In this module you learn about the value of deployments to the developer and to
 operational workflows, and you learn the different strategies you can use to
  deploy a new version of your application.

Life-cycle hooks are covered, including how to use them as build triggers, and
 you learn some practical commands to manage a redeployment or rollback.

endif::showscript[]
== Deployments

.Overview

* OpenShift Enterprise deployment is replication controller based on
 user-defined template called _deployment configuration_

* Deployments are created manually or in response to trigger events

* Deployment system provides:

** Configuration template for deployments
** Triggers that drive automated deployments
** Customizable strategies for transitioning from previous deployment to new
 deployment
** Rollbacks to a previous deployment
** Manual replication scaling

* Deployment configuration version increments each time new deployment is
 created from configuration

ifdef::showscript[]
=== Transcript

A deployment in OpenShift Enterprise is a replication controller based on a
 user-defined template called a _deployment configuration_. Deployments are
  created manually or in response to triggered events.

The deployment system provides:

* A deployment configuration, which is a template for deployments
* Triggers that drive automated deployments in response to events
* User-customizable strategies to transition from the previous deployment to a
 new deployment
* Rollbacks to a previous deployment
* Replication scaling

The deployment configuration contains a version number that is incremented each
 time a new deployment is created from that configuration.

endif::showscript[]
== Deployments

.Deployments and Deployment Configurations

* With concept of _deployments_, OpenShift Enterprise adds expanded support for
 software development and deployment life cycle

* Deployment creates new replication controller and lets it start up pods

* Also provides ability to transition from existing image deployment to new one

* Can define hooks to run before or after replication controller is created

ifdef::showscript[]
=== Transcript

Building on replication controllers, with this concept of deployments, OpenShift
 Enterprise adds expanded support for the software development and deployment
  life cycle.

In the simplest sense, a deployment just creates a new replication controller
 and lets it start up pods.

OpenShift Enterprise deployments also provide the ability to transition from an
 existing deployment of an image to a new one, and also to define hooks to be
  run before or after the replication controller is created.

endif::showscript[]
== Deployments

.Deployments and Deployment Configurations

* `DeploymentConfig` object defines deployment:

** Elements of `ReplicationController` definition
** Triggers for creating new deployment automatically
** Strategy for transitioning between deployments
** Life-cycle hooks

* Each time deployment is triggered (manual or automatic), deployer pod manages
 deployment:
** Scales down old replication controller
** Scales up new replication controller
** Runs hooks
* Deployment pod remains after deployment to retain logs
* To enable easy rollback, when one deployment is superseded by another,
 previous replication controller is retained

ifdef::showscript[]

=== Transcript

The OpenShift Enterprise `DeploymentConfig` object defines the following details
 of a deployment:

* The elements of a `ReplicationController` definition
* Triggers for creating a new deployment automatically
* The strategy for transitioning between deployments
* Life-cycle hooks

Each time a deployment is triggered, whether manually or automatically, a
 deployer pod manages the deployment, including scaling down the old replication
  controller, scaling up the new one, and running hooks.

When a deployment is superseded by another, the previous replication controller
 is retained and set to "replica=0" to enable easy rollback if needed.

endif::showscript[]
== Deployments

.Deployment Configuration Definition File/Manifest

* Example `DeploymentConfig` definition:
+
----
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: frontend
spec:
  replicas: 5
  selector:
    name: frontend
  template: { ... }
  triggers:
  - type: ConfigChange <1>
  - imageChangeParams:
      automatic: true
      containerNames:
      - helloworld
      from:
        kind: ImageStreamTag
        name: hello-openshift:latest
    type: ImageChange  <2>
  strategy:
    type: Rolling      <3>
----

. `ConfigChange` trigger
. `ImageChange` trigger
. Default `Rolling` strategy

ifdef::showscript[]
=== Transcript

This is an example `DeploymentConfig` definition, with some omissions and items
 called out.

Note the following:

. The `ConfigChange` trigger causes a new deployment to be created any time the
 replication controller template changes.

. The `ImageChange` trigger causes a new deployment to be created each time a
 new version of the backing image is available in the named image stream.

. The default `Rolling` strategy provides a downtime-free transition between
 deployments.


endif::showscript[]
== Deployments

.Creating a Deployment Configuration

* _Deployment configuration_ consists of:
- _Replication controller_ template describing application to be deployed
- Default _replica_ count for deployment
- Deployment _strategy_ used to execute deployment
- Set of _triggers_ that cause deployments to be created automatically

* Deployment configuration is `deploymentConfig` OpenShift Enterprise API
 resource
** Can be managed with `oc` command like any other resource

ifdef::showscript[]

=== Transcript
A _deployment configuration_ consists of the following key parts:

* A replication controller template, which describes the application to be
 deployed
* The default replica count for the deployment
* A deployment strategy, which will be used to execute the deployment
* A set of triggers, which cause deployments to be created automatically

A deployment configuration is a `deploymentConfig` OpenShift Enterprise API
 resource that can be managed with the `oc` command like any other resource.


endif::showscript[]
== Deployments

.Deployment Configuration Example

----
{
  "kind": "DeploymentConfig",
  "apiVersion": "v1",
  "metadata": {
    "name": "frontend"
  },
  "spec": {
    "template": { <1>
      "metadata": {
        "labels": {
          "name": "frontend"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "helloworld",
            "image": "openshift/origin-ruby-sample",
            "ports": [
              {
                "containerPort": 8080,
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    }
    "replicas": 5, <2>
    "selector": {
      "name": "frontend"
    },
    "triggers": [
      {
        "type": "ConfigChange" <3>
      },
      {
        "type": "ImageChange", <4>
        "imageChangeParams": {
          "automatic": true,
          "containerNames": [
            "helloworld"
          ],
          "from": {
            "kind": "ImageStreamTag",
            "name": "origin-ruby-sample:latest"
          }
        }
      }
    ],
    "strategy": {
      "type": "Rolling" <5>
    }
  }
}
----

<1> Replication controller template named `frontend`, which describes a simple Ruby
 application
<2> Creates 5 replicas of `frontend` by default
<3> If replication controller template changes, configuration change trigger creates new deployment
<4> If new version of `origin-ruby-sample:latest` image repository is available, image change trigger creates new deployment
<5> `Rolling` is default strategy and may be omitted

ifdef::showscript[]

=== Transcript


This is an example of a `deploymentConfig` resource. Note the following in the
 code sample:

. The replication controller template named `frontend` describes a simple Ruby
 application.
. There will be 5 replicas of `frontend` by default.
. A configuration change trigger causes a new deployment to be created any time
 the replication controller template changes.
. An image change trigger causes a new deployment to be created each time a new
 version of the `origin-ruby-sample:latest` image repository is available.
. The `Rolling` strategy is the default and may be omitted.

endif::showscript[]
== Deployments

.Managing Deployments

* To start new deployment manually:
+
----
$ oc deploy <deployment_config> --latest
----
** If deployment is already in progress, message displays and deployment does
 not start

.Viewing Deployments
* To get basic information about recent deployments:
+
----
$ oc describe <deployment_config>
----

** Shows details, including deployment currently running
* To get detailed information about deployment configuration and latest
 deployment:
+
----
$ oc describe dc <deployment_config>
----



ifdef::showscript[]
=== Transcript
Here are some examples of how to manage a deployment. When trying to deploy the
 latest deployment version, using the `--latest` flag, the new deployment starts
  only if no other deployment is in progress.

For more detailed information about a deployment configuration and the latest
 deployment, use the `oc describe` command.

endif::showscript[]
== Deployments

.Canceling and Retrying a Deployment
* To cancel running or stuck deployment:
+
----
$ oc deploy <deployment_config> --cancel
----
** Cancellation is best-effort operation
** May take some time to complete

** Possible deployment will complete before cancellation

* To retry last failed deployment:
+
----
$ oc deploy <deployment_config> --retry
----
** If last deployment did not fail, message displays and deployment not retried

** Retrying deployment restarts deployment; does not create new version

** Restarted deployment has same configuration as when it failed


ifdef::showscript[]
=== Transcript

You can use the `--cancel` flag to cancel a running deployment that is stuck or
 failing. Cancellation is a best-effort operation. It may take some time to
  complete, and it is possible that the deployment will partially or totally
   complete before the cancellation is effective.

The `--retry` flag reruns a previously failed deployment. Note that if the last
 deployment did not fail, a message displays, and the deployment is not retried.

Retrying a deployment restarts the deployment; it does not create a new
 deployment version. The restarted deployment has the same configuration as when
  it failed.



endif::showscript[]
== Deployments

.Rolling Back a Deployment

* Rollbacks revert application to previous deployment
** Can be performed using REST API or CLI
* To roll back to previous deployment:
+
----
$ oc rollback <deployment>
----

** Configuration template is reverted to deployment specified in rollback command
** New deployment is started

** Image change triggers in deployment configuration are disabled as part of
 rollback to prevent unwanted deployments soon after rollback completes

* To re-enable image change triggers:
+
----
$ oc deploy <deployment_config> --enable-triggers
----

ifdef::showscript[]
=== Transcript
Rollbacks revert an application back to a previous deployment and can be
 performed using the REST API or the CLI.

The deployment configuration’s template is reverted to match the deployment
 specified in the rollback command, and a new deployment is started.

Image change triggers on the deployment configuration are disabled as part of
 the rollback to prevent unwanted deployments soon after the rollback is
  complete. You can re-enable the triggers with the command shown.


endif::showscript[]
== Deployments

.Deployment Configuration Triggers

* Drive creation of new deployment in response to events
** Events can be inside or outside OpenShift Enterprise

* If no triggers defined, deployment must be started manually

.`ConfigChange` Trigger

* Results in new deployment whenever changes are detected to replication
 controller template of deployment configuration

* If `ConfigChange` trigger is defined, first deployment is automatically
 created soon after deployment configuration is created

* `ConfigChange` trigger:
+
----
"triggers": [
  {
    "type": "ConfigChange"
  }
]
----

ifdef::showscript[]
=== Transcript
A deployment configuration can contain triggers that drive the creation of new
 deployments in response to events, both inside and outside OpenShift Enterprise.

If no triggers are defined in a deployment configuration, deployments must be
 started manually.

The `ConfigChange` trigger results in a new deployment whenever changes are
 detected to the replication controller template of the deployment configuration.

If a `ConfigChange` trigger is defined in a deployment configuration, the first
 deployment is automatically created soon after the deployment configuration
  itself is created.

endif::showscript[]
== Deployments

.`ImageChange` Trigger

* Results in new deployment whenever value of image stream tag changes

* In example below:
** When `latest` tag value of `origin-ruby-sample` image stream changes
** And when new tag value differs from current image specified in `helloworld`
 container
** Then new deployment is created using new tag value for `helloworld` container
+
----
"triggers": [
  {
    "type": "ImageChange",
    "imageChangeParams": {
      "automatic": true,
      "from": {
        "kind": "ImageStreamTag",
        "name": "origin-ruby-sample:latest"
      },
      "containerNames": [
        "helloworld"
      ]
    }
  }
]
----




ifdef::showscript[]
=== Transcript
The `ImageChange` trigger results in a new deployment whenever the value of an
 image stream tag changes.

In the example, when the value of the `latest` tag for the `origin-ruby-sample`
 image stream changes, and the new tag value is higher than the current image
  specified in the deployment configuration’s `helloworld` container,
   a new deployment is created using the new tag value for the `helloworld`
    container.

Note that if the `automatic` option is set to `false`, the trigger is disabled.



endif::showscript[]
== Strategies

.Overview

* _Deployment configuration_ declares _strategy_ responsible for executing
 deployment process

* Applications have different requirements for availability and other
 considerations during deployments

* OpenShift Enterprise provides strategies to support variety of deployment
 scenarios

* `Rolling` strategy is default if deployment configuration does not specify
 strategy

ifdef::showscript[]
=== Transcript
A deployment configuration declares a strategy that is responsible for executing
 the deployment process.

Each application has different requirements for availability and other
 considerations during deployments.

OpenShift Enterprise provides out-of-the-box strategies to support a variety of
 deployment scenarios.

The `Rolling` strategy is the default strategy if a deployment configuration
 does not specify a strategy.

endif::showscript[]
== Strategies

.`Rolling` Strategy

* Performs rolling update and supports life-cycle hooks for injecting code into
 deployment process

* `Rolling` strategy:
+
----
"strategy": {
  "type": "Rolling",
  "rollingParams": {
    "timeoutSeconds": 120,
    "pre": {},
    "post": {}
  }
}
----


ifdef::showscript[]
=== Transcript

The `Rolling` strategy performs a rolling update and supports life-cycle hooks
 for injecting code into the deployment process.

In the example, `timeoutSeconds` is optional. The default value is 120.

 `pre`  and `post` are life-cycle hooks that happen before or after the
 deployment

endif::showscript[]
== Strategies

* `Rolling` strategy:
** Executes `pre` life-cycle hooks
** Scales up new deployment by one
** Scales down old deployment by one
** Repeats scaling until:
*** New deployment reaches specified replica count
*** Old deployment is scaled to zero
** Executes `post` life-cycle hooks

WARNING: During scale up, if replica count of the deployment is greater than
 one, the first deployment replica is validated for readiness before fully
  scaling up the deployment. If this validation fails, the deployment fails.

NOTE: When executing a `post` life-cycle hook, all failures are ignored
 regardless of the failure policy specified in the hook.

ifdef::showscript[]
=== TranscriptR

The `Rolling` strategy:

- Executes any `pre` life-cycle hooks.
- Scales up the new deployment by one.
- Scales down the old deployment by one.
- Repeats this scaling until the new deployment reaches the specified replica
count and the old deployment is scaled to zero.
- Executes any `post` life-cycle hooks.


During the scaling-up process, if the replica count of the deployment is greater
 than one, the first replica of the deployment is validated for readiness before
  fully scaling up the deployment. If the validation of the first replica fails,
   the deployment is considered a failure.

When executing a `post` life-cycle hook, all failures are ignored regardless of
 the failure policy specified in the hook.


endif::showscript[]
== Strategies

.`Recreate` Strategy

* Has basic rollout behavior and supports life-cycle hooks for injecting code
 into deployment process

* `Recreate` strategy:
+
----
"strategy": {
  "type": "Recreate",
  "recreateParams": {
    "pre": {},
    "post": {}
  }
}
----


ifdef::showscript[]
=== Transcript
The `Recreate` strategy has basic rollout behavior and supports life-cycle hooks
 for injecting code into the deployment process.

In the example, `recreateParams` are optional. `pre` and `post` are both
 life-cycle hooks that happen before and after the deployment.

endif::showscript[]
== Strategies

* `Recreate` strategy:
** Executes `pre` life-cycle hooks
** Scales down previous deployment to zero
** Scales up new deployment
** Executes `post` life-cycle hooks


WARNING: During scale up, if the replica count of the deployment is greater than
 one, the first deployment replica is validated for readiness before fully
  scaling up the deployment. If this validation fails, the deployment fails.

NOTE: When executing a `post` life-cycle hook, all failures are ignored
 regardless of the failure policy specified in the hook.

ifdef::showscript[]
=== Transcript

* The `Recreate` strategy:
- Executes any `pre` life-cycle hooks
- Scales down the previous deployment to zero
- Scales up the new deployment.
- Executes any `post` life-cycle hooks


During the scaling-up process, if the replica count of the deployment is greater
 than one, the first deployment replica is validated for readiness before fully
  scaling up the deployment. If this validation fails, the deployment fails.

When executing a `post` life-cycle hook, all failures are ignored regardless of
 the failure policy specified in the hook.

endif::showscript[]
== Strategies

.`Custom` Strategy

* Lets you define deployment behavior

* Example `Custom` strategy:
+
----
"strategy": {
  "type": "Custom",
  "customParams": {
    "image": "organization/strategy", <1>
    "command": ["command", "arg1"], <2>
    "environment": [
      {
        "name": "ENV_1",  <3>
        "value": "VALUE_1"
      }
    ]
  }
}
----
<1> `organization/strategy` Docker image provides deployment behavior
<2> Optional `command` array overrides `CMD` directive specified in image Dockerfile
<3> Optional environment variables added to execution environment

ifdef::showscript[]
=== Transcript
The `Custom` strategy lets you provide your own deployment behavior.

Here is an example `Custom` strategy. Note the following:

. The `organization/strategy` Docker image provides deployment behavior.
. The optional `command` array overrides the `CMD` directive specified in the image
 Dockerfile.
. The optional environment variables are added to the execution environment.





endif::showscript[]
== Strategies

* OpenShift Enterprise provides two environment variables for strategy process:

[cols="2"]
|===
| Environment Variable| Description
|`OPENSHIFT_DEPLOYMENT_NAME`| Name of new deployment (replication controller)
|`OPENSHIFT_DEPLOYMENT_NAMESPACE`| Namespace of new deployment
|===

ifdef::showscript[]
=== Transcript
OpenShift Enterprise provides these two environment variables for use with the
 strategy process.


endif::showscript[]
== Life-cycle Hooks

.Overview

* `Recreate` and `Rolling` strategies support life-cycle hooks
** Allow behavior to be injected into deployment process at predefined points

* `pre` life-cycle hook:
+
----
"pre": {
  "failurePolicy": "Abort",
  "execNewPod": {}
}
----

** `execNewPod` is pod-based life-cycle hook
* Every hook has `failurePolicy`

ifdef::showscript[]
=== Transcript
The `Recreate` and `Rolling` strategies support life-cycle hooks, which allow
 behavior to be injected into the deployment process at predefined points in the
  strategy.

The example shows a `pre` life-cycle hook.
`execNewPod` is a pod-based life-cycle hook.

Every hook has a failure policy.

endif::showscript[]
== Life-cycle Hooks

.Failure Policy

* `failurePolicy` defines action strategy takes when hook fails

[cols="1,4"]
|===
|Value | Action
|`Abort`| Abort deployment if if hook fails.
|`Retry`|Retry hook execution until it succeeds.
|`Ignore`|Ignore hook failure and proceed with deployment.
|===

WARNING: Some hook points for a strategy might support only a subset of failure
 policy values. For example, the `Recreate` and `Rolling` strategies do not
  support the `Abort` policy for a `post` deployment life-cycle hook.


ifdef::showscript[]
=== Transcript
Every hook has a failure policy that defines the action the strategy should take
 when a hook failure is encountered.

Note that some hook points for a strategy might support only a subset of failure
 policy values. For example, the `Recreate` and `Rolling` strategies do not
  currently support the `Abort` policy for a `post` deployment life-cycle hook.

endif::showscript[]
== Life-cycle Hooks

.Pod-Based Life-cycle Hook

* Hooks have type-specific field that describes how to execute hook

* Pod-based hooks are only supported type
** Specified in `execNewPod` field
* Pod-based life-cycle hooks execute hook code in new pod derived from deployment
 configuration template

ifdef::showscript[]
=== Transcript
Hooks have a type-specific field that describes how to execute the hook.

Pod-based life-cycle hooks execute hook code in a new pod derived from the
 deployment configuration template.



endif::showscript[]

//ISSUE: Update this in 3.1
== Life-cycle Hooks

.Simplified Deployment Configuration

----
{
  "kind": "DeploymentConfig",
  "apiVersion": "v1",
  "metadata": {
    "name": "frontend"
  },
  "spec": {
    "template": {
      "metadata": {
        "labels": {
          "name": "frontend"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "helloworld", <1>
            "image": "openshift/origin-ruby-sample"
          }
        ]
      }
    }
    "replicas": 5,
    "selector": {
      "name": "frontend"
    },
    "strategy": {
      "type": "Rolling",
      "rollingParams": {
        "pre": {
          "failurePolicy": "Abort", <2>
          "execNewPod": {
            "containerName": "helloworld", <3>
            "command": [
              "/usr/bin/command", "arg1", "arg2" <4>
            ],
            "env": [ <5>
              {
                "name": "CUSTOM_VAR1",
                "value": "custom_value1"
              }
            ]
          }
        }
      }
    }
  }
}
----
<1> `pre` hook executes in new pod using `openshift/origin-ruby-sample` image from  `helloworld` container

<2> Because hook failure policy is `Abort`, deployment fails if hook fails

<3> `helloworld` name refers to `spec.template.spec.containers[0].name`

<4> hook container command is `/usr/bin/command arg1 arg2`, which overrides any `ENTRYPOINT` defined by `openshift/origin-ruby-sample` image

<5> `env` section contains optional environment variables
  for hook container, such as `CUSTOM_VAR1=custom_value1`

ifdef::showscript[]
=== Transcript
This simplified example deployment configuration uses the `Rolling` strategy.
 Triggers and some other minor details are omitted for brevity.

Note the following call-outs in the example:

. The `pre` hook is executed in a new pod using the
 `openshift/origin-ruby-sample` image from the `helloworld` container.

. Because the hook failure policy is `Abort`, the deployment fails if the hook
 fails.

. The `helloworld` name refers to `spec.template.spec.containers[0].name`.

. The hook container command is `/usr/bin/command arg1 arg2`. This command
 overrides any `ENTRYPOINT` defined by the `openshift/origin-ruby-sample` image.

. The hook container will have the `CUSTOM_VAR1=custom_value1` environment
 variable. The `env` section contains an optional set of environment variables
  for the hook container.



endif::showscript[]
== Build Triggers

* Control circumstances in which `buildConfig` runs

* Two types of triggers:
- Webhooks
- Image change

ifdef::showscript[]

=== Transcript

When defining `buildConfig`, you can define triggers to control the
 circumstances in which `buildConfig` should be run.

There are two types of triggers: webhooks and image change.

endif::showscript[]
== Build Triggers

.Webhook Triggers

* Trigger new build by sending request to OpenShift Enterprise API endpoint

* Define using GitHub webhooks or generic webhooks


.Displaying `buildConfig` Webhook URLs

* To display webhook URLs associated with build configuration:
+
----
$ oc describe buildConfig <name>
----

* If command does not display webhook URLs, then no webhook trigger is defined

ifdef::showscript[]

=== Transcript

Webhook triggers trigger a new build by sending a request to the OpenShift
 Enterprise API endpoint. You can define these triggers using GitHub webhooks
  or generic webhooks.

endif::showscript[]
== Build Triggers

.GitHub Webhook Triggers

* Handle call made by GitHub when repository is updated

* When defining trigger, specify `secret` value as part of URL supplied to
 GitHub
** Ensures that only you and your repository can trigger build

* JSON trigger definition within `buildConfig`:
+
----
{
  "type": "github",
  "github": {
    "secret": "secret101"
  }
}
----

** `describe` command retrieves GitHub webhook URL structured as follows:
+
----
http://<openshift_api_host:port>/osapi/v1/namespaces/<namespace>/buildconfigs/<name>/webhooks/<secret>/github
----

ifdef::showscript[]
=== Transcript
GitHub webhooks handle the call made by GitHub when a repository is updated.

When defining the trigger, you must specify a value for `secret` as part of the
 URL you supply to GitHub when configuring the webhook. The `secret` value
  ensures that only you and your repository can trigger the build.

The first example is a JSON `buildConfig` trigger definition, and the second is
 a GitHub webhook URL.

endif::showscript[]
== Build Triggers

.Generic Webhook Triggers

* Can be invoked from any system that can make web request

* Must specify `secret` value when defining trigger
* Caller must provide `secret` value to trigger build
* JSON trigger definition within `buildConfig`:

+
----
{
  "type": "generic",
  "generic": {
    "secret": "secret101"
  }
}
----
* To set up caller, provide calling system with URL of generic webhook endpoint:
+
----
http://<openshift_api_host:port>/osapi/v1/namespaces/<namespace>/buildconfigs/<name>/webhooks/<secret>/generic
----

ifdef::showscript[]
=== Transcript
Generic webhooks can be invoked from any system capable of making a web request.

As with a GitHub webhook, you must specify a value for `secret` when defining
 the trigger, and the caller must provide this value to trigger the build. The
  first example is a JSON trigger definition in the `buildConfig` section, and
   the second is a generic webhook URL.

endif::showscript[]
== Build Triggers

.Image Change Triggers

* Allow your build to be automatically invoked when new upstream image is
 available
- If build based on Red Hat Enterprise Linux image, can trigger build to run any
 time that image changes
- Your application image always runs latest Red Hat Enterprise Linux base image

* To configure image change trigger, define `ImageStream` to point to upstream
 trigger image:
+
----
{
  "kind": "ImageStream",
  "apiVersion": "v1",
  "metadata": {
    "name": "ruby-20-rhel7"
  }
}
----
+
** Defines image stream tied to Docker image repository at
 `<system-registry>/<namespace>/ruby-20-rhel7`
** `<system-registry>` is defined as service with name `docker-registry` running
 in OpenShift Enterprise

ifdef::showscript[]
=== Transcript

Image change triggers allow your build to be automatically invoked when a new
 upstream image is available. For example, if a build is based on a Red Hat
  Enterprise Linux image, you can trigger that build to run any time the Red Hat
   Enterprise Linux image changes. As a result, the application image is always
    running on the latest base image.


endif::showscript[]
== Build Triggers

* To define build with strategy that consumes image stream:
+
----
{
  "strategy": {
    "type": "Source",
    "sourceStrategy": {
      "from": {
        "kind": "ImageStreamTag",
        "name": "ruby-20-rhel7:latest"
      },
    }
  }
}
----
+
** `sourceStrategy` definition consumes `latest` tag of image stream named
 `ruby-20-rhel7` located in this namespace


ifdef::showscript[]
=== Transcript
This example defines a build with a strategy that consumes the image stream
 `ruby-20-rhel7`.
endif::showscript[]
== Build Triggers

* Image change trigger:
+
----
{
  "type": "imageChange",
  "imageChange": {}
}
----

* Resulting build :
+
----
{
  "strategy": {
    "type": "Source",
    "sourceStrategy": {
      "from": {
        "kind": "DockerImage",
        "name": "172.30.17.3:5001/mynamespace/ruby-20-centos7:immutableid"
      }
    }
  }
}
----
* Trigger monitors image stream and tag defined by `strategy` section's `from`
 field
** When change occurs, new build is triggered
* Ensures that triggered build uses new image just pushed to repository
* Build can be rerun any time with same inputs


ifdef::showscript[]
=== Transcript
This example defines an image change trigger that monitors the image stream and
 tag as defined by the `from` field.

When a change occurs, a new build is triggered and is supplied with a static
 Docker tag that points to the new image that was just created. The strategy
  uses this new image when it executes the build.

This ensures that the triggered build uses the new image that was just pushed to
 the repository, and the build can be rerun any time with the same inputs.



endif::showscript[]
== Summary

* Deployments
* Strategies
* Life-cycle Hooks
* Build Triggers

ifdef::showscript[]
=== Transcript
In this module you learned about the the value of deployments to the developer
 and to operational workflows. You learned the different strategies that you can
  use to deploy a new version of your application.

Life-cycle hooks were covered, including how to use them as build triggers, and
 finally, you learned some practical commands to manage a redeployment or
  rollback.

endif::showscript[]
