== Deployments

.Deployment Configuration Example

----
{
  "kind": "DeploymentConfig",
  "apiVersion": "v1",
  "metadata": {
    "name": "frontend"
  },
  "spec": {
    "template": { <1>
      "metadata": {
        "labels": {
          "name": "frontend"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "helloworld",
            "image": "openshift/origin-ruby-sample",
            "ports": [
              {
                "containerPort": 8080,
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    }
    "replicas": 5, <2>
    "selector": {
      "name": "frontend"
    },
    "triggers": [
      {
        "type": "ConfigChange" <3>
      },
      {
        "type": "ImageChange", <4>
        "imageChangeParams": {
          "automatic": true,
          "containerNames": [
            "helloworld"
          ],
          "from": {
            "kind": "ImageStreamTag",
            "name": "origin-ruby-sample:latest"
          }
        }
      }
    ],
    "strategy": {
      "type": "Rolling" <5>
    }
  }
}
----

<1> Replication controller template named `frontend`, which describes a simple Ruby
 application
<2> Creates 5 replicas of `frontend` by default
<3> If replication controller template changes, configuration change trigger creates new deployment
<4> If new version of `origin-ruby-sample:latest` image repository is available, image change trigger creates new deployment
<5> `Rolling` is default strategy and may be omitted

ifdef::showscript[]

=== Transcript


This is an example of a `deploymentConfig` resource. Note the following in the
 code sample:

. The replication controller template named `frontend` describes a simple Ruby
 application.
. There will be 5 replicas of `frontend` by default.
. A configuration change trigger causes a new deployment to be created any time
 the replication controller template changes.
. An image change trigger causes a new deployment to be created each time a new
 version of the `origin-ruby-sample:latest` image repository is available.
. The `Rolling` strategy is the default and may be omitted.

endif::showscript[]
