== Deployments
:noaudio:

.Manage Deployments

* To start a new deployment manually:
+
----
$ oc deploy <deployment_config> --latest
----
** If there’s already a deployment in progress, the command will display a
message and a new deployment will not be started.

* Viewing a Deployment
** To get basic information about recent deployments:
+
----
$ oc deploy <deployment_config>
----

** This will show details about the latest and recent deployments, including
any currently running deployment.
* For more detailed information about a deployment configuration and the latest
  deployment:
+
----
$ oc describe dc <deployment_config>
----



ifdef::showscript[]
=== Transcript
Here are a few examples of how to manage a deployment.
When trying to deploy the latest deployment version, using the --latest flag,
the new deployment will only start of no other deployment is in progress.

For more detailed information about a deployment configuration and the latest
  deployment use the *oc describe* command.

endif::showscript[]


