== Deployments
:noaudio:

.Manage Deployments

* Canceling and Retrying a Deployment
- To cancel a running or *stuck* deployment:
+
----
$ oc deploy <deployment_config> --cancel
----
- The cancellation is a best-effort operation, and may take some time to
complete. It’s possible the deployment will partially or totally complete
before the cancellation is effective.

* Retrying a Deployment
- To retry the last failed deployment:
+
----
$ oc deploy <deployment_config> --retry
----
- If the last deployment didn’t fail,
the command will display a message and the deployment will not be retried.
** Retrying a deployment restarts the deployment and does not create a new
deployment version. The restarted deployment will have the same configuration
it had when it failed.


ifdef::showscript[]
=== Transcript
Here are a few more examples of how to manage a deployment.
You can cancel a running deployment that is stuck or failing using the --cancel
flag,  cancellation is a best-effort operation, and may take some time to
complete. It’s possible the deployment will partially or totally complete
before the cancellation is effective.

The --retry flag creates a re-run of a prevoiusly failed deployment, note that
if the last deployment didn’t fail, the command will display a message and the
deployment will not be retried.

Retrying a deployment restarts the deployment and does not create a new
deployment version. The restarted deployment will have the same configuration
it had when it failed.



endif::showscript[]

