== Deployments


.Canceling and Retrying a Deployment
* To cancel running or stuck deployment:
+
----
$ oc deploy <deployment_config> --cancel
----
** Cancellation is best-effort operation
** May take some time to complete

** Possible deployment will complete before cancellation

* To retry last failed deployment:
+
----
$ oc deploy <deployment_config> --retry
----
** If last deployment did not fail, message displays and deployment not retried

** Retrying deployment restarts deployment; does not create new version

** Restarted deployment has same configuration as when it failed


ifdef::showscript[]
=== Transcript

You can use the `--cancel` flag to cancel a running deployment that is stuck or
 failing. Cancellation is a best-effort operation. It may take some time to
  complete, and it is possible that the deployment will partially or totally
   complete before the cancellation is effective.

The `--retry` flag reruns a previously failed deployment. Note that if the last
 deployment did not fail, a message displays, and the deployment is not retried.

Retrying a deployment restarts the deployment; it does not create a new
 deployment version. The restarted deployment has the same configuration as when
  it failed.



endif::showscript[]
