== Deployments

.Deployment Configuration Triggers

* Drive creation of new deployment in response to events
** Events can be inside or outside OpenShift Enterprise

* If no triggers defined, deployment must be started manually

.`ConfigChange` Trigger

* Results in new deployment whenever changes are detected to replication
 controller template of deployment configuration

* If `ConfigChange` trigger is defined, first deployment is automatically
 created soon after deployment configuration is created

* `ConfigChange` trigger:
+
----
"triggers": [
  {
    "type": "ConfigChange"
  }
]
----

ifdef::showscript[]
=== Transcript
A deployment configuration can contain triggers that drive the creation of new
 deployments in response to events, both inside and outside OpenShift Enterprise.

If no triggers are defined in a deployment configuration, deployments must be
 started manually.

The `ConfigChange` trigger results in a new deployment whenever changes are
 detected to the replication controller template of the deployment configuration.

If a `ConfigChange` trigger is defined in a deployment configuration, the first
 deployment is automatically created soon after the deployment configuration
  itself is created.

endif::showscript[]
