== Strategies
:noaudio:

.Recreate Strategy

The Recreate strategy has basic rollout behavior and supports lifecycle hooks
for injecting code into the deployment process.

* The following is an example of the Recreate strategy:
+
[source,json]
----
"strategy": {
  "type": "Recreate",
  "recreateParams": { <1>
    "pre": {}, <2>
    "post": {}
  }
}
----
<1> recreateParams are optional.
<2> pre and post are both lifecycle hooks.

* The Recreate strategy will:

** Execute any "pre" lifecycle hook.
** Scale down the previous deployment to zero.
** Scale up the new deployment.
** Execute any "post" lifecycle hook.
** During scale up, if the replica count of the deployment is greater than one,
the first replica of the deployment will be validated for readiness before fully
scaling up the deployment. If the validation of the first replica fails, the
deployment will be considered a failure.

** When executing the "post" lifecycle hook, all failures will be ignored
regardless of the failure policy specified on the hook.

ifdef::showscript[]

endif::showscript[]

