== Strategies
:noaudio:

* `Rolling` strategy:
** Executes `pre` lifecycle hooks
** Scales up new deployment by one
** Scales down old deployment by one
** Repeats scaling until:
*** New deployment reaches specified replica count
*** Old deployment is scaled to zero
** Executes `post` lifecycle hooks

WARNING: During scale up, if replica count of the deployment is greater than
 one, the first deployment replica is validated for readiness before fully
  scaling up the deployment. If this validation fails, the deployment fails.

NOTE: When executing a `post` lifecycle hook, all failures are ignored
 regardless of the failure policy specified in the hook.

ifdef::showscript[]
=== Transcript

The `Rolling` strategy:

- Executes any `pre` lifecycle hooks.
- Scales up the new deployment by one.
- Scales down the old deployment by one.
- Repeats this scaling until the new deployment reaches the specified replica
count and the old deployment is scaled to zero.
- Executes any `post` lifecycle hooks.


During the scaling-up process, if the replica count of the deployment is greater
 than one, the first replica of the deployment is validated for readiness before
  fully scaling up the deployment. If the validation of the first replica fails,
   the deployment is considered a failure.

When executing a `post` lifecycle hook, all failures are ignored regardless of
 the failure policy specified in the hook.


endif::showscript[]
