== Strategies
:noaudio:

.Recreate Strategy - Continued

* The Recreate strategy will:
- Execute any "pre" lifecycle hook.
- Scale down the previous deployment to zero.
- Scale up the new deployment.
- Execute any "post" lifecycle hook.
- During scale up, if the replica count of the deployment is greater than one,
the first replica of the deployment will be validated for readiness before fully
scaling up the deployment. If the validation of the first replica fails, the
deployment will be considered a failure.

NOTE: When executing the "post" lifecycle hook, all failures will be ignored
regardless of the failure policy specified on the hook.

ifdef::showscript[]
=== Transcript

* The Recreate strategy will:
- Execute any "pre" lifecycle hook.
- Scale down the previous deployment to zero.
- Scale up the new deployment.
- Execute any "post" lifecycle hook.
- During scale up, if the replica count of the deployment is greater than one,
the first replica of the deployment will be validated for readiness before fully
scaling up the deployment. If the validation of the first replica fails, the
deployment will be considered a failure.

Note that, when executing the "post" lifecycle hook, all failures will be ignored
regardless of the failure policy specified on the hook.
endif::showscript[]

