== Strategies
:noaudio:

.Custom Strategy

The Custom strategy allows you to provide your own deployment behavior.

* The following is an example of the Custom strategy:
+
[source,json]
----
"strategy": {
  "type": "Custom",
  "customParams": {
    "image": "organization/strategy",
    "command": ["command", "arg1"],
    "environment": [
      {
        "name": "ENV_1",
        "value": "VALUE_1"
      }
    ]
  }
}
----
+
** In the above example, the organization/strategy Docker image provides the
deployment behavior. The optional command array overrides any CMD directive
specified in the image’s Dockerfile. The optional environment variables provided
  are added to the execution environment of the strategy process.

ifdef::showscript[]
=== Transcript
The Custom strategy allows you to provide your own deployment behavior.

* The following is an example of the Custom strategy:

In the above example, the organization/strategy Docker image provides the
deployment behavior. The optional command array overrides any CMD directive
specified in the image’s Dockerfile. The optional environment variables provided
  are added to the execution environment of the strategy process.


endif::showscript[]

