== Strategies


* `Recreate` strategy:
** Executes `pre` lifecycle hooks
** Scales down previous deployment to zero
** Scales up new deployment
** Executes `post` lifecycle hooks


WARNING: During scale up, if the replica count of the deployment is greater than
 one, the first deployment replica is validated for readiness before fully
  scaling up the deployment. If this validation fails, the deployment fails.

NOTE: When executing a `post` lifecycle hook, all failures are ignored
 regardless of the failure policy specified in the hook.

ifdef::showscript[]
=== Transcript

* The `Recreate` strategy:
- Executes any `pre` lifecycle hooks
- Scales down the previous deployment to zero
- Scales up the new deployment.
- Executes any `post` lifecycle hooks


During the scaling-up process, if the replica count of the deployment is greater
 than one, the first deployment replica is validated for readiness before fully
  scaling up the deployment. If this validation fails, the deployment fails.

When executing a `post` lifecycle hook, all failures are ignored regardless of
 the failure policy specified in the hook.
