== Build Triggers
:noaudio:

.Webhook Triggers - Generic webooks

Generic webhooks can be invoked from any system capable of making a web request.

* As with a GitHub webhook, you must specify a secret when defining the trigger,
and the caller must provide this secret to trigger the build. The following is
an example trigger definition JSON within the buildConfig:

[source,json]
----
{
  "type": "generic",
  "generic": {
    "secret": "secret101"
  }
}
----
* To set up the caller, supply the calling system with the URL of the generic
webhook endpoint for your build:
+
----
http://<openshift_api_host:port>/osapi/v1/namespaces/<namespace>/buildconfigs/<name>/webhooks/<secret>/generic
----

ifdef::showscript[]
=== Transcript
Generic webhooks can be invoked from any system capable of making a web request.

* As with a GitHub webhook, you must specify a secret when defining the trigger,
and the caller must provide this secret to trigger the build. The first example
is a trigger definition JSON within the buildConfig and the second is a generic
webhook URL Example.

endif::showscript[]


