== Build Triggers
:noaudio:

.GitHub Webhook Triggers

* Handle call made by GitHub when repository is updated

* When defining trigger, specify `secret` value as part of URL supplied to GitHub
** Ensures that only you and your repository can trigger build

* JSON trigger definition within `buildConfig`:
+
----
{
  "type": "github",
  "github": {
    "secret": "secret101"
  }
}
----

** `describe` command retrieves GitHub webhook URL structured as follows:
+
----
http://<openshift_api_host:port>/osapi/v1/namespaces/<namespace>/buildconfigs/<name>/webhooks/<secret>/github
----

ifdef::showscript[]
=== Transcript
GitHub webhooks handle the call made by GitHub when a repository is updated.

When defining the trigger, you must specify a value for `secret` as part of the URL you supply to GitHub when configuring the webhook. The `secret` value ensures that only you and your repository can trigger the build.

The first example is a JSON `buildConfig` trigger definition, and the second is a GitHub webhook URL.

endif::showscript[]

