:toc2:
:icons: images/icons

== Deployment Life Cycle Lab

=== Overview

In this lab you explore the different aspects of the application life cycle.

This lab includes two sections:

. Roll Back, Activate, and Code Life Cycle
+
In this section you manage the various phases of the deployment's life cycle.
. Create and Use Web Hooks
+
In this section you create a Git webhook and automatically start a new build and a new deployment by pushing a code change into your Git repository.

:numbered:

== Roll Back, Activate, and Code Life Cycle

No one codes correctly all the time. On occasion you may want to revert to a previous incarnation of your application to restart a programming task. Other times you may want to move to a newer version.

In this section, you modify the front end of the `hello-ruby` application and then rebuild. Afterward, you revert to the original version and then go on to your rebuilt version.

The next sections require a GitHub account.

=== Fork Repository

* If you have not done so already, go to the Git web interface and click *Fork* in the
 upper right corner of the GitHub web UI to fork the Git repository
  `https://github.com/openshift/ruby-hello-world` into your own account.

=== Create Your Application

[NOTE]
Remember that `buildconfig` (the build-configuration file) instructs OpenShift Container Platform how to perform a build.

. As `root`, create a project for user `marina`:
+
----
[root@master1 ~]# oadm new-project lifecycle --display-name="Lifecycle Lab" \
    --description="This is the project we use to learn about Lifecycle management" \
    --admin=marina --node-selector='region=primary'
----

. Switch to user `marina` and use the `lifecycle` project:
+
----
[root@master1 ~]# su - marina
[marina@master1 ~]$ oc project lifecycle
----

. Create an application from the `https://github.com/openshift/ruby-hello-world` repository:
+
----
[marina@master1~]$ oc new-app https://github.com/openshift/ruby-hello-world --strategy=source
----

* The `--strategy=source` option forces `oc new-app` to adopt the S2I strategy. 
* A simpler alternative is the `new-app` command, using your own repository, but you are intentionally picking an incorrect repository as part of this learning exercise.

. Run `oc env` to add the environment variables for a database to be used later:
+
----
[marina@master1~]$ oc env dc/ruby-hello-world MYSQL_USER=mysqluser \
  MYSQL_PASSWORD=redhat MYSQL_DATABASE=mydb
----

. While waiting for the build to finish, expose your service to the world so that you can test it from your local browser:
+
----
[marina@master1~]$ oc expose service ruby-hello-world \
  --name="ruby-hello-world" \
  --hostname=ruby-hello-world.lifecycle.cloudapps-${guid}.oslab.opentlc.com
----

. View the current `buildconfig` file for your application:
+
----
[marina@master1~]$ oc get buildconfig ruby-hello-world -o yaml
----

. Verify that the output is similar to the following:
+
----
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2016-07-29T09:47:05Z
  labels:
    app: ruby-hello-world
  name: ruby-hello-world
  namespace: lifecycle
  resourceVersion: "28797"
  selfLink: /oapi/v1/namespaces/lifecycle/buildconfigs/ruby-hello-world
  uid: 688ca0bc-5571-11e6-83dc-2cc2600a5748
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ruby-hello-world:latest
  postCommit: {}
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/openshift/ruby-hello-world
    secrets: []
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ruby-20-rhel7:latest
    type: Source
  triggers:
  - github:
      secret: jV5Ipwr7__4ae_sZG2Jm
    type: GitHub
  - generic:
      secret: ALNUyArydLb22JqdXYIb
    type: Generic
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: registry.access.redhat.com/openshift3/ruby-20-rhel7:latest
    type: ImageChange
status:
  lastVersion: 1
----

. Observe that the current configuration points at the `openshift/ruby-hello-world` repository.
* Because you forked this repository earlier, you can now _repoint_ your configuration.

=== Repoint Your Configuration

. Run `oc edit` to repoint the configuration:
+
----
[marina@master1~]$  oc edit bc ruby-hello-world
----

.. Change the `uri` reference to match the name of your GitHub repository, which is based in part on your GitHub username: `https://github.com/<GitHubUsername>/ruby-hello-world`.
+
[IMPORTANT]
Replace `<GitHubUsername>` with your GitHub username. For example, if your GitHub username is `jeandeaux`, the name of your GitHub repository is `https://github.com/jeandeaux/ruby-hello-world`.

.. Enter `:wq` to save and exit vi.

* There are other ways to achieve this outcome. 
* This way is used to cover the `oc edit` and the `oc start-build` commands. 


. Run `oc get buildconfig ruby-hello-world -o yaml` again. Notice that `uri` has been updated.

. Run `oc get builds` to check if the new build has started:
+
----
[marina@master1~]$ oc get builds
----

. If the build has not started:
.. Start it yourself:
+
----
[marina@master1~]$ oc get bc
NAME               TYPE      SOURCE
ruby-hello-world   Docker    https://github.com/YOURUSERNAME/ruby-hello-world
----
+
----
[marina@master1~]$ oc start-build ruby-hello-world
ruby-hello-world-2
----
.. Follow the build log:
+
----

[marina@master1~]$ oc get builds -w
NAME                 TYPE      FROM	 STATUS     STARTED              DURATION
ruby-hello-world-1   Source    Git	 Complete   16 minutes ago	 4m25s
ruby-hello-world-2   Source    Git	 Complete   About a minute ago   1m46s
----
+
----
[marina@master1~]$ oc logs -f bc/ruby-hello-world
I0709 23:41:08.493756       1 docker.go:69] Starting Docker build from justanother1/ruby-hello-world-7 BuildConfig ...
I0709 23:41:08.508448       1 tar.go:133] Adding to tar: /tmp/docker-build062004796/.gitignore as .gitignore
I0709 23:41:08.509588       1 tar.go:133] Adding to tar: /tmp/docker-build062004796/.sti/bin/README as .sti/bin/README
I0709 23:41:08.509953       1 tar.go:133] Adding to tar: /tmp/docker-build062004796/.sti/environment as .sti/environment
I0709 23:41:08.510183       1 tar.go:133] Adding to tar: /tmp/docker-build062004796/Dockerfile as Dockerfile
I0709 23:41:08.510548       1 tar.go:133] Adding to tar: /tmp/docker-build062004796/Gemfile as Gemfile
.......
Cropped Output
.......
----

. Search for the available MySQL applications (templates):
+
----
[marina@master1-82bc ~]$ oc new-app --search mysql
Templates (oc new-app --template=<template>)
----
* Expect the output to look like this:
+
----
mysql-persistent
  Project: openshift
  MySQL database service, with persistent storage. Scaling to more than one replica is not supported
mysql-ephemeral
  Project: openshift
  MySQL database service, without persistent storage. WARNING: Any data stored will be lost upon pod destruction. Only use this template for testing
eap64-mysql-s2i
  Project: openshift
  Application template for EAP 6 MySQL applications built using S2I.
jws30-tomcat7-mysql-persistent-s2i
  Project: openshift
  Application template for JWS MySQL applications with persistent storage built using S2I.
jws30-tomcat8-mysql-s2i
  Project: openshift
  Application template for JWS MySQL applications built using S2I.
jws30-tomcat7-mysql-s2i
  Project: openshift
  Application template for JWS MySQL applications built using S2I.
cakephp-mysql-example
  Project: openshift
  An example CakePHP application with a MySQL database
dancer-mysql-example
  Project: openshift
  An example Dancer application with a MySQL database
jws30-tomcat8-mysql-persistent-s2i
  Project: openshift
  Application template for JWS MySQL applications with persistent storage built using S2I.
eap64-mysql-persistent-s2i
  Project: openshift
  Application template for EAP 6 MySQL applications with persistent storage built using S2I.
----
+
----
Image streams (oc new-app --image-stream=<image-stream> [--code=<source>])
----
+
----
mysql
  Project: openshift
  Tags:    5.5, 5.6, latest

Docker images (oc new-app --docker-image=<docker-image> [--code=<source>])
----
+
----
mysql
  Registry: Docker Hub
  Tags:     latest
----

. Create the `database` application by running `oc new-app`:
+
----
[marina@master1~]$ oc new-app --template=mysql-ephemeral  --name=database \
--param MYSQL_USER=mysqluser --param MYSQL_PASSWORD=redhat \
--param MYSQL_DATABASE=mydb --param DATABASE_SERVICE_NAME=database
----


. Verify that your values were processed correctly:
+
----
[marina@master1~]$ oc env dc/database --list
# deploymentconfigs database, container mysql
# MYSQL_USER from secret database, key database-user
# MYSQL_PASSWORD from secret database, key database-password
# MYSQL_ROOT_PASSWORD from secret database, key database-root-password
MYSQL_DATABASE=mydb
----

. You must redeploy your front end so that it checks for the database again. You
 can delete just the pod, or you can redeploy the application:
+
----
[marina@master1 ~]$ oc deploy ruby-hello-world --latest   # (reference)
Flag --latest has been deprecated, use 'oc rollout latest' instead
Started deployment #2
Use 'oc logs -f dc/ruby-hello-world' to track its progress.
[marina@master1 ~]$ oc rollout latest ruby-hello-world
deploymentconfig "ruby-hello-world" rolled out
----

. Use this `oc logs` command to see the logs for your latest deployment:
+
----
[marina@master1~]$  oc logs -f dc/ruby-hello-world
I1222 01:54:45.485814       1 deployer.go:198] Deploying from lifecycle/ruby-hello-world-3 to lifecycle/ruby-hello-world-4 (replicas: 1)
I1222 01:54:46.913895       1 rolling.go:232] RollingUpdater: Continuing update with existing controller ruby-hello-world-4.
I1222 01:54:47.019320       1 rolling.go:232] RollingUpdater: Scaling up ruby-hello-world-4 from 0 to 1, scaling down ruby-hello-world-3 from 1 to 0 (keep 0 pods available, don't exceed 2 pods)
I1222 01:54:47.020399       1 rolling.go:232] RollingUpdater: Scaling ruby-hello-world-4 up to 1
I1222 01:54:51.372703       1 rolling.go:232] RollingUpdater: Scaling ruby-hello-world-3 down to 0
----

== Create and Use Webhooks

With webhooks, you can integrate external systems into your OpenShift environment so that they can start OpenShift builds. Generally speaking, you make code changes and update the code repository, after which a process hits OpenShift's webhook URL to start a build with the new code.

=== Create Webhook

Your GitHub account can configure a webhook whenever you push a commit to a specific branch.

. Find the webhook URL:
.. In the web console, navigate to your project.
.. Click *Browse* and then click *Builds*.
.. Select the `ruby-hello-world` app and click *Configuration*.

* Two webhook URLs are displayed.

. Copy the Github Webhook URL, which looks like this:
+
----
https://master1-GUID.oslab.opentlc.com:8443/oapi/v1/namespaces/lifecycle/buildconfigs/ruby-hello-world/webhooks/ALNUyArydLb22JqdXYIb/github
----

. In the GitHub repository, which you forked earlier, go to *Settings* -> *Webhooks and Services*.

. Paste the URL that you copied from the web console into the *Payload URL* field.

. Change 'Content type' to 'application/json'

. Leave the `secret` field empty

. Disable SSL verification.

. Click *Add Webhook*.

=== Test Webhook

To test your webhook, you are going to revise the code, commit, and push the change into the Git repository.

[TIP]
You can also test the webhook the usual way by cloning your repository locally, making the required changes, and pushing them to the repository.

. Go to your forked repository (`https://github.com/GitHubUsername/ruby-hello-world`) and find the `main.erb` file in the `views` folder.

* You can edit files in the GitHub web UI.

. Locate this HTML code:
+
----
    <div class="page-header" align=center>
      <h1> Welcome to an OpenShift v3 Demo App! </h1>
    </div>
----
+
. Change it to read as follows (including the deliberately misspelled `crustom`):
+
----
    <div class="page-header" align=center>
      <h1> This is my crustom demo! </h1>
    </div>
----

. Commit the change to the repository.

. Check if a build has started.
+
[CAUTION]
If another build is already running, this latest build may fail because both builds are pushing to the registry. Either run `oc delete build` to stop the other build or `oc start-build` to restart the failed build.

. Log in as `marina` and check the web UI to verify that the build is running.

. Wait for the build to complete. It can take a minute or two for the service endpoint to update.
. Use your browser to go to the application at `http://ruby-hello-world.lifecycle.cloudapps-GUID.oslab.opentlc.com/`.

* The output includes the deliberately misspelled `crustom`.
* If you try to access the application before the update is complete, you may see a `503` error.


=== Roll Back Application

Because you failed to properly test your application and your typo made it into production, you must revert to the previous version of your application.


. Log in to the web console as `marina`.

. Select *Browse* -> *Deployments*.

* Two deployments are at your front end: `1` and `2`.
+
[TIP]
====
You can also view this information from the CLI:

----
[marina@master1~]$ oc get replicationcontroller
----

The semantics of this syntax state that `DeploymentConfig` ensures that `replicationcontroller` is created to manage the deployment of the built `Image` from `ImageStream`.  [[Question out to writer about this. Seems like a lot to infer based on what's here.]]
====

. From the CLI, roll back the deployment:

.. Determine which builds are available:
+
----
[marina@master1~] oc get builds
----

.. Choose a deployment and see what a rollback to `ruby-hello-world-X` would
 look like (where X is your desired deployment):
+
----
[marina@master1~]$ oc rollback ruby-hello-world-X --dry-run
----
+
----
Name:           ruby-hello-world
Created:        39 minutes ago
Labels:         <none>
Latest Version: 9
Triggers:       Config, Image(ruby-hello-world@latest, auto=false)
Strategy:       Recreate
Template:
                        Selector:       deploymentconfig=ruby-hello-world
                        Replicas:       1
                        Containers:
                                NAME                    IMAGE                                                     ENV
                                ruby-hello-world        172.30.119.73:5000/lifecycle/ruby-hello-world@sha256:fcc9ce95e503429926dbe9e0cde304e0a0de19483e1cb79acada7334d7eb2504      MYSQL_DATABASE=mydb,MYSQL_PASSWORD=redhat,MYSQL_USER=root
Latest Deployment:      <none>
----
* From this output, you can see that you can go ahead with the rollback.

.. Roll back the deployment:
+
----
[marina@master1~]$ oc rollback ruby-hello-world-X # X is your desired deployment
#7 rolled back to ruby-hello-world-X
Warning: the following images triggers were disabled: ruby-hello-world:latest
  You can re-enable them with: oc set triggers dc/ruby-hello-world --auto
----

. Click the *Browse* tab of your project and note that you have a new pod in the *Pods* section.

. After a few minutes, go back to the application in your browser.

* The old "Welcome . . ." message is displayed.

=== Roll Your Application Forward

* To roll forward (activate) the typo-enabled application:
+
----
[marina@master1~]$ oc rollback ruby-hello-world-X # X is your desired deployment
#8 rolled back to ruby-hello-world-X
Warning: the following images triggers were disabled: ruby-hello-world:latest
  You can re-enable them with: oc set triggers dc/ruby-hello-world --auto
----
