== Strategies
:noaudio:

.Rolling Strategy

The Rolling strategy performs a rolling update and supports lifecycle hooks for
injecting code into the deployment process.

* The following is an example of the Rolling strategy:
+
[source,json]
----
"strategy": {
  "type": "Rolling",
  "rollingParams": {
    "timeoutSeconds": 120,
    "pre": {},
    "post": {}
  }
}
----
** How long to wait for a scaling event before giving up. Optional;
the default is 120.
** pre and post are both lifecycle hooks.

* The Rolling strategy will:
**  Execute any "pre" lifecycle hook.
** Scale up the new deployment by one.
** Scale down the old deployment by one.
** Repeat this scaling until the new deployment has reached the desired replica
count and the old deployment has been scaled to zero.
** Execute any "post" lifecycle hook.
+
WARNING: During scale up, if the replica count of the deployment is greater than
  one, the first replica of the deployment will be validated for readiness before
  fully scaling up the deployment. If the validation of the first replica fails,
  the deployment will be considered a failure.
+
WARNING: When executing the "post" lifecycle hook, all failures will be ignored
regardless of the failure policy specified on the hook.

ifdef::showscript[]

endif::showscript[]

