== Installation Scenario
:noaudio:

[cols="1,1,4,2"]
|=======================================================================
|Host |IP |Description |Labels
|*Master00* |`192.168.0.100` a|* Hosts the web console, _API service_, and _etcd store_
* Cannot be scheduled
* No need for label a|* *Region*: `NA`
* *Zone*: `NA`
* *Schedulable*: `false`
|*InfraNode00* |`192.168.0.101` |Used only to host
_Infrastructure_ containers such as `Registry` and HAProxy `Router` a|* *Region*: `Infra`
* *Zone*: `infranode`
* *Schedulable*: `true`
|*Node00* |`192.168.0.200` a|* Part of primary region
* Cohosts all user workloads a|* *Region*: `Primary`
* *Zone*: `East`
* *Schedulable*: `true`
|*Node01* |`192.168.0.201` a|* Part of primary region
* Cohosts all user workloads a|* *Region*: `Primary`
* *Zone*: `West`
* *Schedulable*: `true`
|`oselab` |`192.168.0.254` |Simulates the corporate DNS server
and NFS backend
|=======================================================================


ifdef::showscript[]

=== Transcript
In this sample scenario, you set up four hosts to simulate a regular environment.

You use the *master* host to host some of the management components of OpenShift Enterprise, such as the web console, the _API service_, and the _etcd store_.

While *Infranode* is a regular node like the others, you dedicate it to be used only for _Infrastructure containers_ by changing its labels. This is strictly a design choice, not a mandatory constraint.

The two remaining *nodes* are hosts that you use to run containers (pods) in the OpenShift Enterprise environment. You label the two nodes to be in the same region but different zones. This simulates the use-case of an environment in a single region and possibly two cloud availability zones.

endif::showscript[]
