== Installation Scenario
:noaudio:

In this training we will review the install of the following environment

* Master00 [192.168.0.100] - Our master will host the Web Console, *The API
service* and the *etcd store*. Our master is unschedulable so there is no need to
label it.
** Labels : Region=*NA*, Zone=*NA*, schedulable=`false`
* InfraNode00 [192.168.0.101] - The InfraNode00 is to be used only to host
"Infrastructure" containers such as the *Registry* and our HAproxy *Router*.
** Labels : Region=*Infra*, Zone=*infranode*, schedulable=*true*
* Node00 [192.168.0.200] - Part of the Primary Region, Will co-host all the
user workloads.
** Labels : Region=*Primary*, Zone=*East*, schedulable=*true*
* Node01  [192.168.0.201] - Part of the Primary Region, Will co-host all the
user workloads.
** Labels : Region=*Primary*, Zone=*West*, schedulable=*true*
* oselab  [192.168.0.254] - This server will simulate our corporate DNS server
and NFS backend.

ifdef::showscript[]

=== Transcript
In our lab we will be using the following hosts to simulate a regular
environment.

Our *master* host will be used to host some of the management components of
OpenShift Enterprise, Components such as the Web Console, *The API service* and
the *etcd store*

*Infranode* is a regular node like the others but by changing the labels applied
to the node we are going to dedicate it to be used only for "Infrastructure
containers". This is a design choice and not a mandatory constraint.

the *nodes*, nodes are hosts that are used to run containers (Pods) in the OSE
environment, we label the two nodes to be in the same region but different
zones. This is to simulate a use-case of an environment in a single region and
possibly two cloud availability zones

endif::showscript[]

