== Installation Workflow
:noaudio:

* Prerequisites
** System requirements
** Set up DNS
** Prepare host
* OpenShift Enterprise installation
** Download and run installation utility
* Post-install tasks
** Deploy integrated Docker registry
** Deploy HAProxy router
** Populate OpenShift installation with image streams and templates
** Configure authentication and create project for users
** Set up and configure NFS server for use with _persistent volumes_

ifdef::showscript[]
=== Transcript

Use this workflow to install OpenShift Enterprise. You start by making sure that
 the system prerequisites have been met. These are the basic requirements for a
  viable OpenShift Enterprise environment. They include setting up the DNS
   requirements and preparing the hosts for OpenShift Enterprise deployment.

Next, you use the CLI installation utility to install the OpenShift Enterprise
 software.

Finally, you deploy some containerized infrastructure components such as the
 default router and the integrated Docker registry. You also configure
  authentication and set up an NFS server to serve your persistent volume
   requests.

endif::showscript[]
