== Host Preparation
:noaudio:

.Host Preparation - overview

* To prepare your hosts for OpenShift 3 Enterprise
** *Installing Red Hat Enterprise Linux 7.1* - A base installation of `Red Hat Enterprise Linux (RHEL) 7.1` is required for master or node hosts. See the link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/index.html[Red Hat Enterprise Linux 7.1 Installation Guide]
 for more information.
** *Registering the Hosts with subscription-manager* - You will need to register all the hosts to RHEL7.1 and OpenShift Enterprise repositories.
** *Managing Base Packages* - You will need to install some utility packages (i.e git, net-tools, bind-utils, iptables-services
** *Managing Services* - You will need to disable firewalld and enable iptables-services
** *Install Docker 1.6.x* - Docker version 1.6 or later needs to be installed and storage backend configured for images.
** *Host Password-less communication* - You will ensure that the master hosts can issue remove commands on the nodes without requiring a password.

ifdef::showscript[]

=== Transcript

We will cover some of the basic steps that are required to prepare the hosts.

To prepare the hosts to be used with OpenShift its best to consult the
documentation as it would always have the most up-to-date information.

In case you want to create a scalable environment you will probably create a
image template for the node (depending on your infrastructure provider) and spin
up a new instance/VM in which these steps have already been performed (to save
  time) and then run the installer script to add the new node to the OSE
  environment/cluster.


endif::showscript[]

