== Host Preparation

.Overview

* To prepare your hosts for OpenShift Container Platform 3:
** Install Red Hat Enterprise Linux 7.2
** Register hosts with `subscription-manager`
** Manage base packages:
*** `git`
*** `net-tools`
*** `bind-utils`
*** `iptables-services`
** Manage services:
*** Disable `firewalld`
*** Enable `iptables-services`
**  Install Docker 1.9.1 or later
** Make sure master does not require password for communication

ifdef::showscript[]

=== Transcript

To prepare the hosts to use with OpenShift Container Platform, consult the
 documentation. This ensures you always have the most up-to-date information.

The basic steps for preparing hosts are as follows:

* Perform a base installation of Red Hat Enterprise Linux 7.2 for master and
 node hosts.
* Use `subscription-manager` to register all the hosts to Red Hat Enterprise
 Linux 7.1 and OpenShift Container Platform 3 repositories.
* Install some utility packages, including `git`, `net-tools`, `bind-utils`, and
 `iptables-services`.
* Disable `firewalld` and enable `iptables-services`.
* Install Docker 1.9.1 or later and configure the storage back end for images.
* Make sure that the master hosts can issue remote commands on the nodes
 without requiring a password.

If you want to create a scalable environment, you should create an image
 template for the node--depending on your infrastructure provider--and then, to
  save time, spin up a new instance or VM in which these steps have already been
   performed. You should then run the installer script to add the new node to
    the OpenShift Container Platform environment/cluster.


endif::showscript[]
