== Host Preparation
:noaudio:

.Host Preparation - Password-less communication

* Ensure Installer has password-less access to all Hosts.
* Ansible, which is used to run the installation process, requires a user that has access to all hosts. For running the installer as a non-root user, passwordless sudo rights must also be configured on each destination host.
* For example, you can generate an SSH key on the host where you will invoke the installation process:
+
----
# ssh-keygen
# ssh-copy-id root@node00.example.com
----

NOTE: Do not use a password when generating the key.

* An easy way to distribute your SSH keys is by using a bash loop:

ifdef::showscript[]

=== Transcript
For the installation to be successful the installer will need to be able to run
commands on each on of the members in the OSE environment without a user typing
in the password every time.

Do achieve this we will generate a key and copy it to the root user's id on each
member of the OSE cluster.

endif::showscript[]

