== Host Preparation
:noaudio:

.Host Preparation - Firewalls
OpenShift relies heavily on iptables under the covers. As such, it must be
running, and various ports will need to be opened to allow communication between
 OpenShift components.

* Node-To-Node
- 4789 : required between nodes for SDN communication between pods on separate
 hosts

* Nodes-To-Master
- 53: DNS services within the environment (This is not the DNS for extarnal
  access)
- 4789 : required between nodes for SDN communication between pods on separate
 hosts
- 8443 : Access to the API

* Master-To-Node
- 10250 : endpoint for master communication with nodes
- 4789 : required between nodes for SDN communication between pods on separate
 hosts

* Master to Master
- 4789 : required between nodes for SDN communication between pods on separate
 hosts

ifdef::showscript[]

=== Transcript

The following ports need to be allowed between the different components of the
environment, note that port 4789 is required to be accessiable from any to any
host in the cluster as it is required for the SDN overlay.

The master is running a local DNS Server, do not confuse this server with the
DNS server that holds the wildcard DNS entry. This is a DNS server (SkyDNS) that
is used to resolve local resources, for example, each *service* we define in OSE
will have a dns entry that can be resolved locally.

endif::showscript[]




