== Host Preparation
:noaudio:

.Host Preparation - Firewalls Continued
In case you want to allow external access to your environment, open the
following ports:

* External - Master
- 8443: CLI and IDE plugins communicate via REST to this port. Web console
runs on this port.

* External - Node (or nodes) hosting the *default Router* (HA-Proxy) container
- 80,443: Ports opened and bound to the *Default Router* container to proxy
communication from the external world to the *Pods* (Containters) internally.

ifdef::showscript[]

=== Transcript
If you want to allow users from outside your LAN to access the Web console or
make API calls to OSE, you need to expose the 8443 port of your master to the
desired networks.

The *default router* will be listening on its host's ports 80 and 443 for
incoming requests, to allow external access to your pods you only need to expose
the node hosting the *default router*.

Consider a topology where only the Infrastructure *nodes* are running in a DMZ
and the application hosting *nodes*, master and other supporting infrastructure
are running in a more secure network.

endif::showscript[]



