== Docker Install
:noaudio:

.Configuring Docker Storage

* Docker’s default loopback storage mechanism is not supported for production
use and is only appropriate for proof of concept environments. For production
environments, you must create a thin-pool logical volume and re-configure docker
 to use that volume.
* You can use the "`docker-storage-setup`" script to create a thin-pool device
and configure docker’s storage driver after installing docker but before you
start using it.
* The script reads configuration options from the
"/etc/sysconfig/docker-storage-setup" file.

ifdef::showscript[]

=== Transcript

Docker’s default loopback storage mechanism is not supported for production
use and is only appropriate for proof of concept environments. For production
environments, you must create a thin-pool logical volume and re-configure docker
 to use that volume.

You can use the "`docker-storage-setup`" script to create a thin-pool device
and configure docker’s storage driver after installing docker but before you
start using it.

endif::showscript[]



