
:scrollbar:
:data-uri:
== Installing OpenShift

* The installation utility is provided at https://install.openshift.com. Visit that page for the latest information and to download the portable version if neccessary.

* There are two methods for using the installation utility.
** Method 1: Running the Installation Utility From the Internet
*** Run the installation utility directly from the Internet by running the following command on a host that has SSH access to your intended master and node hosts:
+
----
$ sh <(curl -s https://install.openshift.com/ose/)
---- 

*** Follow the on-screen instructions to install a new OpenShift instance.

** Method 2: Downloading and Running the Installation Utility
*** Download and unpack the installation utility on a host that has SSH access to your intended master and node hosts:
+
----
$ curl -o oo-install-ose.tgz \
    https://install.openshift.com/portable/oo-install-ose.tgz
$ tar -zxf oo-install-ose.tgz
Execute the installation utility to interactively configure one or more hosts:

$ ./oo-install-ose
----

*** Follow the on-screen instructions to install a new OpenShift instance.

* The installer will ask you for Internal and Public IPs of your Master's and Nodes and will configure then accordingly. 

ifdef::showscript[]

=== Transcript

endif::showscript[]




