== Docker Installation
:noaudio:

.Storage Options: Example

* Use unpartitioned block device to create new volume group and thin-pool:
** Example: Use `/dev/vdc device` to create `docker-vg`:
+
----
# cat /etc/sysconfig/docker-storage-setup
DEVS=/dev/vdc
VG=docker-vg
SETUP_LVM_THIN_POOL=yes
# docker-storage-setup
----

* Verify configuration:
** Should have `dm.thinpooldev` value in
`/etc/sysconfig/docker-storage` and `docker-pool` device
+
----
# lvs
LV                  VG        Attr       LSize  Pool Origin Data%  Meta% Move
docker-pool         docker-vg twi-a-tz-- 48.95g             0.00   0.44

# cat /etc/sysconfig/docker-storage
DOCKER_STORAGE_OPTIONS=--storage-opt dm.fs=xfs --storage-opt
dm.thinpooldev=/dev/mapper/docker--vg-docker--pool

----

* Restart `Docker` daemon

ifdef::showscript[]

=== Transcript

In this example, you use the `/dev/vdc` unpartitioned block device to create the `docker-vg` volume group that the `Docker` daemon will use.

To verify that the volume is created and configured, use the `lvs` command and view the `/etc/sysconfig/docker-storage` file. You should have a `dm.thinpooldev` value in the `/etc/sysconfig/docker-storage` file and a `docker-pool` device.

After you verify the setup, restart the `Docker` daemon.

endif::showscript[]
