== OpenShift Enterprise Installation
:noaudio:

* Install OpenShift `utils` package that includes installer:
+
----
# yum -y install atomic-openshift-utils
----

* Run following on host that has SSH access to intended master and nodes:
+
----
$ atomic-openshift-installer install
----

* Follow onscreen instructions to install OpenShift Enterprise
** Installer asks for hostnames or IPs of masters and nodes and configures them
 accordingly
** Configuration file with all information provided is saved in `~/.config/openshift/installer.cfg.yml`
*** Can use this as _answer file_

ifdef::showscript[]

=== Transcript

To install OpenShift
 Enterprise 3, install the OpenShift `utils` package that includes the installer,
  and run the installer CLI utility on a host that has SSH access to your
   intended master and nodes.

The installer asks for the hostnames or IPs of the masters and nodes and configures them
 accordingly.

A configuration file with all the information provided is saved in  `~/.config/openshift/installer.cfg.yml`.
You can use this as an _answer file_
  for future installations.


endif::showscript[]
