== OpenShift Enterprise Installation
:noaudio:

* Install the OpenShift Utils package that includes the installer
+
----
# yum -y install atomic-openshift-utils
----

* Run the following on host that has SSH access to intended master and nodes:
+
----
$ atomic-openshift-installer install
----

* Follow onscreen instructions to install OpenShift Enterprise
** Installer asks for hostnames or IPs of masters and nodes and configures them
 accordingly.
** A configuration file with all the information provided would be saved in:
 `~/.config/openshift/installer.cfg.yml` - This can be used as an "Answer file".

ifdef::showscript[]

=== Transcript
The latest installer is available from the link shown here. To install OpenShift
 Enterprise 3, Install the OpenShift Utils package that includes the installer,
  and run the installer CLI utility on a host that has SSH access to your
   intended master and nodes.

The installer asks for hostnames or IPs of masters and nodes and configures them
 accordingly.

A configuration file with all the information provided would be saved in:
  `~/.config/openshift/installer.cfg.yml`, this can be used as an "Answer file"
  for future installs.


endif::showscript[]
