== Deploying the Registry
:noaudio:

.NFS Storage for the Registry

* The registry stores Docker images and metadata. If you simply deploy a pod
with the registry, it uses an ephemeral volume that is destroyed if the pod
exits. Any images anyone has built or pushed into the registry would disappear.
* For production use, you should use persistent storage using PersistentVolume
and PersistentVolumeClaim objects for storage for the registry.
* For non-production use, other options exist to provide persistent storage for
the registry, like the --mount-host option.
+
----
$ oadm registry --config=admin.kubeconfig \
    --credentials=openshift-registry.kubeconfig \
	   --selector='region=infra' \
     --mount-host host:/export/dirname
----
+
** The --mount-host option mounts a directory from the node on which the
registry container lives. If you scale up the docker-registry deployment
configuration, it is possible that your registry pods and containers will
run on different nodes.
+
**
ifdef::showscript[]

=== Transcript

endif::showscript[]

