
:scrollbar:
:data-uri:
== Populating OpenShift
* You can populate your OpenShift installation with a useful set of Red Hat-provided *image streams* and *templates* to make it easy for developers to create new applications.
** Template: A template describes a set of resources intended to be used together that can be customized and processed to produce a configuration. Each template defines a list of parameters that can be modified for consumption by containers.
** Image Streams: An image stream is similar to a Docker image repository in that it contains one or more Docker images identified by tags. An image stream presents a single virtual view of related images.

* The core set of image streams provide images that can be used to build *Node.js*, *Perl*, *PHP*, *Python*, and *Ruby* applications. It also defines images for *MongoDB*, *MySQL*, and *PostgreSQL* to support data storage.
** To create the core set of image streams, that use the Red Hat Enterprise Linux (RHEL) 7 based images:
+
----
oc create -f \
    examples/image-streams/image-streams-rhel7.json \
    -n openshift
----
 

ifdef::showscript[]

=== Transcript

endif::showscript[]

