== Registry Deployment
:noaudio:

.Registry Container

* OpenShift Enterprise: 
** Builds Docker images from source code
** Deploys them
** Manages lifecycle
* To enable this, deploy Docker registry in OpenShift Enterprise environment
* OpenShift Enterprise runs registry in pod on node, just like any other workload
* Deploying registry creates _service_ and _deployment configuration_
** Both called `docker-registry`
* After deployment, pod created with name similar to `docker-registry-1-cpty9`

* To control where registry is deployed, use `--selector` flag to specify desired target  

ifdef::showscript[]

=== Transcript

OpenShift Enterprise can build Docker images from your source code, deploy them, and manage their lifecycle. To enable this, you deploy an internal, integrated Docker registry in your OpenShift Enterprise environment.

OpenShift runs the registry in a pod on a node, just like any other workload.

Deploying the registry creates a _service_ and a _deployment configuration_, both called `docker-registry`.

After successful deployment, a pod is created with a name similar to `docker-registry-1-cpty9`.

To control where your registry is deployed, you use the `--selector` flag to specify your target by picking the labels you want to match.

endif::showscript[]

