== Registry Deployment
:noaudio:

.Deploying Registry

* Environment includes `infra` region and dedicated
`infranode00` host
** Good practice for highly scalable environment
** Use better-performing servers for nodes or place them in DMZ for external
 access only

* To deploy registry anywhere in environment:
+
----
$ oadm registry --config=admin.kubeconfig \
    --credentials=openshift-registry.kubeconfig
----

* To ensure `registry` pod is hosted in `infra` region only:
+
----
$ oadm registry --config=admin.kubeconfig \
    --credentials=openshift-registry.kubeconfig \
	   --selector='region=infra'
----

ifdef::showscript[]

=== Transcript

You can deploy the _Registry container_ anywhere in the OpenShift Environment.
 In your environment, you created a region called `infra` and dedicated the
  `infranode00` host for it.

This is a good practice for a highly scalable environment. You might want to use
 better-performing servers for these nodes or place them in the DMZ so only the
  external network can access them.

To deploy a registry anywhere in the environment, run the first command shown
 here.

To ensure that the `registry` pod is hosted only in the `infra` region, run the
 second command shown here with the `--selector` option added.

endif::showscript[]
