== Registry Deployment
:noaudio:

.NFS Storage for the Registry

* Registry stores Docker images, metadata
* If you deploy a pod with registry:
** Uses ephemeral volume
** Destroyed if pod exits
*** Images built or pushed into registry disappear
* For production:
** Use persistent storage
** Use `PersistentVolume` and `PersistentVolumeClaim` objects for storage for
 registry
* For non-production:
** Other options exist
** Example: `--mount-host`:
+
----
$ oadm registry --config=admin.kubeconfig \
    --credentials=openshift-registry.kubeconfig \
	   --selector='region=infra' \
     --mount-host host:/export/dirname
----
+
*** Mounts directory from node on which registry container lives
*** If you scale up `docker-registry` deployment configuration, registry pods
 and containers might run on different nodes

ifdef::showscript[]

=== Transcript

The registry stores Docker images and metadata. If you simply deploy a pod with
 the registry, it uses an ephemeral volume that is destroyed if the pod exits.
  Any images built or pushed into that registry will disappear.

For production use, you should build persistent storage using `PersistentVolume`
 and `PersistentVolumeClaim` objects for storage for the registry.

For non-production use, other options exist to provide persistent storage, such
 as the `--mount-host` option.

The `--mount-host` option mounts a directory from the node on which the registry
 container lives. If you scale up the `docker-registry` deployment
  configuration, it is possible that your registry pods and containers will run
   on different nodes.

endif::showscript[]
