== Default HAProxy Router Deployment
:noaudio:

* `Default Router` (aka `Default HA-Proxy Router`, other names):
** Modified deployment of HAProxy
** Entry point for traffic destined for services in OpenShift Enterprise
 installation
* HAProxy-based router implementation provided as default template router
 plug-in
** Uses `openshift3/ose-haproxy-router` image to run HAProxy instance alongside
 and router plug-in
** Supports HTTP(S) traffic and TLS-enabled traffic via SNI only
** Hosted inside OpenShift Enterprise
** Essentially a proxy

* Default router’s pod listens on host network interface on port 80 and 443
** Default router's container listens on external/public ports
** Router proxies external requests for route names to IPs of actual pods
 identified by service associated with route

ifdef::showscript[]

=== Transcript

The `Default Router`, also known as the `Default HA-Proxy Router` and many other
 similar names, is a modified deployment of HAProxy. It serves as the entry
  point for all traffic destined for services in your OpenShift Enterprise
   installation.

An HAProxy-based router implementation is provided as the default template
 router plug-in. It uses the `openshift3/ose-haproxy-router` image to run an
  HAProxy instance alongside and a router plug-in. The router currently supports
   HTTP(S) traffic and TLS-enabled traffic via SNI only. Like the registry and
    any other workload, it is hosted inside OpenShift Enterprise.

While it is called a _router_, it is essentially a _proxy_.

The default router’s pod listens on its host's network interface on ports 80 and
 443. Unlike most containers, which listen only on private IPs, the default
  router's container listens on external/public ports. The router proxies
   external requests for route names to the IPs of actual pods identified by the
    service associated with the route.

endif::showscript[]
