== OpenShift Enterprise Population


* Can populate OpenShift Enterprise installation with Red Hat-provided _image streams_ and _templates_
** Make it easy to create new applications
* *Template*: Set of resources you can customize and process to produce configuration
** Defines list of parameters you can modify for consumption by containers
* *Image Stream*: Similar to Docker image repository
** Contains Docker images identified by tags
** Presents single virtual view of related images

ifdef::showscript[]

=== Transcript
You can populate your OpenShift Enterprise installation with a useful set of Red Hat-provided _image streams_ and _templates_. These make it easy for developers to create new applications. The installer automatically adds image streams and common templates.

A _template_ describes a set of resources intended to be used together that you can customize and process to produce a configuration. Each template defines a list of parameters that you can modify for consumption by a container. This is somewhat similar to a OpenShift Enterprise 2.0 _quickstart_.

An _image stream_ is similar to a Docker image repository in that it contains one or more Docker images identified by tags. An image stream presents a single virtual view of related images.

endif::showscript[]

