== Populating OpenShift
:noaudio:

* The xPaaS Middleware image streams provide images for *JBoss EAP*,
*JBoss EWS*, and *JBoss A-MQ*. They can be used to build applications for those
platforms.
** To create the Image Streams for xPaaS Middleware Images:
+
----
$ oc create -f \
    examples/xpaas-streams/jboss-image-streams.json
    -n openshift
----
* The database service templates make it easy to run a database instance which can be utilized by other components.
* For each database (*MongoDB*, *MySQL*, and *PostgreSQL*), two templates are provided.
** To create the core set of database templates:
+
----
$ oc create -f \
    examples/db-templates -n openshift
----

** After creating the templates, users are able to easily instantiate the various templates, giving them quick access to a database deployment.


ifdef::showscript[]

=== Transcript
Red Hat provides xPaas Middleware image streams for  *JBoss EAP*, *JBoss EWS*,
and *JBoss A-MQ*.

you can also deploy database Templates that make it easy to run a database
instance which can be utilized by other components.

endif::showscript[]




