== OpenShift Container Platform Population

.Image Streams

* xPaaS middleware image streams provide images for:
** Red Hat JBoss Enterprise Application Platform
** Red Hat JBoss Web Server
** Red Hat JBoss A-MQ

* Can use images to build applications for those platforms

* To create or delete core set of image streams that use Red Hat Enterprise
 Linux 7-based images:
+
----
oc create|delete -f \
    examples/image-streams/image-streams-rhel7.json \
    -n openshift
----

** To create image streams for xPaaS middleware images:
+
----
$ oc create|delete -f \
    examples/xpaas-streams/jboss-image-streams.json
    -n openshift
----

ifdef::showscript[]

=== Transcript

Red Hat provides xPaaS middleware image streams for Red Hat JBoss Enterprise
 Application Platform, Red Hat JBoss Web Server, and Red Hat JBoss A-MQ.

You can use the image streams to build application for these platforms.

Use the code shown here to create or delete the core set, xPaaS and JBoss image
 streams.



endif::showscript[]
