== Persistent Storage Using NFS

* To create a persistent volume that can be claimed by a pod, you must
 create a `PersistentVolume` object in pod's `Project`
* After `PersistentVolume` is created, a `PersistentVolumeClaim` must be
 created to ensure other pods and projects do not try to use `PersistentVolume`

.Persistent Volume Object Definition
[source,yaml]
----
{
  "apiVersion": "v1",
  "kind": "PersistentVolume",
  "metadata": {
    "name": "pv0001"
  },
  "spec": {
    "capacity": {
        "storage": "5Gi"
    },
    "accessModes": [ "ReadWriteOnce" ],
    "nfs": {
        "path": "/tmp",
        "server": "172.17.0.2"
    },
    "persistentVolumeReclaimPolicy": "Recycle"
  }
}
----

ifdef::showscript[]

=== Transcript

To create a persistent volume that can be claimed by a pod, you must create
 a `PersistentVolume` object in the pod's `Project`.
After a `PersistentVolume` is created, a `PersistentVolumeClaim` must also be
 created to ensure that other pods and projects do not try to use the
  `PersistentVolume`.

Here is the definition of the `Persistent Volume` object.

You must specify the storage capacity, access mode, and details of your NFS host.

endif::showscript[]
