:scrollbar:
:data-uri:
:icons: images/icons
:toc2:		

	
== Regions and Zones
:numbered:	

* In the previous lab we have added 2 more nodes to our OpenShift environment. 

* In this lab we will label these nodes into regions and zones and configure the OpenShift Scheduler.

** Our scheduler would be configured to filter OUT nodes that are NOT in the pod's Region label.

** Our scheduler would be configured to prioritize nodes that are NOT in our pod's Zone Label

=== Configure The Scheduler

. If not already connected, connect to your administration host *oselab* (your private key location may vary):
+
----

yourdesktop$ ssh -i ~/.ssh/id_rsa your-opentlc-login@oselab-*GUID*.oslab.opentlc.com

----

. Become the `root` user:
+
----

-bash-4.2$ sudo -i

----

. SSH to the master host:
+
----

[root@oselab-GUID ~]# ssh 192.168.0.100

----
+
[NOTE]
If prompted for a password use *r3dh4t1!*
+
----

root@192.168.0.100's password: ******** (r3dh4t1!) 

----

. Create a Scheduler configuration file on the master host:
+
----

[root@master00-GUID ~]# cat << EOF > /etc/openshift/scheduler.json
{
  "predicates" : [
    {"name" : "PodFitsResources"},
    {"name" : "PodFitsPorts"},
    {"name" : "NoDiskConflict"},
    {"name" : "Region", "argument" : {"serviceAffinity" : { "labels" : ["region"]}}}
  ],"priorities" : [
    {"name" : "LeastRequestedPriority", "weight" : 1},
    {"name" : "ServiceSpreadingPriority", "weight" : 1},
    {"name" : "Zone", "weight" : 2, "argument" : {"serviceAntiAffinity" : { "label" : "zone" }}}
  ]
}

EOF

----

. Configure OpenShift-Master to use our scheduler configuration file
.. On the master host change the /etc/openshift.master.yaml file "schedulerConfigFile:" line to point to our configuration file */etc/openshift/scheduler.json*:
+
----

[root@master00-GUID ~]# vi /etc/openshift/master.yaml
#or
[root@master00-GUID ~]# sed -i "s/schedulerConfigFile:.*/schedulerConfigFile: \"\/etc\/openshift\/scheduler.json\"/g" /etc/openshift/master.yaml 


----

=== Label the Nodes

* We want to label our nodes in the following manner
** master00 -- "region":"infra", "zone":"NA"
** node00 -- "region":"primary", "zone":"east"
** node01 -- "region":"primary", "zone":"west"

:numbered:

. On the master host use the *osc get node* command to generate a .json file for us to edit:
+
----

[root@master00-GUID ~]# osc get node -o json > ~/nodes.json

----

. To be able to use *nodes.json* to update our configuration we need to remove the *"resourceVersion"* line :
+
----

[root@master00-GUID ~]# sed -i '/"resourceVersion"/d' ~/nodes.json 

----

. Enter your favorite editort to edit *nodes.json* for the next few steps:
+
----

vi ~/nodes.json 

----

. To set the master's labels, search for the metadata section with "name": "master00-GUID.oslab.opentlc.com" and add the following before that "name" setting (ignore the blank metadata section on the 4th line):
+
----

                "labels" : {
                  "region" : "infra",
                  "zone" : "NA"
                },

----
+
[NOTE]
Formatting means everything in JSON.  You must make sure the format is 100% correct.

.. The result should look something like this: 
+
----
{
    "kind": "List",
    "apiVersion": "v1beta3",
    "items": [
        {
            "kind": "Node",
            "apiVersion": "v1beta3",
            "metadata": {
                "labels" : {
                  "region" : "infra",
                  "zone" : "NA"
                },
                "name": "master00-GUID.oslab.opentlc.com",
...

----

. Add the following to the node00 section:
+
----

                "labels" : {
                  "region" : "primary",
                  "zone" : "east"
                },

----

. Add the following to node01 section:
+
----

                "labels" : {
                  "region" : "primary",
                  "zone" : "west"
                },

----

. Write out the file and exit the editor.

:numbered!:

=== Apply the update to OpenShift
:numbered:
. From the master host, update the nodes configuration with the *osc update* command:
+
----

[root@master00-GUID ~]# osc update node -f ~/nodes.json

----


. In this version of the software (Beta3) we need to restart the `openshift-node` and `openshift-master` services for changes to take effect.  Run all the commands from the master host:
+
----

[root@master00-GUID ~]# GUID=`hostname|cut -f2 -d-|cut -f1 -d.`
[root@master00-GUID ~]# systemctl restart openshift-master
[root@master00-GUID ~]# systemctl restart openshift-node
[root@master00-GUID ~]# ssh node00-$GUID.oslab.opentlc.com "systemctl restart openshift-node"
[root@master00-GUID ~]# ssh node01-$GUID.oslab.opentlc.com "systemctl restart openshift-node"

----

. On the master host use *osc get nodes* command to review the changes that were made:
+
----

[root@master00-GUID ~]# osc get nodes

NAME                              LABELS        STATUS
master00-GUID.oslab.opentlc.com   Schedulable   region=infra,zone=NA       Ready
node00-GUID.oslab.opentlc.com     Schedulable   region=primary,zone=east   Ready
node01-GUID.oslab.opentlc.com     Schedulable   region=primary,zone=west   Ready

----


:numbered!:
