:scrollbar:
:data-uri:
:icons: images/icons
:toc2:		

	
== Add Nodes to the Environment
:numbered:	

In the previous lab we have installed OpenShift Enterprise 3.0 On a single host. 
In this lab we will learn how to add nodes to the OpenShift 3.0 environment. 

=== Configure SSH connectivity with the nodes 

. If not already connected, connect to your administration host *oselab* (your private key location may vary):
+
----

yourdesktop$ ssh -i ~/.ssh/id_rsa your-opentlc-login@oselab-*GUID*.oslab.opentlc.com

----

. Become the `root` user:
+
----

-bash-4.2$ sudo -i

----

. SSH to the master host:
+
----

[root@oselab-5485 ~]# ssh 192.168.0.100

----
+
[NOTE]
If prompted for a password use *r3dh4t1!*
+
----

root@192.168.0.100's password: ******** (r3dh4t1!) 

----

. From the master host use ssh-copy-id to copy the public SSH key to each of the nodes:
+
----

[root@master00-GUID ~]# GUID=`hostname|cut -f2 -d-|cut -f1 -d.`
[root@master00-GUID ~]# ssh-copy-id node00-$GUID.oslab.opentlc.com
[root@master00-GUID ~]# ssh-copy-id node01-$GUID.oslab.opentlc.com

----
+
[NOTE]
If prompted for a password use *r3dh4t1!*
+
----

root@192.168.0.100's password: ******** (r3dh4t1!) 

----

. From the master host test passwordless SSH connections to the nodes:
+
----

[root@master00-GUID ~]# ssh node00-$GUID.oslab.opentlc.com "hostname -f ; date"
[root@master00-GUID ~]# ssh node01-$GUID.oslab.opentlc.com "hostname -f ; date"

----

:numbered!:

=== Reconfigure and Re-run the Ansible Playbook to Add Nodes

. Review the Ansible host configuration file on the master host and note there is only one host under [nodes]:
+
----

[root@master00-GUID ~]# cat /etc/ansible/hosts
...
[nodes]
master00-GUID.oslab.opentlc.com

---- 

. Edit the Ansible host configuration file on the master host so that it includes the two nodes under the [nodes] section: 
+
----

[root@master00-GUID ~]# echo "node00-$GUID.oslab.opentlc.com" >> /etc/ansible/hosts
[root@master00-GUID ~]# echo "node01-$GUID.oslab.opentlc.com" >> /etc/ansible/hosts

----

. Look at the Ansible host configuration file [nodes] section on the master host again:
+
----

[root@master00-GUID ~]# cat /etc/ansible/hosts

...
[nodes]
master00-GUID.oslab.opentlc.com

node00-GUID.oslab.opentlc.com
node01-GUID.oslab.opentlc.com
...

----

. Run the Ansible installer on the master host again using the `ansible-playbook` command:
+
----

[root@master00-GUID ~]# ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml

----
+
[NOTE]
This will take a while to complete.  This is a good time for a break.

. After the installer is complete, check the status of your nodes using the *osc get nodes* command on the master host:
+
----

[root@master00-GUID ~]# osc get nodes
NAME                      LABELS        STATUS
ose3-master.example.com   Schedulable   <none>    Ready
ose3-node1.example.com    Schedulable   <none>    Ready
ose3-node2.example.com    Schedulable   <none>    Ready

---- 

*You have succesfully added nodes to your environment.*
