:scrollbar:
:data-uri:
:icons: images/icons
:toc2:		

	
== Deploy OpenShift Enterprise
:numbered:	

In this lab we will Deploy OpenShift Enterprise on a single host (in later labs we will add more nodes).

* Configure Repositories

* Configure Network Settings

* Install Docker on our host 

* Configure SSH Keys

* Install Ansible Installer 

* Configure and Install OpenShift Enterprise

* Configure a DNS on our *oselab* server to serve our OpenShift environment.

* Test deployment.

=== Beta Course Warning
Take note that all of the steps in the lab may change when OpenShift 3.0 goes GA.  This course was built on a beta build.

=== Configure the Repositories
. If not already connected, connect to your administration host *oselab* (your private key location may vary):
+
----

yourdesktop$ ssh -i ~/.ssh/id_rsa your-opentlc-login@oselab-*GUID*.oslab.opentlc.com

----

. Become the `root` user:
+
----

-bash-4.2$ sudo -i

----

. SSH to the master host:
+
----

[root@oselab-GUID ~]# ssh 192.168.0.100

----
+
[NOTE]
If prompted for a password use *r3dh4t1!*
+
----

root@192.168.0.100's password: ******** (r3dh4t1!) 

----

. On the master host set up */etc/yum.repos.d/open.repo* with the following repositories (We are using local repositories in our lab environment, normally you would use `subscription-manager`):
.. Red Hat Enterprise Linux 7
.. Red Hat Enterprise Linux 7 Common
.. Red Hat Enterprise Linux 7 Extras
.. Red Hat Enterprise Linux 7 Optional
+
----
[root@master00-GUID ~]# cat << EOF > /etc/yum.repos.d/open.repo
[rhel-x86_64-server-7]
name=Red Hat Enterprise Linux 7
baseurl=http://www.opentlc.com/repos/rhel-x86_64-server-7
enabled=1
gpgcheck=0

[rhel-x86_64-server-rh-common-7]
name=Red Hat Enterprise Linux 7 Common
baseurl=http://www.opentlc.com/repos/rhel-x86_64-server-rh-common-7
enabled=1
gpgcheck=0

[rhel-x86_64-server-extras-7]
name=Red Hat Enterprise Linux 7 Extras
baseurl=http://www.opentlc.com/repos/rhel-x86_64-server-extras-7
enabled=1
gpgcheck=0

[rhel-x86_64-server-optional-7]
name=Red Hat Enterprise Linux 7 Optional
baseurl=http://www.opentlc.com/repos/rhel-x86_64-server-optional-7
enabled=1
gpgcheck=0

EOF

----

. Add the OpenShift Beta3 repository to the master host:
+
----

[root@master00-GUID ~]# cat << EOF >> /etc/yum.repos.d/open.repo
[ose3]
name=Red Hat Enterprise Linux 7 OSE 3
baseurl=http://www.opentlc.com/repos/ose3_beta4
enabled=1
gpgcheck=0

EOF

----

. List the available repositories on the master host:
+
-----

[root@master00-GUID ~]# yum repolist 

-----
+
You should see the following:
+
----

repo id                           repo name                               status
ose3                              Red Hat Enterprise Linux 7 OSE 3           16
rhel-x86_64-server-7              Red Hat Enterprise Linux 7              4,387
rhel-x86_64-server-extras-7       Red Hat Enterprise Linux 7 Extras          19
rhel-x86_64-server-optional-7     Red Hat Enterprise Linux 7 Optional     4,087
rhel-x86_64-server-rh-common-7    Red Hat Enterprise Linux 7 Common          19

----

=== Verify Network Configuration:

. On the Master host, remove the NetworkManager package (if installed):
+
----

[root@master00-GUID ~]# yum -y remove NetworkManager*

----

. Verify the hostname for the master host:
+
----

[root@master00-GUID ~]# hostname -f 

----
+
.You should see the following:
----

master00-GUID.oslab.opentlc.com

----

. Take note of the internal IP address:
+
----

[root@master00-GUID ~]# ip address show dev eth0|grep "inet "|awk '{print $2}'|cut -f1 -d/

----

. Make sure the internal DNS entry matches the internal IP address:
+
----

[root@master00-GUID ~]# host `hostname -f` 

----

. Take note of the external IP address:
+
----

[root@master00-GUID ~]# curl http://www.opentlc.com/getip

----

. Make sure the external DNS entry matches the external IP address:
+
----

[root@master00-GUID ~]# host `hostname -f` 8.8.8.8

----

=== Install Docker 

. Install *Docker* on the master host
+ 
----

[root@master00-GUID ~]# yum -y install docker

----

. Run `docker-storage-setup` on the master host to create logical volumes for *Docker*:
+
----

[root@master00-GUID ~]# docker-storage-setup

----
+
You should see the following:
+
----

  Rounding up size to full physical extent 32.00 MiB
  Logical volume "docker-poolmeta" created.
  Logical volume "docker-pool" created.
  WARNING: Converting logical volume rhel_host2cc260760b15/docker-pool and rhel_host2cc260760b15/docker-poolmeta to pool's data and metadata volumes.
  THIS WILL DESTROY CONTENT OF LOGICAL VOLUME (filesystem etc.)
  Converted rhel_host2cc260760b15/docker-pool to thin pool.
  Logical volume "docker-pool" changed.
  
----
+
[NOTE]
Be careful with `docker-storage-setup` as it will, by default, find any unused extents in the volume group that contains your root filesystem to create the pool.  You can also specify a specific volume group or block device.  This can be a destructive process to the specified VG or block device!  Consult the OpenShift documentation for more information.

. On the master host examine the newly created logical volume `docker-pool`:
+
----

[root@master00-GUID ~]# lvs /dev/rhel_host2cc260760b15/docker-pool

----
+
You should see the following:
+
----

  LV          VG                    Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker-pool rhel_host2cc260760b15 twi-a-t--- 5.98g             0.00   0.11

----

. On the master host, examine the docker storage configuration:
+
----

[root@master00-GUIDc ~]#  cat /etc/sysconfig/docker-storage

----
+
You should see the following:
+
----

DOCKER_STORAGE_OPTIONS=-s devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/rhel_host2cc260760b15-docker--pool

----

. Configure the *Docker* registry on the master host:
+
----

[root@master00-GUID ~]# sed -i "s/OPTIONS.*/OPTIONS='--selinux-enabled --insecure-registry 0.0.0.0\/0'/" \
    /etc/sysconfig/docker

----

. Enable, start, and get status for the *Docker* service on the master host:
+
----

[root@master00-GUID ~]# systemctl enable docker
[root@master00-GUID ~]# systemctl start docker
[root@master00-GUID ~]# systemctl status docker

----
+
You should see the following:
+
----

docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: active (running) since Wed 2015-06-10 15:31:11 EDT; 1s ago
...OUTPUT OMMITTED...

----
+
[NOTE]
Make sure the status shows *enabled* and *active (running)*.

. In order to save time later, we will "pull" some docker images to the master host. (We already downloaded these locally to your host so it will go faster) [master host shell prompt not shown below]:
+
----

docker pull registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.4.3.2
docker pull registry.access.redhat.com/openshift3_beta/ose-deployer:v0.4.3.2
docker pull registry.access.redhat.com/openshift3_beta/ose-sti-builder:v0.4.3.2
docker pull registry.access.redhat.com/openshift3_beta/ose-docker-builder:v0.4.3.2
docker pull registry.access.redhat.com/openshift3_beta/ose-pod:v0.4.3.2
docker pull registry.access.redhat.com/openshift3_beta/ose-docker-registry:v0.4.3.2
docker pull registry.access.redhat.com/openshift3_beta/sti-basicauthurl:latest
docker pull registry.access.redhat.com/openshift3_beta/ruby-20-rhel7
docker pull registry.access.redhat.com/openshift3_beta/mysql-55-rhel7
docker pull openshift/hello-openshift

----

. Restart the *Docker* service on master host:
+
----

[root@master00-GUID ~]# systemctl restart docker

----

=== Configure SSH Keys:

. On the master host, create keys for the root user.
+
----

[root@master00-GUID ~]# ssh-keygen -f /root/.ssh/id_rsa -N '' 

----

. Add ssh key to *authorized_keys* of all the hosts in the environment (currently only our master host):
+
----

[root@master00-GUID ~]# cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys 
#or
[root@master00-GUID ~]# ssh-copy-id -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pub 127.0.0.1

----

. Configure */etc/ssh/ssh_conf* to disable *StrictHostKeyChecking* on the master host (only for development, testing, or demos!):
+
----

[root@master00-GUID ~]# echo StrictHostKeyChecking no >> /etc/ssh/ssh_config

----

. From the master host test the new SSH key by connecting to itself over the loopback interface without a keyboard prompt:
+
----

[root@master00-GUID ~]# ssh 127.0.0.1
...[output ommitted]...
[root@master00-GUID ~]# exit

----

=== Install Ansible Installer 

[NOTE]
The steps in this section will drastically change when the product goes GA.

. Add the *EPEL* repository to the master host and disable it:
+
----

[root@master00-GUID ~]# yum -y install http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
[root@master00-GUID ~]# sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo

----

. Install Ansible on master host:
+
----

[root@master00-GUID ~]# yum -y --enablerepo=epel install ansible

----

=== Configure and Install OpenShift Enterprise 3.0

. Download the Ansible "playbook" to the master host in root's home directory:
+
---- 

[root@master00-GUID ~]# cd;git clone https://github.com/detiber/openshift-ansible.git -b v3-beta3 

----

. Configure */etc/ansible/hosts* on the master host:
+
----

[root@master00-GUID ~]# export GUID=`hostname|cut -f2 -d-|cut -f1 -d.`
[root@master00-GUID ~]# cat << EOF >> /etc/ansible/hosts
[OSEv3:children]
masters
nodes
[OSEv3:vars]
deployment_type=enterprise
ansible_ssh_user=root

# host group for masters
[masters]
master00-$GUID.oslab.opentlc.com

# host group for nodes
[nodes]
master00-$GUID.oslab.opentlc.com

EOF

----

  
. Run the Ansible installer on the master host and then restart the *openshift-master* service:
+
---- 

[root@master00-GUID ~]# ansible-playbook -vvv /root/openshift-ansible/playbooks/byo/config.yml
[root@master00-GUID ~]# systemctl start openshift-master

----
+
[NOTE]
Running the Ansible installer will take a few minutes to run.  This is a good time for a break.

=== Configure Wildcard DNS to Service the OpenShift Environment.

. If not already connected, connect to your administration host *oselab* (your private key location may vary):
+
----

yourdesktop$ ssh -i ~/.ssh/id_rsa your-opentlc-login@oselab-*GUID*.oslab.opentlc.com

----

. Become the `root` user:
+
----

-bash-4.2$ sudo -i

----

. Install *BIND* on the administration host (*oselab*) then enable but stop the service:
+
----

[root@oselab-GUID ~]# yum -y install bind bind-utils
[root@oselab-GUID ~]# systemctl enable named
[root@oselab-GUID ~]# systemctl stop named

----

. On the admistration host collect and define the environment's information:
+
----

[root@oselab-GUID ~]# guid=`hostname|cut -f2 -d-|cut -f1 -d.`
[root@oselab-GUID ~]# masterIP=`host master00-$guid.oslab.opentlc.com ipa.opentlc.com | grep $guid | awk '{ print $4 }'`
[root@oselab-GUID ~]# domain="cloudapps-$guid.oslab.opentlc.com"

----

. On the administration host create the zone file with the wildcard DNS:
+
----

[root@oselab-GUID ~]# mkdir /var/named/zones
[root@oselab-GUID ~]# echo "\$ORIGIN  .
\$TTL 1  ;  1 seconds (for testing only)
${domain} IN SOA master.${domain}.  root.${domain}.  (
  2011112904  ;  serial
  60  ;  refresh (1 minute)
  15  ;  retry (15 seconds)
  1800  ;  expire (30 minutes)
  10  ; minimum (10 seconds)
)
  NS master.${domain}.
\$ORIGIN ${domain}.
test A ${masterIP}
* A ${masterIP}"  >  /var/named/zones/${domain}.db

----

. Configure named.conf on the administration host:
+
----

[root@oselab-GUID ~]# echo "// named.conf
options {
  listen-on port 53 { any; };
  directory \"/var/named\";
  dump-file \"/var/named/data/cache_dump.db\";
  statistics-file \"/var/named/data/named_stats.txt\";
  memstatistics-file \"/var/named/data/named_mem_stats.txt\";
  allow-query { any; };
  recursion yes;
  /* Path to ISC DLV key */
  bindkeys-file \"/etc/named.iscdlv.key\";
};
logging {
  channel default_debug {
    file \"data/named.run\";
    severity dynamic;
  }; 
};
zone \"${domain}\" IN {
  type master;
  file \"zones/${domain}.db\";
  allow-update { key ${domain} ; } ;
};" > /etc/named.conf

----

. On the administration host correct file permissions and start the DNS server:
+
----

[root@oselab-GUID ~]# chgrp named -R /var/named
[root@oselab-GUID ~]# chown named -R /var/named/zones
[root@oselab-GUID ~]# restorecon -R /var/named
[root@oselab-GUID ~]# chown root:named /etc/named.conf
[root@oselab-GUID ~]# restorecon /etc/named.conf
[root@oselab-GUID ~]# systemctl start named

----

. Configure FirewallD on the administation host to allow inbound DNS queries:
+
----

[root@oselab-GUID bin]# firewall-cmd --zone=public --add-service=dns --permanent
[root@oselab-GUID bin]# firewall-cmd --reload

----

=== Verify DNS configuration:

.. First try locally on the administration host
.. Then you could try from your laptop/desktop, this might take a few minutes to be updated.  Be sure to replace GUID with the correct GUID.
+
----

[root@oselab-GUID ~]# dig @127.0.0.1 test.cloudapps-$guid.oslab.opentlc.com
[root@oselab-GUID ~]# dig @8.8.8.8 test.cloudapps-$guid.oslab.opentlc.com

yourhost$ nslookup test.cloudapps-GUID.oslab.opentlc.com

----
