:scrollbar:
:data-uri:
:icons: images/icons
:toc2:		

== Deploy The "Router" Container
:numbered:	

* In this lab we will Deploy the *Router* container.

* We will configure the *Router* to be deployed only in the "Infra" region.

=== Connect to Lab

. If not already connected, connect to your administration host:
+
----

yourdesktop$ ssh -i ~/.ssh/id_rsa your-opentlc-login@oselab-GUID.oslab.opentlc.com

----

. SSH to the master host:
+
----

[root@oselab-GUID ~]# ssh root@master00-GUID.oslab.opentlc.com

----
+
[NOTE]
If prompted for a password use *r3dh4t1!*
+
----

root@master00-GUID.oslab.opentlc.com's password: ******** (r3dh4t1!) 

----



. Run the *osadm router* command to create the *Router* container:
+
----

[root@master00-GUID ~]# osadm registry --create \
   --credentials=/var/lib/openshift/openshift.local.certificates/openshift-registry/.kubeconfig \
   --images='registry.access.redhat.com/openshift3_beta/ose-${component}:${version}'
----
+
The following should be returned:
+
----

services/docker-registry
deploymentConfigs/docker-registry

----

. Notice that a *Service* and a *DeploymentConfig* have been created for your *Registry* container.

. On the master host get your *Registry* service's port using the *osc get services* command:
+
----

[root@master00-GUID ~]# osc get services

----
+
The following should be returned:
+
----

NAME              LABELS                                    SELECTOR                  IP             PORT(S)
docker-registry   docker-registry=default                   docker-registry=default   172.30.17.54   5000/TCP
kubernetes        component=apiserver,provider=kubernetes   <none>                    172.30.17.2    443/TCP
kubernetes-ro     component=apiserver,provider=kubernetes   <none>                    172.30.17.1    80/TCP

----

. On the master host check that your *docker-registry* pod status is "Running":
+
----

[root@master00-GUID ~]# osc get pods

----
+
The following should be returned:
+
----

POD                       IP         CONTAINER(S)   IMAGE(S)                                                                  HOST                                          LABELS                                                                                  STATUS    CREATED
docker-registry-1-lfx8b   10.1.1.2   registry       registry.access.redhat.com/openshift3_beta/ose-docker-registry:v0.4.3.2   node00-GUID.oslab.opentlc.com/192.168.0.200   deployment=docker-registry-1,deploymentconfig=docker-registry,docker-registry=default   Running   2 hours

----

. On the master host verify that your docker-registry contaienr is online.  Expect "docker-registry server (dev) (v0.9.0)" as a reply:
 
+
----

[root@master00-GUID ~]# curl [yourserviceIP]:[yourservicePORT];echo
#or
[root@master00-GUID ~]# curl `osc get services | grep registry | awk '{print $4":"$5}' | sed -e 's/\/.*//'`;echo

----
+
The following should be returned:
+
----

"docker-registry server (dev) (v0.9.0)"

----
+
[NOTE]
The Registry could take up to a couple of minutes to go on-line

*You have successfully deployed the registry*

=== Redeploy Docker Registry to Primary Region

. On the master host edit the *deploymentConfig* of the *docker-registry* to allow deployment only in the "primary" region.  Search for *podTemplate* then on the next line add the *nodeSelector* section at the same level as *desiredState*.  Under that add *region: primary*:  
+
----

[root@master00-GUID ~]# osc edit deploymentConfigs/docker-registry

----
+
Add the following under podTemplate:
+
----

      nodeSelector:
        region: primary
        
----

. After editing the *DeploymentConfig* should look like this:
+
----

template:
  controllerTemplate:
    podTemplate:
      nodeSelector:
        region: primary
      desiredState:
        manifest:

----

. Write the file and exit the editor.

. On the master host run the `osc get pods` command until the  *docker-registry* is moved to the correct host (Your node01 host):
+
----

[root@master00-GUID ~]# osc get pods

----
+
The following should be returned, take note of the host running the *docker-registry*:
+
----

...OUTPUT OMITTED...
docker-registry-2-4w2pn   10.1.2.6   registry       registry.access.redhat.com/openshift3_beta/ose-docker-registry:v0.4.3.2   node01-GUID.oslab.opentlc.com/192.168.0.201     deployment=docker-registry-2,deploymentconfig=docker-registry,docker-registry=default   Running   17 seconds
...OUTPUT OMITTED...

----

*You have successfully moved the docker registry to the primary region.*

=== Deploy the Router

. On the master host run the *osadm router* command to create the *Router* container
+
----

[root@master00-GUID ~]# osadm router --create \
   --credentials=/var/lib/openshift/openshift.local.certificates/openshift-router/.kubeconfig \
   --images='registry.access.redhat.com/openshift3_beta/ose-${component}:${version}'

----
+
The following should be returned:
+
----

services/router
deploymentConfigs/router

----

. Notice that a *Service* and a *DeploymentConfig* have been created for your *Router* container.

. On the master host view the new resources created for the *Router*:
+
----

[root@master00-GUID ~]# osc get service

----
+
The following should be returned:
+
----

NAME              LABELS                                    SELECTOR                  IP             PORT(S)
docker-registry   docker-registry=default                   docker-registry=default   172.30.17.54   5000/TCP
kubernetes        component=apiserver,provider=kubernetes   <none>                    172.30.17.2    443/TCP
kubernetes-ro     component=apiserver,provider=kubernetes   <none>                    172.30.17.1    80/TCP
router            router=router                             router=router             172.30.17.29   80/TCP

----

. On the master host view the *Router* service:
+
----

[root@master00-GUID ~]# osc describe service router

----
+
The following should be returned:
+
----

Name:                   router
Labels:                 router=router
Selector:               router=router
IP:                     172.30.17.29
Port:                   <unnamed>       80/TCP
Endpoints:              10.1.2.4:80
Session Affinity:       None
No events.

----

. On the master host view the deployment configs:
+
----

[root@master00-GUID ~]# osc get dc

----
+
The following should be returned:
+
----

NAME              TRIGGERS       LATEST VERSION
docker-registry   ConfigChange   1
router            ConfigChange   1

----
+
[NOTE]
This is the same as `osc get deploymentConfigs`

. On the master host view detailed *Router* information:
+
----

[root@master00-GUID ~]# osc describe dc router

----
+
The following should be returned:
+
----

Name:           router
Created:        7 minutes ago
Labels:         router=router
Latest Version: 1
Triggers:       Config
Strategy:       Recreate
...OUTPUT OMITTED...

----

. On the master host check where your *Router* pod has been deployed using the *osc get pods* command, Your *Router* could have been deployed to any of the nodes in your environment:
+
----

[root@master00-GUID ~]# osc get pods

----
+
The following should be returned:
+
----

...OUTPUT OMITTED...
router-1-ioqfa            10.1.2.4   router         registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.4.3.2    node01-GUID.oslab.opentlc.com/192.168.0.201   deployment=router-1,deploymentconfig=router,router=router                               Running   9 minutes
...OUTPUT OMITTED...

----

*You have successfully deployed the router.*

=== Redeploy Router in Infra Region

. In this lab environment*, we must require that our *router* always runs on the *master00* host.  This is due to the fact that our dns wildcard record pointing to the master. In *real-life deployments* you could deploy multiple *router* containers and have your DNS wildcard loadblanced between them.  

. On the master host edit the *deploymentConfig* of the *router* to allow deployment only in the "infra" region.  Search for *podTemplate* then on the next line add the *nodeSelector* section at the same level as *desiredState*.  Under that add *region: infra*:  
+
----

[root@master00-GUID ~]# osc edit deploymentConfigs/router

----
+
Add the following under podTemplate:
+
----

      nodeSelector:
        region: infra
        
----

. After editing the *DeploymentConfig* should look like this:
+
----

template:
  controllerTemplate:
    podTemplate:
      nodeSelector:
        region: infra
      desiredState:
        manifest:

----
+
[NOTE]
In future releases, you will be able to supply NodeSelector and other labels at creation time rather than editing the object after the fact.

. Write the file and exit the editor.

. On the master host run the `osc get pods` command until the  *Router* is moved to the correct host (Your master00 host):
+
----

[root@master00-GUID ~]# osc get pods

----
+
The following should be returned, take note of the host running the router:
+
----

...OUTPUT OMITTED...
router-2-inbv8            10.1.0.2   router         registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.4.3.2    master00-GUID.oslab.opentlc.com/192.168.0.100   deployment=router-2,deploymentconfig=router,router=router                               Running   23 seconds

----

*You have successfully redeployed the router into the infra region.*
