== Resource Quota
:noaudio:

.Quota enforcement
* After a quota is first created in a project, the project restricts the ability to create any new resources that may violate a quota constraint until it has calculated updated usage statistics.

* Once a quota is created and usage statistics are up-to-date, the project accepts the creation of new content. When you create resources, your quota usage is incremented immediately upon the request to create or modify the resource. When you delete a resource, your quota use is decremented during the next full recalculation of quota statistics for the project. As a result, it may take a moment for your quota usage statistics to be reduced to their current observed system value when you delete resources.

* If your modification to a project would exceed a quota usage limit, the action is denied by the server, and an appropriate error message is returned to the end-user. The error explains what quota constraint was violated, and what their currently observed usage stats are in the system.

ifdef::showscript[]

=== Transcript


endif::showscript[]



