== Replication Controllers
:noaudio:

. What Are Replication Controllers:
* A replication controller ensures that a specified number of replicas of a pod are running at all times. If pods exit or are deleted, the replica controller acts to instantiate more up to the desired number. Likewise, if there are more running than desired, it deletes as many as necessary to match the number.
* The definition of a replication controller consists mainly of:
** The number of replicas desired (which can be adjusted at runtime).
** A pod definition for creating a replicated pod.
** A selector for identifying managed pods.
* The selector is just a set of labels that all of the pods managed by the replication controller should have. So that set of labels is included in the pod definition that the replication controller instantiates. This selector is used by the replication controller to determine how many instances of the pod are already running in order to adjust as needed.



ifdef::showscript[]

=== Transcript


endif::showscript[]


