:scrollbar:
:data-uri:
:icons: images/icons
:toc2:		

	
== Users, Projects and Quotas
:numbered:	

In this lab we will:
* Configure htpasswd Authentication. 
* Create Users and Projects. 
* Define and test quota restrictions. 


.Configuring Authentication and Users

. Connect to your master as the `root` user.
+
----
[sborenst@desktop01 ~]$ ssh -i ~/.ssh/sborenstkey.pub shacharb-redhat.com@oselab-*GUID*.oslab.opentlc.com

[bash-4.2$ ~] ssh root@192.168.0.100
root@192.168.0.100's password: ******** (r3dh4t1!) 

----

. Install *httpd-tools* package 
+
----
yum -y install httpd-tools
----

. To configure OpenShift to use *htpasswd Authentication*, edit the */etc/openshift/master.yaml* file and change oauthConfig's identityProviders stanza so that it looks like the following:
+
[source,yaml]
----

identityProviders:
- challenge: true
  login: true
  name: apache_auth
  provider:
    apiVersion: v1
    file: /etc/openshift-passwd
    kind: HTPasswdPasswordIdentityProvider
----

. You can use this *sed* command to make the change from the last instruction.  
+
----
sed -i -e 's/name: anypassword/name: apache_auth/' \
-e 's/kind: AllowAllPasswordIdentityProvider/kind: HTPasswdPasswordIdentityProvider/' \
-e '/kind: HTPasswdPasswordIdentityProvider/i \      file: \/etc\/openshift-passwd' \
/etc/openshift/master.yaml

----


. Restart the OpenShift Master
+
----
systemctl restart openshift-master
----

.Create users and Authenticate
 
. Create users to use with htpasswd-based authentication method
+
----
touch /etc/openshift-passwd
htpasswd -b /etc/openshift-passwd andrew r3dh4t1!
htpasswd -b /etc/openshift-passwd marina r3dh4t1! 

----

. Log in to web console using the user "Andrew" : link:https://master00-GUID.oslabs.opentlc.com:8443[https://master00-GUID.oslabs.opentlc.com:8443]
NOTE: Notice that we didn't create "users" in the operating system, just OpenShift users. We will also create local/O.S users for andrew and marina but that is only for the benefit of the training environment. 

. Create "system" users for Andrew and Marina
+
----
useradd andrew
useradd marina
----  

. Authenticate using the command line as user "Andrew" 
+
----
su - andrew

osc login -u andrew \
--certificate-authority=/var/lib/openshift/openshift.local.certificates/ca/cert.crt \
--server=https://master00-${GUID}.oslab.opentlc.com:8443 
Password: (Enter r3dh4t1!)
Login successful.

----

. Review your OpenShift authentication token and explore your new powers
+
[source,yaml]
----
cat ~/.config/openshift/.config

osc get pods

osc get projects 

osc get nodes 

----

.Creating Projects
 
. As root, use the *osadm new-project* command to create projects for our users:
+
----
# A project for Andrew
osadm new-project atom --display-name="ProjectA" \
--description="This is Project Atom for Andrew" \
--admin=andrew

# A project for Marina 
osadm new-project magma --display-name="ProjectM" \
--description="This is Project Magma for Marina" \
--admin=marina

# A project for both 
osadm new-project plasma --display-name="ProjectMA" \
--description="This is Project plasma for Marina and Andrew" \
--admin=marina,andrew

----

. Log in to the Web Console and verify you can see the projects 

. Use the command line as "andrew" and your available projects
+
----
osc get projects 
---- 

. Set your current project to be : "atom"
+
----
osc project atom
----

.Quotas

. As Andrew, Test your limits before the the quota is applied, create *hello-quota.json* file and use it to create a series of pods. 
+
----
osc project atom

curl http://www.opentlc.com/downloads/ose_implementation/files/hello-quota.json > hello-quota.json

osc create -f hello-quota.json

----
NOTE: Have a look at *hello-quota.json* to understand better what is going on. Later on we will learn more exciting ways to scale up an application.

. Check how many pods are created using the *osc get pods* command
+
----
osc get pods 

----

. Clean up and delete all the pods created in this lab.
+
----
osc delete -f hello-quota.json
#or 
osc delete pod `osc get pods |grep hello-openshift | awk '{print $1}'`

----


. As Root, Create and review the quota config file
+

[source,json]
----

curl http://www.opentlc.com/downloads/ose_implementation/files/quota.json > quota.json

cat quota.json 
{
  "apiVersion": "v1beta3",
  "kind": "ResourceQuota",
  "metadata": {
    "name": "atom-quota"
  },
  "spec": {
    "hard": {
      "memory": "512Mi",
      "cpu": "200m",
      "pods": "2",
      "services": "2",
      "replicationcontrollers": "2",
      "resourcequotas": "1"
    }
  }
}
----

. As Root, Apply the Quota to the "atom" project.
+
----
osc create -f quota.json --namespace=atom

----

. Check what was created 
+
----
osc get -n atom quota
NAME
atom-quota

osc describe quota atom-quota -n atom
Name:                   atom-quota
Resource                Used    Hard
--------                ----    ----
cpu                     0m      200m
memory                  0       512Mi
pods                    0       2
replicationcontrollers  0       2
resourcequotas          1       1
services                0       2
----

. As Andrew, Try again to create *hello-quota.json* in the "atom" project
+
----
osc create -f hello-quota.json
pods/1-hello-openshift
pods/2-hello-openshift
Error: pods "3-hello-openshift" is forbidden: Limited to 2 pods
Error: pods "4-hello-openshift" is forbidden: Limited to 2 pods
----

. Try to create *hello-quota.json* in another project, Should the quota apply there? (no)
+
----
osc project plasma 

osc create -f hello-quota.json
pods/1-hello-openshift
pods/2-hello-openshift
pods/3-hello-openshift
pods/4-hello-openshift

----





