== Configuring Authentication
:noaudio:

.Identity Providers - HTPasswd

* Set _HTPasswdPasswordIdentityProvider_ in the `identityProviders` stanza to
validate user names and passwords against a flat file generated using
http://httpd.apache.org/docs/2.4/programs/htpasswd.html[`htpasswd`].

* Only MD5 and SHA encryption types are supported. MD5 encryption is recommended,
and is the default for `htpasswd`.
** Plaintext, crypt, and bcrypt hashes are not currently supported.

* The flat file is re-read if its modification time changes, without requiring a
server restart.

* Master Configuration Using *HTPasswdPasswordIdentityProvider*:
+
[source,yaml]
----
oauthConfig:

  identityProviders:
  - name: my_htpasswd_provider <1>
    challenge: true <2>
    login: true <3>
    provider:
      apiVersion: v1
      kind: HTPasswdPasswordIdentityProvider
      file: /path/to/users.htpasswd <4>
----

<1> This provider name is prefixed to provider user names to form an identity
name.
<2> When *true*, unauthenticated token requests from non-web clients (like the
CLI) are sent a `WWW-Authenticate` challenge header for this provider.
<3> When *true*, unauthenticated token requests from web clients (like the web
console) are redirected to a login page backed by this provider.
<4> File generated using
http://httpd.apache.org/docs/2.4/programs/htpasswd.html[`htpasswd`].

ifdef::showscript[]
=== Transcript

endif::showscript[]

