== Module Topics



* Overview and design concepts in OpenShift Enterprise by Red Hat version 3.0
* Introduction to Docker
* Introduction to Kubernetes infrastructure
* Networking in OpenShift Enterprise 3.0
* Image registry
* Builds and OpenShift Enterprise S2I images


ifdef::showscript[]

=== Transcript

Welcome to module two of the OpenShift Enterprise Implementation course.

This module covers the following topics:

* Overview and design concepts in OpenShift Enterprise by Red Hat version 3.0, including the
OpenShift stack, how OpenShift works, standards, important projects, and how the
various components work together

* An introduction to Docker, including the difference between containers and
VMs and Docker components and capabilities

* An introduction to Kubernetes infrastructure, covering features and concepts.

* An overview of networking in OpenShift Enterprise 3.0

* A description of the image registry, including the integrated OpenShift
Enterprise registry and third-party registries

* A discussion of builds and OpenShift Enterprise S2I images, including what an S2I build is and reasons to use it

endif::showscript[]
