== What Is OpenShift Container Platform

* Platform-as-a-Service (PaaS)
* Uses industry standards
* Provides development environments on demand (self-service)
* Provides languages, frameworks, runtimes, and databases (polyglot)
* Automates application lifecycle management (build, deploy, retire)
* Enables collaboration between developers on projects and components



ifdef::showscript[]

=== Transcript

This module begins with an overview of OpenShift Container Platform design concepts.

OpenShift Container Platform is a Platform-as-a-Service, or PaaS, that is based on
 industry
standards. OpenShift Container Platform is a self-service platform, meaning that it
 provides development environments on demand. As a polyglot offering, it
  includes a range of languages, frameworks, runtimes, and databases. It also
   automates management of the entire application lifecycle: build, deploy, and
    retire.

OpenShift Container Platform enables collaboration between developers on projects and
 components.


endif::showscript[]
