== OpenShift Container Platform Workflow

.Scenario
* Application needs to be scaled up to accommodate overall increase or upcoming
 spike in traffic
* Request could be:
** Manual API call/command line
** Initiated by external monitoring agent

* OpenShift Container Platform workflow:
. API call made (CLI, REST API, automation process)
. Data store gets new information (desired scale = 6 pods)
. Replication controllers see mismatch between current scale (3 pods) and
desired scale (6 pods)
. OpenShift Container Platform schedules and deploys 3 instances (pods)


ifdef::showscript[]

=== Transcript

Put simply, OpenShift Container Platform manages its workflow as follows:

. Users or automation make calls to the REST API (using the web console, command
   line, or any other method) to change the state of the system.
. OpenShift Container Platform periodically checks to see what system state the call
 wants.
. OpenShift Container Platform then works to bring the other parts of the system into
sync with the desired state.

For example: Say an OpenShift Container Platform 3 user predicts a spike in traffic
 before a holiday or major sports event.
The user wants to spin up more pods of a specific service/application to
 accommodate the additional traffic.

The application has three pods running, and the user wants to double that
 number, to six running pods, as a pre-emptive measure.

The user uses the web console, CLI, or other method to make a call to the master
 stating that the application should have six instances.

The Master updates the data store with the new information that the desired
 scale is six running pods.

On the next sync loop, the replication controllers determine that the current
 scale of three running pods does not match the desired scale of six running
  pods.

OpenShift Container Platform then schedules three more instances and places them for
 deployment.


endif::showscript[]
