:noaudio:
== Docker Components


* *Docker daemon*: Runs on host machine
* *Docker client*: Primary user interface to Docker
* *Docker images*: Read-only template
* *Docker registries*: Hold images
* *Docker containers*: Hold everything needed for application to run

ifdef::showscript[]

=== Transcript

The Docker daemon runs on a host machine. You do not interact directly with the
daemon when using OpenShift Enterprise.

The Docker client is the primary user interface. It accepts commands
from the user and communicates back and forth with a Docker daemon.

A Docker image is a read-only template. For example, an image could contain
Red Hat Enterprise Linux 7-compatible libraries for Apache and your web
application source code.

Docker registries hold images. Registries are public or private stores from
which you upload or download images.

Docker containers hold everything that is needed for an application to run.
Each container is created from a Docker image. You can start, run, terminate, and
 delete Docker containers.

endif::showscript[]

