== OpenShift Enterprise Networking Basics

* One or more OpenShift Enterprise nodes host the `Default Router`:
** `Default Router`: An HA-Proxy instance running inside a container to "route"
(but actually _proxy_) between the outside world and pods in OpenShift Enterprise
environment
** The `Default Router`:
*** Binds an `fqdn` (e.g., `myapp.mydomain.org`) to OpenShift Enterprise
environment address/addresses
*** Routinely gets pod's IPs from the `service` representing them
*** Routes/proxies to pods directly, not through the `service`
* Configure DNS server to resolve `wildcard` DNS entry to the node that hosts
 `Default Router`


ifdef::showscript[]

=== Transcript

A container running an instance of HA-Proxy is hosted on one or more of the
nodes in the OpenShift Enterprise environment. We call this instance the _Default
Router_.

The router's function is to resolve `fqdn` hostname requests and proxy the
connection directly to any of the pods represented by the service.

You need to configure a DNS entry in the client's DNS server to resolve a
 wildcard entry such as `*.cloudapps.companynameexample.com`.

endif::showscript[]
