== Lifecycle Hooks
:noaudio:

The Recreate and Rolling strategies support lifecycle hooks, which allow
behavior to be injected into the deployment process at predefined points within the strategy:

* The following is an example of a "pre" lifecycle hook:
+
[source,json]
----
"pre": {
  "failurePolicy": "Abort",
  "execNewPod": {}
}
----

** execNewPod is a pod-based lifecycle hook.


* Every hook has a failurePolicy, which defines the action the strategy should
take when a hook failure is encountered:

|====
|Abort|The deployment should be considered a failure if the hook fails.
|Retry|The hook execution should be retried until it succeeds.
|Ignore|Any hook failure should be ignored and the deployment should proceed.
|====

WARNING: Some hook points for a strategy might support only a subset of failure
policy
values. For example, the Recreate and Rolling strategies do not currently
support the Abort policy for a "post" deployment lifecycle hook. Consult the
documentation for a given strategy for details on any restrictions regarding
lifecycle hooks.

* Hooks have a type-specific field that describes how to execute the hook.
* Currently pod-based hooks are the only supported hook type,
specified by the execNewPod field


ifdef::showscript[]

endif::showscript[]

