
:noaudio:
:scrollbar:
:data-uri:
== What is Docker

* *Docker* - Open platform for developers and admins to build, ship, and run distributed applications.

* Main support components:
** Docker Engine, a portable, lightweight runtime and packaging tool
** Docker Hub, a cloud service for sharing applications and automating workflows
* Benefits:
** Multi-version packaging format and isolation
** Simplified container API (Docker libcontainer)
** Easy to create (Dockerfile)
** Atomic deployment (Docker images)
** Large ecosystem (Docker Hub)



ifdef::showscript[]

=== Transcript

This next portion of the module provides an introduction to Docker.
Docker is an open platform for developers and system administrators to build, ship, and run distributed applications. The main components are the Docker Engine and the Docker hub. 
Docker Engine is a portable, lightweight runtime and packaging tool. Docker Hub is a cloud service for sharing applications and automating workflows.

Docker has a number of benefits, as shown here. Docker images are described in detail later.



endif::showscript[]




