
:scrollbar:
:data-uri:
== Introduction to Docker

=== Docker Components

* The Docker daemon -  Runs on a host machine. The user does not directly interact with the daemon, but instead through the Docker client.
** The Docker client - The primary user interface to Docker. It accepts commands from the user and communicates back and forth with a Docker daemon.
** Docker images - A Docker image is a read-only template. For example, an image could contain an Red Hat Enterprise Linux 7 operating system with Apache and your web application installed.
** Docker registries - Holds images. These are public or private stores from which you upload or download images.
** Docker containers - Holds everything that is needed for an application to run. Each container is created from a Docker image. Docker containers can be run, started, stopped, moved, and deleted. Each container is an isolated and secure application platform.

* With Docker you can:
** Build Docker images that hold your applications.
** Create Docker containers from those Docker images to run your applications.
** Share and reuse those Docker images via Docker Hub or your own registry.





ifdef::showScript[]

=== Transcript

* The Docker daemon -  Runs on a host machine. The user does not directly interact with the daemon, but instead through the Docker client.
** The Docker client - The primary user interface to Docker. It accepts commands from the user and communicates back and forth with a Docker daemon.
** Docker images - A Docker image is a read-only template. For example, an image could contain an Red Hat Enterprise Linux 7 operating system with Apache and your web application installed.
** Docker registries - Holds images. These are public or private stores from which you upload or download images.
** Docker containers - Holds everything that is needed for an application to run. Each container is created from a Docker image. Docker containers can be run, started, stopped, moved, and deleted. Each container is an isolated and secure application platform.

* With Docker you can:
** Build Docker images that hold your applications.
** Create Docker containers from those Docker images to run your applications.
** Share and reuse those Docker images via Docker Hub or your own registry.


endif::showScript[]



