
:noaudio:
:scrollbar:
:data-uri:
== What is Kubernetes

* *Kubernetes* - Open source system for managing containerized applications across multiple hosts

* Provides basic mechanisms for deployment, maintenance, and scaling of applications
** *Lean* - Lightweight, simple, accessible
** *Portable* - Public, private, hybrid, multi-cloud
** *Extensible* - Modular, pluggable, hookable, composable
** *Self-healing* - Autoplacement, autorestart, autoreplication

* Builds on over 1.5 decades of experience at Google
+
link:https://github.com/googlecloudplatform/kubernetes[https://github.com/googlecloudplatform/kubernetes]




ifdef::showscript[]

=== Transcript

Next we take a look at the Kubernetes infrastructure. 
Kubernetes is an open source system for managing containerized applications across multiple hosts. It provides basic mechanisms for deployment, maintenance, and scaling of applications.

Kubernetes is lean, portable, extensible, and self-healing. Kubernetes builds upon a decade and a half of experience at Google.

endif::showscript[]



