
:scrollbar:
:data-uri:
== Introduction to Docker

=== How does a Docker Image work?


* Docker images are read-only templates from which Docker containers are launched.
* Each image consists of a series of layers. Docker makes use of union file systems to combine these layers into a single image.
* Union file systems allow files and directories of separate file systems, known as branches, to be transparently overlaid, forming a single coherent file system.
* When you change a Docker image—for example, update an application to a new version— a new layer gets built.
* You don't need to distribute a whole new image, just the update.

ifdef::showScript[]

=== Transcript

* Docker images are read-only templates from which Docker containers are launched.
* Each image consists of a series of layers. Docker makes use of union file systems to combine these layers into a single image.
* Union file systems allow files and directories of separate file systems, known as branches, to be transparently overlaid, forming a single coherent file system.
* When you change a Docker image—for example, update an application to a new version— a new layer gets built.
* You don't need to distribute a whole new image, just the update.


endif::showScript[]


