
:scrollbar:
:data-uri:
== Introduction to Kubernetes Infrastructure

=== Concepts

* Nodes - are the compute resources on top of which your containers are built.
* Pods  - are a colocated group of containers with shared storage volumes.
** Smallest deployable units that can be created, scheduled, and managed with Kubernetes.
* Replication controllers - manage the lifecycle of pods. They ensure that a specified number of pods are running at any given time, by creating or killing pods as required.
* Services - provide a single, stable name and address for a set of pods. They act as basic load balancers.
* Labels - are used to organize and select groups of objects based on key:value pairs.


ifdef::showScript[]

=== Transcript

* Nodes - are the compute resources on top of which your containers are built.
* Pods  - are a colocated group of containers with shared storage volumes.
** Smallest deployable units that can be created, scheduled, and managed with Kubernetes.
* Replication controllers - manage the lifecycle of pods. They ensure that a specified number of pods are running at any given time, by creating or killing pods as required.
* Services - provide a single, stable name and address for a set of pods. They act as basic load balancers.
* Labels - are used to organize and select groups of objects based on key:value pairs.

endif::showScript[]

