== Pods
:noaudio:

* Correspond to colocated group of applications running with shared context
** May have individual cgroup isolations applied
* Models an application-specific logical host in a containerized environment
** May contain one or more applications that are relatively tightly coupled
** Example: Web server and a “file puller/syncer”
* Smallest deployable units that can be created, scheduled, and managed
* Consist of colocated group of Docker containers with shared volumes


ifdef::showscript[]

=== Transcript

A pod corresponds to a colocated group of applications running with a shared
context.  Within that context, the applications may also have individual cgroup
isolations applied. A pod models an application-specific logical host in a
containerized environment.
A pod may contain one or more applications that are relatively tightly coupled.
For example, a Pod could contain a web server and a “file puller/syncer.” In a
pre-container world, they would have executed on the same physical or virtual
host.

In Kubernetes, rather than individual application containers, pods are the
smallest deployable units that can be created, scheduled, and managed.
In terms of Docker constructs, a pod consists of a colocated group of Docker
containers.


endif::showscript[]



