== OpenShift Enterprise Networking Basics
:noaudio:

* One or more OpenShift Enterprise nodes hosts `Default Router`:
** `Default Router`: An HA-Proxy instance running inside container to route
(_proxy_) between outside world and pods in OpenShift Enterprise environment
** `Router`:
*** Binds hostname `fqdn` (e.g., `myapp.mydomain.org`) to OpenShift Enterprise environment address/addresses
*** Routinely gets pods' IPs from service representing them
*** Routes/proxies to pods directly, not through service
* Configure DNS server to resolve `wildcard` DNS entry to node that hosts `Default Router` 
** `Infranode00` host used in labs

ifdef::showscript[]

=== Transcript

A container running an instance of HA-Proxy is hosted on one or more of the
nodes in the OpenShift Enterprise environment. We call this instance the _Default
Router_.

The router's function is to resolve `fqdn` hostname requests and proxy the
connection directly to any of the pods represented by the service.

You need to configure a DNS entry in the client's DNS server to resolve a wildcard
entry such as `*.cloudapps.companynameexample.com`.

endif::showscript[]


