
:scrollbar:
:data-uri:
== Builds and OpenShift STI Images

=== Why we use STI builds


* OpenShift v3 provides a developer-centric flow that focuses on turning your source code into a running application as simply as possible. 
** Source-to-Image is a project started to make it easy to take source code and combine it with an image that contains both a build and runtime environment for that source code (called a “builder image”) .
** Having a strong separation between source code (or even binary artifacts like WARs or EARs in Java) and the runtime environment in the Docker image helps migrate your code between:
***  runtime environments like Tomcat and other JEE servers, 
*** across major versions of a runtime like Ruby 1.9 and Ruby 2.0, 
*** and even across operating system versions like CentOS and Red Hat Enterprise Linux.



ifdef::showScript[]

=== Transcript

* OpenShift v3 provides a developer-centric flow that focuses on turning your source code into a running application as simply as possible. 
** Source-to-Image is a project started to make it easy to take source code and combine it with an image that contains both a build and runtime environment for that source code (called a “builder image”) .
** Having a strong separation between source code (or even binary artifacts like WARs or EARs in Java) and the runtime environment in the Docker image helps migrate your code between:
***  runtime environments like Tomcat and other JEE servers, 
*** across major versions of a runtime like Ruby 1.9 and Ruby 2.0, 
*** and even across operating system versions like CentOS and Red Hat Enterprise Linux.

endif::showScript[]



























