

== EAP Example

This example requires internet access because the Maven configuration uses
public repositories.

If you have a Java application whose Maven configuration uses local
repositories, or has no Maven requirements, you could probably substitute that
code repository for the one below.

=== Create a Project

Using the skills you have learned earlier in the training, create a new project
for the EAP example. Make sure to use the user that created the project in the subsequent commands.

=== Instantiate the Template
When we imported the imagestreams into the `openshift` namespace earlier, we
also brought in JBoss EAP and Tomcat S2I builder images.

\\

. Download an EAP template and secret file for use in the lab:
+
----
[marina@master00-GUID ~]$ wget https://raw.githubusercontent.com/openshift/training/master/beta4/eap6-basic-sti.json
[marina@master00-GUID ~]$ wget https://raw.githubusercontent.com/openshift/training/master/beta4/eap-app-secret.json
----

Take a look at the `eap6-basic-sti.json` file you just downloaded.  You'll see that
there are a number of bash-style variables (`${SOMETHING}`) in use in this
template. This template is already configured to use the EAP builder image, so
we can use the web console to simply isntantiate it in the desired way.

We want to:

* set the application name to *helloworld*

* set the application hostname to *helloworld.cloudapps-GUID.oslab.opentlc.com*

* set the Git URI to *https://github.com/jboss-developer/jboss-eap-quickstarts/*

* set the Git ref to *6.4.x*

* set the Git context dir to *helloworld*

* set Github and Generic trigger secrets to *secret*

\\

. Update the JSON file with the correct domain:
+
----

[marina@master00-GUID ~]$ sed -i "s/cloudapps.example.com/cloudapps-$GUID.oslab.opentlc.com/" eap6-basic-sti.json

----

. Add the `eap6-basic-sti.json` template to your project using the commandline:
+
----

[marina@master00-GUID ~]$ oc create -f eap6-basic-sti.json

----

. Create the secret for the EAP template:
+
----

[marina@master00-GUID beta4]$ oc create -f eap-app-secret.json

----

. Go into the web console.

. Find the project you created and click on it.

. Click the "Create..." button.

. Click the "Browse all templates..." button.

. Click the "eap6-basic-sti" example.

. Click "Select template".

. Now that you are on the overview page, you'll have to click "Edit Paremeters"
and fill in the values with the things we wanted above.

. Hit "Create" when you are done.

In the UI you will see a bunch of things get created -- several services, some
routes, and etc.

=== Update the BuildConfig

The template assumes that the imageStream exists in our current project, but
that is not the case. The EAP imageStream exists in the `openshift` namespace.

. Edit the resulting `buildConfig` and specify that.
+
----

[marina@master00-GUID ~]$ oc edit bc helloworld

----

. You will need to edit the `strategy` section to look like the following:

    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap6-openshift:6.4
          namespace: openshift

**REMEMBER** indentation is *important* in YAML.

=== Watch the Build

In a few moments a build will start. You can watch the build if you choose, or
just look at the web console and wait for it to finish. If you do watch the
build, you might notice some Maven errors.  These are non-critical and will not
affect the success or failure of the build.

=== Visit Your Application

We specified a route via defining the application hostname, so you should be able to
visit your app at:

    http://helloworld.cloudapps-GUID.oslab.opentlc.com/jboss-helloworld

The reason that it is "/jboss-helloworld" and not just "/" is because the
helloworld application does not use a "ROOT.war".


:numbered!:
