 
:noaudio:

== Why S2I?
* *Image flexibility* - S2I scripts can be written to layer application code onto almost any existing Docker image, taking advantage of the existing ecosystem. Note that, currently, S2I relies on tar to inject application source, so the image needs to be able to process tarred content.
* *Speed* - With S2I, the assemble process can perform a large number of complex operations without creating a new layer at each step, resulting in a fast process. In addition, S2I scripts can be written to re-use artifacts stored in a previous version of the application image, rather than having to download or build them, each time the build is run.
* *Patchability* - S2I allows you to rebuild the application consistently if an underlying image needs a patch due to a security issue.
* *Operational efficiency* - By restricting build operations instead of allowing arbitrary actions, such as in a Dockerfile, the PaaS operator can avoid accidental or intentional abuses of the build system.
* *Operational security* - Building an arbitrary Dockerfile exposes the host system to root privilege escalation. This can be exploited by a malicious user because the entire docker build process is run as a user with docker privileges. S2I restricts the operations performed as a root user, and can run the scripts as a non-root user.
* *User efficiency* - S2I prevents developers from performing arbitrary yum install type operations during their application build, which results in slow development iteration.
* *Ecosystem* - S2I encourages a shared ecosystem of images where you can leverage best practices for your applications. 

ifdef::showscript[]

=== Transcript

* *Image flexibility* - S2I scripts can be written to layer application code onto almost any existing Docker image, taking advantage of the existing ecosystem. Note that, currently, S2I relies on tar to inject application source, so the image needs to be able to process tarred content.
* *Speed* - With S2I, the assemble process can perform a large number of complex operations without creating a new layer at each step, resulting in a fast process. In addition, S2I scripts can be written to re-use artifacts stored in a previous version of the application image, rather than having to download or build them, each time the build is run.
* *Patchability* - S2I allows you to rebuild the application consistently if an underlying image needs a patch due to a security issue.
* *Operational efficiency* - By restricting build operations instead of allowing arbitrary actions, such as in a Dockerfile, the PaaS operator can avoid accidental or intentional abuses of the build system.
* *Operational security* - Building an arbitrary Dockerfile exposes the host system to root privilege escalation. This can be exploited by a malicious user because the entire docker build process is run as a user with docker privileges. S2I restricts the operations performed as a root user, and can run the scripts as a non-root user.
* *User efficiency* - S2I prevents developers from performing arbitrary yum install type operations during their application build, which results in slow development iteration.
* *Ecosystem* - S2I encourages a shared ecosystem of images where you can leverage best practices for your applications. 


endif::showscript[]


 
 
