
== `BuildConfig`

* A *buildConfig* describes a single build definition and a set of triggers for when a new build should be created.
* A *buildConfig* is a REST object, which can be used in a POST to the API server to create a new instance. The following example buildConfig results in a new build every time a Docker image tag or the source code changes: 
* *`BuildConfig` object* - Definition of the entire build process consisting of:
** *triggers* - Define policies for invoking builds
*** *GitHub webhooks* - Specify which repository changes invoke a new build; specific to the GitHub API
*** *generic webhooks* - Invoke a new build when notified; payload slightly different from GitHub
*** *image change* - Invoked when new image is available in specified `ImageRepository`
** *parameters*
*** `source` - Describes SCM used to locate the sources; supports Git only
*** `strategy` - Describes invoked build type and build type details
*** `output` - Describes resulting image name, tag, and registry to which OpenShift Enterprise should push image

ifdef::showscript[]

=== Transcript

The `BuildConfig` object is the definition of the entire build process. 
It consists of the following elements: the triggers that define policies used to automatically invoke builds and the parameters that point OpenShift Enterprise to your source code and builder image.

The three trigger types include:

* GitHub-specific webhooks, which specify the repository changes, such as a new commit, that invokes a new build. This trigger is specific to the GitHub API.
* The second trigger type is generic webhooks. This trigger is similar to GitHub webhooks in that it invokes a new build whenever it receives a notification. 
* And lastly, image change is a trigger that is invoked when a new image is available in the specified `ImageRepository` or 'ImageStream'

The three parameter types include:

* `source`, which describes the SCM used to locate the source code. The source parameter currently supports Git only.
* `strategy`, which describes the build type being invoked, along with build type-specific details.
* And `output`, which describes the resulting image name, tag, and registry to which OpenShift Enterprise should push the image.

endif::showscript[]

