:icons: images/icons
:toc2:

:numbered:



== Lab: Arbitrary Docker Image (WordPress)

One of the first things we did with OpenShift was launch an "arbitrary" Docker
image from the Docker Hub. However, we can also build Docker images from Docker
files, too. While this is a "build" process, it's not a "source-to-image"
process -- we're not working with only a source code repo.

As an example, the CentOS community maintains a Wordpress all-in-one Docker
image:

    https://github.com/CentOS/CentOS-Dockerfiles/tree/master/wordpress/centos7

We've taken the content of this subfolder and placed it in the GitHub
`openshift/centos7-wordpress` repository.

. Either from the *Master* or from your *desktop* authenticate to openshift as
*marina*
+
----
[marina@master00~]$ oc login -u marina --insecure-skip-tls-verify --server=https://master00-${GUID}.oslab.opentlc.com:8443
----

=== Create a Project

. As `marina`, go ahead and create a new project:
+
----
[marina@master00-GUID ~]$ oc new-project wordpress --display-name="Wordpress" \
    --description='Building an arbitrary Wordpress Docker image'
----



=== Build Wordpress

. Run `oc new-app` and see what happens:
+
----
[marina@master00-GUID ~]$ oc new-app https://github.com/openshift/centos7-wordpress.git -o yaml
----

. Let's choose the Wordpress example:
+
----

[marina@master00-GUID ~]$ oc new-app -l name=wordpress https://github.com/openshift/centos7-wordpress.git

----
+
----

imageStreams/centos
imageStreams/centos7-wordpress
buildConfigs/centos7-wordpress
deploymentConfigs/centos7-wordpress
services/centos7-wordpress
A build was created - you can run `oc start-build centos7-wordpress` to start it.
Service "centos7-wordpress" created at 172.30.135.252 with port mappings 22.

----
+
[NOTE]
This can take a *really* long time to build.**

. Fix the json file from the training repo to match the lab hostnames:
+
----

[marina@master00-GUID ~]$ sed -i "s/cloudapps.example.com/cloudapps-$GUID.oslab.opentlc.com/" ~/training/beta4/wordpress-addition.json

----

. You will need a route for this application, as `curl` won't do a whole lot for
us here. Additionally, `oc new-app` currently has a bug in the way services are
detected, so we'll have a service for SSH (thus port 22 above) but not one for
httpd. So we'll add on a service and route for web access.
+
----

[marina@master00-GUID ~]$ cd ~/training/beta4; oc create -f wordpress-addition.json

----

=== Test Your Application

. You should be able to visit:

    http://wordpress.cloudapps-GUID.oslab.opentlc.com

Remember - not only did we use an arbitrary Docker image, we actually built the
Docker image using OpenShift. Technically there was no "code repository". So, if
you allow it, developers can actually simply build Docker containers as their
"apps" and run them directly on OpenShift.

=== Application Resource Labels

You may have wondered about the `-l name=wordpress` in the invocation above. This
applies a label to all of the resources created by `oc new-app` so that they can
be easily distinguished from any other resources in a project.

. For example, we can easily delete only the things with this label:
+
----

[marina@master00-GUID ~]$ oc delete all -l name=wordpress

----
+
----

buildConfigs/centos7-wordpress
builds/centos7-wordpress-1
imageStreams/centos
imageStreams/centos7-wordpress
deploymentConfigs/centos7-wordpress
replicationcontrollers/centos7-wordpress-1
services/centos7-wordpress

----

. Notice that the things we created from wordpress-addition.json didn't
have this label, so they didn't get deleted:
+
----

[marina@master00-GUID ~]$ oc get services

----
+
----

NAME                      LABELS    SELECTOR                             IP             PORT(S)
wordpress-httpd-service   <none>    deploymentconfig=centos7-wordpress   172.30.17.83   80/TCP

----
+
----

[marina@master00-GUID ~]$ oc get route

----
+
----

NAME              HOST/PORT                         PATH      SERVICE                   LABELS
wordpress-route   wordpress.cloudapps.example.com             wordpress-httpd-service

----

Labels will be useful for many things, including identification in the web console.


== Lab: Deploy an STI Build

In this lab, you create a simple STI build. As part of this process, you create a `BuildConfig` object and build an image using the STI build process. You also create the pod, service, and route for your STI build image.

:numbered:
=== Prepare Your Environment

If you have not done so in previous labs, follow these steps before starting this lab.

. Connect to your master with the `root` user.
. Run the post-deployment script:
+
----
[sborenst@desktop01 ~]$ ssh -i ~/.ssh/sborenstkey.pub shacharb-redhat.com@oselab-GUID.oslab.opentlc.com

[bash-4.2$ ~] ssh root@192.168.0.100
root@192.168.0.100's password: ******** (r3dh4t1!)
----
+
[NOTE]
This process might take a while. Use this time to read the lab and get a good understanding of the scenario.


=== Authenticate to OpenShift Enterprise and Choose Your Project

. On the master host as root create a project called *hello-s2i*:
+
----

[root@master00-GUID ~]# oadm new-project hello-s2i --display-name="Resources Management" \
    --description="This is the project we use to learn about resource management" \
    --admin=andrew

----

. Become and authenticate to OpenShift Enterprise as user `andrew`:
+
----

[root@master00 ~]# su - andrew
[andrew@master00 ~]$ guid=`hostname|cut -f2 -d-|cut -f1 -d.`
[andrew@master00 ~]$ oc login -u andrew --insecure-skip-tls-verify --server=https://master00-${guid}.oslab.opentlc.com:8443

----

. Change the context to the `hello-s2i` project:
+
----

[andrew@master00 ~]$ oc project hello-s2i
Now using project "hello-s2i" on server "https://master00-GUID.oslab.opentlc.com:8443".

----

. Check your current context:

.. View the `~/.kube/config` file to review the information.
.. Run the following command for a quick test:
+
----

[andrew@master00 ~]$ grep current ~/.kube/config
current-context: hello-s2i/master00-GUID-oslab-opentlc-com:8443/andrew

----

=== Create Your S2I description

For this activity, you use a prebuilt and preconfigured code repository. This repository is an extremely simple application of the `Hello World` type.

. Go to link:https://github.com/openshift/simple-openshift-sinatra-sti[https://github.com/openshift/simple-openshift-sinatra-sti]. You will use this application's source code.

. Take a minute to review the repository.
. To create the instructions and configuration for your image, use the `oc new-app` command as follows:
** To use the default image suggested by the builder, run the following:
+
----

[andrew@master00 ~]$ oc new-app https://github.com/openshift/simple-openshift-sinatra-sti.git -o json | tee ~/simple-sinatra.json
----

. Look at the JSON that you generated.
+
----
[andrew@master00 ~]$ cat ~/simple-sinatra.json

----

=== Start Your Build


. To create the build components, use the `oc create` command on the `BuildConfig` file:
+
----

[andrew@master00 ~]$ oc create -f ~/simple-sinatra.json

----

. To see the output of the last command, run the following:
+
----

[andrew@master00 ~]$ for i in buildconfig deploymentconfig service; do echo $i; oc get $i; echo -e "\n\n"; done


----

. Output after build is complete would look similar to this:
+
----
NAME                           TYPE      SOURCE
simple-openshift-sinatra-sti   Source    https://github.com/openshift/simple-openshift-sinatra-sti.git

deploymentconfig
NAME                           TRIGGERS                    LATEST VERSION
simple-openshift-sinatra-sti   ConfigChange, ImageChange   2

service
NAME                       LABELS    SELECTOR                                        IP(S)           PORT(S)
simple-openshift-sinatra   <none>    deploymentconfig=simple-openshift-sinatra-sti   172.30.64.255   8080/TCP

----

. Watch the running pods in realtime:
+
----

[andrew@master00 ~]$ watch oc get pods

. Note you will see an error for a few minutes, it will clear up:
+
----

NAME                                   READY     REASON                                                               RESTARTS   AGE
simple-openshift-sinatra-sti-1-o72am   0/1       Error: image library/simple-openshift-sinatra-sti:latest not found   0          1m

----

. Eventually it will build and look like this:
+
----

NAME                                   READY     REASON       RESTARTS   AGE
simple-openshift-sinatra-sti-1-build   0/1       ExitCode:0   0          2m
simple-openshift-sinatra-sti-2-cpp9t   1/1       Running      0          7m
...
CTRL+C

----
+

NOTE: Don't be alarmed if you see that the pod has failed to deploy, that happens before our image is created and will rectify itself once the image build process is complete.


. To view the current build status and build logs, run the following:
+
----

[andrew@master00 ~]$ oc get builds
NAME                             TYPE      STATUS     POD
simple-openshift-sinatra-sti-1   Source    Complete   simple-openshift-sinatra-sti-1-build

----

. View the Build log
+
----
[andrew@master00 ~]$ oc build-logs simple-openshift-sinatra-sti-1
....
....
....
I0702 05:36:50.618747       1 sti.go:246] Successfully built 172.30.133.153:5000/sinatra/simple-openshift-sinatra-sti
I0702 05:36:50.703511       1 cleanup.go:23] Removing temporary directory /tmp/sti235763477
I0702 05:36:50.703600       1 fs.go:99] Removing directory '/tmp/sti235763477'
I0702 05:36:50.727475       1 cfg.go:46] PUSH_DOCKERCFG_PATH=/var/run/secrets/openshift.io/push/.dockercfg
I0702 05:36:50.733088       1 cfg.go:64] Using serviceaccount user for Docker authentication
I0702 05:36:50.733130       1 sti.go:96] Using provided push secret for pushing 172.30.133.153:5000/sinatra/simple-openshift-sinatra-sti image
I0702 05:36:50.733157       1 sti.go:99] Pushing 172.30.133.153:5000/sinatra/simple-openshift-sinatra-sti image ...
I0702 05:39:46.967064       1 sti.go:103] Successfully pushed 172.30.133.153:5000/sinatra/simple-openshift-sinatra-sti



----

. Make sure to check the progress on the web console.

=== Create Your First Image (Sinatra)

. After your build is complete, to verify your pod and service, run the following:
+
----

[andrew@master00 ~]$ curl `oc get services | grep sin | awk '{print $4":"$5}' | awk -F'/' '{print $1}'`
Hello, Sinatra!

----

. Your last step is to add a route to make the application publicly accessible. To do this, run the following:
+
----

[andrew@master00 ~]$ oc expose service simple-openshift-sinatra \
  --hostname=mysinatra.cloudapps-${guid}.oslab.opentlc.com



[andrew@master00 ~]$ oc get routes
NAME                       HOST/PORT                                        PATH      SERVICE                    LABELS
simple-openshift-sinatra   mysinatra.cloudapps-f4fc.oslab.opentlc.com             simple-openshift-sinatra

[andrew@master00 ~]$ curl http://mysinatra.cloudapps-${guid}.oslab.opentlc.com
Hello, Sinatra!
----

=== Using the Web Console

. Using what you learned in this chapter, create an application using the Web Console and the command line.
.. Create a project called "nodejs"
.. The Application repository is link:https://github.com/openshift/nodejs-ex[https://github.com/openshift/nodejs-ex]
.. Use the "nodejs:0.10" image
.. Create a route and expose the service to the world under the name : http://nodejs.cloudapps-GUID.oslab.opentlc.com/
... Try to explore the *oc edit route* command
.. Make sure Application has 4 replicas.

NOTE: At this point the web console can create a local route. To create an external route use the *oc expose* command or edit the existing route with *oc edit route*
