:noaudio:

ifdef::revealjs_slideshow[]

[#cover,data-background-image="image/1156524-bg_redhat.png" data-background-color="#cc0000"]
== &nbsp;

[#cover-h1]
Red Hat OpenShift Enterprise Implementation

[#cover-h2]
Introduction to Course and Learning Environment

[#cover-logo]
image::{revealjs_cover_image}[]

endif::[]



== Course Goals

* Review the OSE3.0 Architecture
* Describe and Review the different components of OSE3.0
* Describe OpenShift Enterprise installation and configuration process.
** Including: Scheduling (Placement), Persistent Storage and Authentication
* Describe and review an Application's lifecycle (Deployment lifecycle)
* Review Management of security restrictions and capabilities in OSE3.0


ifdef::showscript[]

=== Transcript

Welcome to the OpenShift Enterprise Implementation course.

The goal of this course is to show you how to set up and configure various
aspects of the OpenShift 3.0 Enterprise environment, including the following:
* The Installation process, Scheduling (Placement of pods), Persistent Storage
and Authentication to the OSE3.0 environment.
* We will also review how applications and deployments are managed and how
security restrictions and permissions can be applied.

endif::showscript[]


== Course Overview

* Module 01 : Introduction to Course and Learning Environment
* Module 02 : OpenShift Enterprise 3.0 Architecture
* Module 03 : OpenShift Enterprise 3.0 Installation
* Module 04 : Core Concepts
* Module 05 : Resource Management
* Module 06 : Creating Applications
* Module 07 : Tempaltes
* Module 08 : Deployment Lifecycle
* Module 09 : Managing Security


ifdef::showscript[]

=== Transcript

During the course you will learn the following modules, each module will
introduce you to new topics and review, in depth, previously described topics.

endif::showscript[]



== Assumptions

* You want to learn how to use OpenShift Enterprise 3.0.
* You know how to use Red Hat Enterprise Linux 7.
* You can read and modify some form of code.
* You have a workstation you can use for this training.
* You have an SSH client installed on your workstation.
* You have completed OpenShift 3.x FASTRAX training and all it's labs.


ifdef::showscript[]

=== Transcript

If you are taking this course, the assumption is that you want to learn how to
use OpenShift Enterprise and that you have completed OpenShift 3 FASTRAX
training and all it's labs.
It is also assumed that you can write some form of code, and that you have a
workstation with an SSH client installed.

endif::showscript[]



== Class Environment

* An HTML version of this content is available:
https://www.opentlc.com/classes/ose3-implementation.

* Class labs and demonstrations require provisioning the following virtual machines:
** *Master host* – 1 VM that serves as the Master for the OpenShift Enterprise environment.
** *Node hosts* – 3 VMs that serve as the nodes of the OpenShift Enterprise environment.
** *oselab host* – 1 VM for admin purposes such as: DNS Server, NFS Server,
SSH "Jumpbox" and more.
* Red Hat Enterprise Linux 7.1 is preinstalled and configured for deployment.
* Connection details arrive via email after you provision the environment.


ifdef::showscript[]

=== Transcript

This class uses a cloud-based environment. You will provision the following
hosts for your OpenShift Enterprise environment: A single Master host, three
Node hosts (One will be dedicated for Infrastructure components), and an admin
host to act as our DNS Server, NFS Server and SSH "Jumpback"

Red Hat Enterprise Linux is preinstalled and configured for deployment.

After you provision the environment, you should receive connection details via
email. This can take a few minutes, check your spam folder if you do not receive
the email within 10 minutes of environment provisioning request.


endif::showscript[]


== Connection Details
.Master and Infranode Hosts
[options="header",width="65"]
|=======================
||Master00|InfraNode00
|*Internal IP*|192.168.0.100|192.168.0.101
|*External IP*|Provided|Provided
|*DNS Name*|master00-*GUID*.oslab.opentlc.com|infranode00-*GUID*.oslab.opentlc.com
|*Credentials*|root / r3dh4t1!|root / r3dh4t1!
|=======================

ifdef::showscript[]

=== Transcript
Tables 1, 2, and 3 show the connection details to use when setting up and
connecting to the lab environment. This information is repeated in the labs as
required.

External IPs are provided by the lab provisioning email that is sent to you
after you provision the lab from 'labs.opentlc.com'.

The text *GUID* shown here is a 4-character generated unique identifier assigned
to your lab environment. Your GUID is provided in the provisioning email as well.

The *Master* host is used to manage the state of the OpenShift cluster/environment, it
hosts the web console and the API endpoint.

The *InfraNode* host is a regular node to host "pods" and "containers" but we
will use it only for infrastructure related applications (such as the router and
  Docker registry)





endif::showscript[]




== Connection Details

.Node Hosts
[options="header",width="65"]
|=======================
||Node00|Node01
|*Internal IP*|192.168.0.200|192.168.0.201
|*External IP*|Provided|Provided
|*DNS Name*|node00-*GUID*.oslab.opentlc.com|node01-*GUID*.oslab.opentlc.com
|*Credentials*|root / r3dh4t1!|root / r3dh4t1!
|=======================

ifdef::showscript[]

=== Transcript
The Node servers are used to run user's "pods" and "applications", note that the
nodes are completely blocked (firewalled) from external access.

endif::showscript[]



== Connection Details
.Administration and Support Host
[options="header",cols ="1,4",width="65"]
|=======================
||oselab
|*Internal IP*|192.168.0.200
|*External IP*|Provided
|*DNS Name*|oselab-*GUID*.oslab.opentlc.com
|*Credentials*|OpenTLC Credentials
|=======================

ifdef::showscript[]

When connecting to your environment use only your OPENTLC credentials and SSH
key to connect directly into your administration VM. Do not use root or try to
connect directly to the Master or nodes.
Your administration VM (oselab) can be used as a "jump box" to connect via SSH
to the other internal lab hosts.

endif::showscript[]
