:noaudio:

ifdef::revealjs_slideshow[] 

[#cover,data-background-image="image/1156524-bg_redhat.png" data-background-color="#cc0000"] 
== &nbsp;

[#cover-h1] 
Red Hat OpenShift Enterprise Implementation

[#cover-h2] 
Introduction to Course and Learning Environment

[#cover-logo] 
image::{revealjs_cover_image}[] 

endif::[]



:scrollbar:
:data-uri:
== Course Goals

* Explain  with the technical architecture of OSE3.0
* Perform a 20 minute demonstration of the use of OSE3.0
* Explain how to set up STI build process 
* Explain how to implement Zones and Regions in multi node environments  
* Explain how to deploy a POC like environment of OpenShift 3.0
* Explain how HA application deployments work in OpenShift 3.0 
* Explain how to Manage the life cycle of applications in OpenShift 3.0   

ifdef::showscript[]

=== Transcript


Welcome to the OpenShift Enterprise Implementation course.

The goal of this course is to show you how to set up and configure various aspects of the OpenShift 3.0 Enterprise environment, including the following: 
* The Installation process 
* The Source to Image process  
* Configuring the Scheduler to implement Zones and Regions in a multi node environment
* Create and maintain InstantApps (Templates) in OpenShift.
* Manage life cycle of an application


endif::showscript[]


:scrollbar:
:data-uri:
== Course Overview

Module 01 : Introduction to Course and Learning Environment
Module 02 : OpenShift 3.0 Architecture  
Module 03 : OpenShift 3.0 Installation
Module 04 : Resource Management
Module 05 : The STI Build Method
Module 06 : Quickstarts
Module 07 : Demonstrating OpenShift 3.0 Capabilities


ifdef::showscript[]

=== Transcript


endif::showscript[]



:scrollbar:
:data-uri:
== Assumptions

* You want to learn how to use OpenShift Enterprise 3.0.
* You know how to use Red Hat Enterprise Linux 7.
* You can read and modify some form of code.
* You have a workstation you can use for this training.
* You have an SSH client installed on your workstation.
* You have completed OpenShift 3.x FASTRAX training and all its labs.


ifdef::showscript[] 

=== Transcript


If you are taking this course, the assumption is that you want to learn how to use OpenShift Enterprise and that you have completed OpenShift 3 FASTRAX training and all it's labs. 
It is also assumed that you can write some form of code, and that you have a workstation with an SSH client installed.


endif::showscript[]



:scrollbar:
:data-uri:
== Class Environment


* Class related content found at https://www.opentlc.com/classes/ose_implementation.
* Class labs and demonstrations require provisioning the following virtual machines:
** *Master host* – VM that serves as the Master for the OpenShift Enterprise environment.
** *Node hosts* – VMs that serve as the nodes of the OpenShift Enterprise environment.
** *oselab host* – VM for repositories, files, SSH "Jumpbox," and other services.
* Red Hat Enterprise Linux 7.1 is preinstalled and configured for deployment.
* Connection details arrive via email after you provision the environment.



ifdef::showscript[] 

=== Transcript

This class uses a cloud-based environment. You will provision the following hosts for your OpenShift Enterprise environment: A single Master host, two Node hosts, and an admin host for repositories, files, and other services.

Red Hat Enterprise Linux is preinstalled and configured for deployment.

After you provision the environment, you should receive connection details via email.


endif::showscript[]


:scrollbar:
:data-uri:
== Connection Details
.Master Hosts
[options="header",width="65"]
|=======================
||Master00|Master01
|*Internal IP*|192.168.0.100|192.168.0.101
|*External IP*|Provided|Provided
|*DNS Name*|master00-*GUID*.oslab.rhpds.opentlc.com
|*Credentials*|root / r3dh4t1!|root / r3dh4t1!
|=======================





ifdef::showscript[]

=== Transcript
Tables 1, 2, and 3 show the connection details to use when setting up and connecting to the lab environment. This information is repeated in the labs as required.

External IPs are provided by the lab provisioning email that is sent to you after you provision the lab from 'labs.opentlc.com'. 

The text *GUID* shown here is a 4-character generated unique identifier assigned to your lab environment. Your GUID is provided in the provisioning email as well.

When connecting to your evironment use only your OPENTLC credentials and SSH key to connect directly into your administration VM. Do not use root or try to connect directly to the Master or nodes. 
Your administration VM can be used as a "jump box" to connect via SSH to the other internal lab hosts. 



endif::showscript[]




:noaudio:
:scrollbar:
:data-uri:
== Connection Details

.Node Hosts
[options="header",width="65"]
|=======================
||Node00|Node01
|*Internal IP*|192.168.0.200|192.168.0.201
|*External IP*|Provided|Provided
|*DNS Name*|node00-*GUID*.oslab.rhpds.opentlc.com|node01-*GUID*.oslab.rhpds.opentlc.com
|*Credentials*|root / r3dh4t1!|root / r3dh4t1!
|=======================

ifdef::showscript[]

endif::showscript[]



:noaudio:
:scrollbar:
:data-uri:
== Connection Details
.Administration and Support Host
[options="header",cols ="1,4",width="65"]
|=======================
||oselab
|*Internal IP*|192.168.0.200
|*External IP*|Provided
|*DNS Name*|oselab-*GUID*.oslab.rhpds.opentlc.com
|*Credentials*|OpenTLC Credentials
|=======================

ifdef::showscript[]

endif::showscript[]


