
:noaudio:
== Class Environment


* Class related content found at https://www.opentlc.com/classes/ose_implementation.
* Class labs and demonstrations require provisioning the following virtual machines:
** *Master host* – VM that serves as the Master for the OpenShift Enterprise environment.
** *Node hosts* – VMs that serve as the nodes of the OpenShift Enterprise environment.
** *oselab host* – VM for repositories, files, SSH "Jumpbox," and other services.
* Red Hat Enterprise Linux 7.1 is preinstalled and configured for deployment.
* Connection details arrive via email after you provision the environment.



ifdef::showscript[] 

=== Transcript

This class uses a cloud-based environment. You will provision the following hosts for your OpenShift Enterprise environment: A single Master host, two Node hosts, and an admin host for repositories, files, and other services.

Red Hat Enterprise Linux is preinstalled and configured for deployment.

After you provision the environment, you should receive connection details via email.


endif::showscript[]

