== Connection Details
:noaudio:


.Master and Infranode Hosts
[options="header",width="65"]
|=======================
||Master00|InfraNode00
|*Internal IP*|192.168.0.100|192.168.0.101
|*External IP*|Provided|Provided
|*DNS Name*|master00-*GUID*.oslab.opentlc.com|infranode00-*GUID*.oslab.opentlc.com
|*Credentials*|root / r3dh4t1!|root / r3dh4t1!
|=======================

ifdef::showscript[]

=== Transcript
Tables 1, 2, and 3 show the connection details to use when setting up and
connecting to the lab environment. This information is repeated in the labs as
required.

External IPs are provided by the lab provisioning email that is sent to you
after you provision the lab from 'labs.opentlc.com'.

The text *GUID* shown here is a 4-character generated unique identifier assigned
to your lab environment. Your GUID is provided in the provisioning email as well.

The *Master* host is used to manage the state of the OpenShift cluster/environment, it
hosts the web console and the API endpoint.

The *InfraNode* host is a regular node to host "pods" and "containers" but we
will use it only for infrastructure related applications (such as the router and
  Docker registry)





endif::showscript[]
