== Connection Details
:noaudio:

.Master and Infranode Hosts

* Details for master and infranode hosts
+
[cols="3",width="65%"]
|=======================
||Master00|InfraNode00
|*Internal IP*|`192.168.0.100`|`192.168.0.101`
|*External IP*|Provided|Provided
|*DNS Name*|+master00-**GUID**.oslab.opentlc.com+|+infranode00-**GUID**.oslab.opentlc.com+
|*Credentials*|`root`/`r3dh4t1!`|`root`/`r3dh4t1!`
|=======================

ifdef::showscript[]

=== Transcript

The tables on the next three slides show the connection details to use when
setting up and connecting to the lab environment. This information is repeated
in the labs as required.

External IPs are provided by the lab provisioning email you receive after you
provision the lab from `labs.opentlc.com`.

You use the master host to manage the state of the OpenShift cluster/environment.
 It hosts the web console and the API endpoint.

The infranode host is a regular node to host _pods_ and _containers_.
In this training it is used for infrastructure-related applications such as the
 router and Docker registry.

The `GUID` is a four-character generated unique identifier assigned to your lab environment. The provisioning email also provides your GUID.


endif::showscript[]
