:scrollbar:
:data-uri:
:icons: images/icons
:toc2:

== Set Up Lab Environment

:numbered:
== Provision Your Lab Environment

To do the labs in this training, you must provision the lab environment, which provides access to an environment with all the components required to perform the labs. 

. Go to https://labs.opentlc.com and use your credentials to log in to the OPENTLC labs provisioning system, which is built on top of Red Hat CloudForms to provide a self-service portal.
+
[TIP]
If you forgot your username or password, go to https://www.opentlc.com/pwm to reset your password or obtain a user name reminder. 

. Navigate to *Services* -> *Catalogs* -> *All Services* -> *OPENTLC Cloud Infrastructure Labs*.

. On the left side of the screen, locate *OpenShift Enterprise 3.0 Implementation Lab* and click  *Order*  (appears on the right).

. Click *Submit* (in the lower right) to order your environment. 
+
In a few minutes you receive an email describing how to connect to the environment.

. Wait about 20 minutes to allow your environment to build. 
+
The environment includes the following entities:

- One host for the broker 
- Two hosts for nodes
- One administration host for connection into the environment and miscellaneous tasks
- IPA identity management

[WARNING] 
Do not select *App Control* -> *Start* after ordering the lab. The lab is already starting. Selecting *Start* may corrupt the lab environment or cause other complications. You can select *Status* to receive an email with the status of your environment.

[NOTE]
The lab environment is cloud based, so you can access it over the WAN from anywhere. Do not, however, expect performance to match a bare-metal environment.


== Set Up SSH

To access any of your lab systems via SSH, you must use your personal OPENTLC SSO user name and public SSH key. Unless otherwise noted, you cannot use SSH to connect directly as `root`.

[NOTE]
If you have not already done so, you must provide a public SSH key.

. Go to https://www.opentlc.com/update and log in.  

. Paste your public key in that location.

. Connect to your administration host via SSH using your OPENTLC username and private SSH key:
+
.Example using UNIX/Linux
[subs="verbatim,macros"]
----
ssh -i ~/.ssh/yourprivatekey.key opentlc-username.com@oselab-pass:quotes[*GUID*].oslab.opentlc.com
----
+
[NOTE]
The text *GUID* is a 4-character unique identifier generated for your lab environment. Your GUID is at the top of the lab provisioning email.  If using windows, you will use a terminal program such as putty not the above command.
+
[NOTE]
For more information on using SSH and keys, see link:https://www.opentlc.com/ssh.html[https://www.opentlc.com/ssh.html]

. Become the root user on the administration host:
+
[subs="verbatim,macros"]
----
-bash-4.2$ sudo -i
----

. From the administraion host, make sure you can SSH to each of your provisioned hosts (192.168.0.100, 192.168.0.200, 192.168.0.201):
+
[subs="verbatim,macros"]
----
[root@oselab-GUID ~]# ssh root@192.168.0.X
----
+
[NOTE]
If prompted for a password, remember the root password is *r3dh4t1!*.

:numbered!:

