== Projects and Users
:noaudio:

.Users and User Types

* Interaction with OpenShift Enterprise associated with _user_
* OpenShift Enterprise user object represents _actor_
** May grant system permissions by adding roles to actors or groups
* User types:

[.noredheader,cols="2,3"]
|===================================================================
a|.Regular Users
* Way most interactive OpenShift Enterprise users are represented
* Created automatically in system upon first login, or via API
* Represented with `User` object
a|.System Users
* Many created automatically when infrastructure defined
* Let infrastructure interact with API securely
* Include:
** Cluster administrator with access to everything
** Per-node user
** Users for use by routers and registries
** Various others
** Anonymous system user
*** Used by default for
unauthenticated requests
*** Examples: `system:admin`, `system:openshift-registry`, `system:node:node1.example.com`
|===================================================================

ifdef::showscript[]

=== Transcript

Interaction with OpenShift Enterprise is associated with a _user_.

An OpenShift Enterprise user object represents an _actor_. You can grant permissions to actors in the system by adding roles to them or to their groups.

Among the user types that can exist are regular users and system users.

Regular users are how most interactive OpenShift Enterprise users are represented. Regular users are created automatically in the system upon first login, or you can create them via the API. Regular users are represented with the `User` object.

Most system users are created automatically when the infrastructure is defined, mainly for the purpose of enabling the infrastructure to interact with the API securely.

System users include a cluster administrator, who has access to everything; a per-node user; users for use by routers and registries; and various others.

There is also an anonymous system user that is used by default for unauthenticated requests. Examples include `system:admin`, `system:openshift-registry`, and `system:node:node1.example.com`.

endif::showscript[]

