== Client tool authentication
:noaudio:

* Every user must authenticate in some way in order to access OpenShift.
API requests with no authentication or invalid authentication are authenticated
as requests by the anonymous system user. Once authenticated, policy determines
what the user is authorized to do.

.Web Console Authentication

* When accessing the web console from a browser at `_<master-public-addr>_:8443`,
you are automatically redirected to a login page.

* You can provide your login credentials on this page to obtain a token to make
API calls. After logging in, you can navigate your projects using the web
console.


ifdef::showscript[]

=== Transcript
Every user must authenticate in some way in order to access OpenShift.
API requests with no authentication or invalid authentication are authenticated
as requests by the anonymous system user. Once authenticated, policy determines
what the user is authorized to do.

You can access the Web Console on the OSE Master's public IP on port 8443.

You can provide your login credentials on to obtain a token to make
API calls. After logging in, you can navigate your projects using the web
console.

endif::showscript[]

