== Client Tool Authentication

* Every user must authenticate to access OpenShift Container Platform
* Requests lacking valid authentication authenticated as anonymous system user
* Policy determines what user is authorized to do

.Web Console Authentication

* Access web console at `_<master-public-addr>_:8443` (By default)
* Automatically redirected to login page
* Provide login credentials to obtain token to make API calls
* Use web console to navigate projects


ifdef::showscript[]

=== Transcript

Every user must authenticate in some way to access OpenShift Container Platform. API
 requests that lack valid authentication are authenticated as requests by an
  anonymous system user. Once you authenticate, policy determines what you are
   authorized to do.

You can access the web console on the OpenShift Container Platform master's public IP on
 port 8443. The system automatically redirects you to the login page.

You provide your login credentials to obtain a token to make API calls. After
 you log in, you use the web console to navigate through your projects.

endif::showscript[]
