== Client Tool Authentication


.CLI Authentication
* Download client from Red Hat Product Downloads:
link:https://access.redhat.com/downloads/[https://access.redhat.com/downloads/]
* After extracting software, use `oc login` to authenticate from command line:
+
----
$ oc login -u andrew --server="https://master09-c3po.oslab.opentlc.com:8443"
----

* Command's interactive flow helps establish session to OpenShift Enterprise
 server with provided credentials

* Example: Authenticate as OpenShift Enterprise cluster administrator (usually `root` user):
+
----
$ oc login -u system:admin -n openshift
----
+
** You set username and _project_ (_namespace_) to log in to


ifdef::showscript[]

=== Transcript

You can download the CLI client from Red Hat Product Downloads.

After you extract the software, you can authenticate from the command line using
 the CLI command `oc login`.

The command's interactive flow helps you establish a session to an OpenShift
 Enterprise server with the provided credentials.

Note that you set the user name and the _project_ (_namespace_) to log in to by
 using the "-n" flag

endif::showscript[]
