== Client tool authentication
:noaudio:

.CLI Authentication
* You can download the client from
link:https://access.redhat.com/downloads/content/290/ver=3.0.0.0/rhel---7/3.0.1.0/x86_64/product-downloads[Red Hat Product Downloads]
* Once you extracted the software, you can authenticate from the command line
using the CLI command `oc login`.
+
----
$ oc login -u andrew --server="https://master09-c4po.oslab.opentlc.com:8443"
----

* The command's interactive flow helps you establish a session to an OpenShift
server with the provided credentials.

* Here is a handy example, lets say we wanted to authenticate as the Openshift
Cluster Administrator (Usually root User), we could use the following:
+
----
$ oc login -u system:admin -n openshift
----
NOTE: Notice that we are setting the user name and the *project* (_namespace_)
to log in to.


ifdef::showscript[]

=== Transcript
You can download the client from Red Hat Product Downloads.

Once you extracted the software you can authenticate from the command line using
 the CLI command "oc login".

endif::showscript[]


