
:scrollbar:
:data-uri:
== Service Accounts
:noaudio:

.Enable service account authentication

* Service accounts authenticate to the API using tokens signed by a private RSA key.
* The authentication layer verifies the signature using a matching public RSA key.

* To enable service account token generation, update the
master configuration file `serviceAccountConfig` stanza to specify a
`privateKeyFile` (for signing), and a matching public key file in the
`publicKeyFiles` list:
+
----
serviceAccountConfig:
  ...
  masterCA: ca.crt <1>
  privateKeyFile: serviceaccounts.private.key <2>
  publicKeyFiles:
  - serviceaccounts.public.key <3>
  - ...
----

<1> CA file used to validate the API server's serving certificate
<2> Private RSA key file (for token signing)
<3> Public RSA key files (for token verification). If private key files are
provided, then the public key component is used. Multiple public key files can
be specified, and a token will be accepted if it can be validated by one of
the public keys. This allows rotation of the signing key, while still
accepting tokens generated by the previous signer.


ifdef::showscript[]

=== Transcript


endif::showscript[]

