:noaudio:
== Resource Quota


.Quota Enforcement: Usage Changes

* After quota created and usage statistics are up-to-date:
** Project accepts content creation
* When you create resources:
** Quota usage incremented immediately upon request
* When you delete resources:
** Quota use decremented during next full recalculation of project quota
 statistics
** May take moment to reduce quota usage statistics to their current observed
system value


ifdef::showscript[]

=== Transcript

After you create a quota and usage statistics are up-to-date, the project
 accepts the creation of new content.

When you create resources, your quota usage is incremented immediately upon the
 request to create or modify the resource. However, when you delete a resource,
  your quota use is decremented during the next full recalculation of quota
   statistics for the project. Because of this, it may take a moment for your
    quota usage statistics to be reduced to their current observed system value
     when you delete resources.

endif::showscript[]
