
:scrollbar:
:data-uri:
== Service Accounts
:noaudio:

.Managed service accounts

* Service accounts are required in each project to run builds, deployments, and
other pods.
* The `managedNames` setting in the master configuration file controls which
service accounts are automatically created in every project:
+
----
serviceAccountConfig:
  ...
  managedNames: <1>
  - builder <1>
  - deployer <2>
  - default <3>
  - ...
----
<1> List of service accounts to automatically create in every project
<2> A *builder* service account in each project is required by build pods, and is given the *system:image-builder* role, which allows pushing images to any image stream in the project using the internal docker registry.
<3> A *deployer* service account in each project is required by deployment pods, and is given the *system:deployer* role, which allows viewing and modifying replication controllers and pods in the project.
<4> A *default* service account is used by all other pods unless they specify a different service account.


* All service accounts in a project are given the *system:image-puller* role,
which allows pulling images from any image stream in the project using the internal docker registry.

ifdef::showscript[]

=== Transcript


endif::showscript[]

