== Service Accounts
:noaudio:

.Usernames and Groups: Service Account Groups

* Every service account is also a member of two groups:
** `system:serviceaccounts`: Includes all service accounts in system
** `system:serviceaccounts:<project>`: Includes all service accounts in a
 specified project

* Examples:
** To allow all service accounts in all projects to view resources in
 `monitored-project`:
+
----
$ oc policy add-role-to-group view system:serviceaccounts -n monitored-project
----

** To allow all service accounts in `monitor project` to edit resources in
 `monitored-project`:
+
----
$ oc policy add-role-to-group edit system:serviceaccounts:monitor -n monitored-project
----

ifdef::showscript[]

=== Transcript

Every service account is also a member of two groups:

* `system:serviceaccounts`, which includes all service accounts in the system
* `system:serviceaccounts:<project>`, which includes all service accounts in the
 specified project.

The first example shows how to allow all service accounts in all projects to
 view resources in the `monitored-project` project.

The second example shows how to allow all service accounts in the
 `monitor project` to edit resources in the `monitored-project` project.

endif::showscript[]
