== Service Accounts
:noaudio:

.Enable Service Account Authentication

* Service accounts authenticate to API using tokens signed by private RSA key
* Authentication layer verifies signature using matching public RSA key

* To enable service account token generation, update `serviceAccountConfig` stanza to specify:
** `privateKeyFile` for signing
** Matching public key file in `publicKeyFiles` list
+
----
serviceAccountConfig:
  ...
  masterCA: ca.crt <1>
  privateKeyFile: serviceaccounts.private.key <2>
  publicKeyFiles:
  - serviceaccounts.public.key <3>
  - ...
----

ifdef::showscript[]

=== Transcript

Service accounts authenticate to the API using tokens signed by a private RSA key.
The authentication layer verifies the signature using a matching public RSA key.

To enable service account token generation, update the master configuration file's `serviceAccountConfig` stanza to specify a `privateKeyFile` for signing, and  a matching public key file in the `publicKeyFiles` list.

Note the following in the example shown here:

. This is the CA file used to validate the API server's serving certificate
. This is the private RSA key file for token signing.
. These are the public RSA key files for token verification. If the code provides private key files, then you use the public key component. You can specify multiple public key files, and a token will be accepted if one of the public keys can validate it. This allows you to rotate the signing key, while still accepting tokens generated by the previous signer.


endif::showscript[]

