== Service Accounts
:noaudio:

.Managed Service Accounts

* Service accounts required in each project
** Run builds, deployments, other pods
* `managedNames` setting in master configuration file determines service accounts automatically created in project:
+
----
serviceAccountConfig:
  ...
  managedNames: <1>
  - builder <2>
  - deployer <3>
  - default <4>
  - ...
----

* All service accounts in project given `system:image-puller` role
** Allows pulling images from any image stream in project using internal Docker registry.


ifdef::showscript[]

=== Transcript

Service accounts are required in each project to run builds, deployments, and other pods.

The `managedNames` setting in the master configuration file controls which service accounts are automatically created in every project. The `builder`, `deployer`, and `default` service accounts are created for each project automatically and given permissions to do their roles.

Note the following regarding the example shown here:

. This is the list of service accounts to automatically create in every project.
. Build pods require a `builder` service account. This service account is given the `system:image-builder` role, which allows pushing images to any image stream in the project using the internal Docker registry.
. Deployment pods require a `deployer` service account in each project. This service account is given the `system:deployer` role, which allows viewing and modifying replication controllers and pods in the project.
. All other pods use a `default` service account unless they specify a different service account.

All service accounts in a project are given the `system:image-puller` role, which allows pulling images from any image stream in the project using the internal Docker registry.


endif::showscript[]


