== Routes

.Creating Routes With the Command Line

* Can create routes using:
** API call
** Object definition file (YAML, JSON)
** CLI tool

* Example: Use CLI to create route with hostname exposing service
 `hello-service`:
+
[source,bash]
----
$ oc expose service hello-service --hostname=hello-openshift.cloudapps-r2d2.oslab.opentlc.com
NAME            HOST/PORT                                 PATH      SERVICE         LABELS
hello-service   hello-openshift-r2d2.oslab.opentlc.com             hello-service
----

* To display `routes` in current project:
+
----

$ oc get routes
NAME                    HOST/PORT                                          SERVICE                   LABELS
hello-openshift-route   hello-openshift.cloudapps-r2d2.oslab.opentlc.com   hello-openshift-service

----

ifdef::showscript[]

=== Transcript

You can create `routes` using an API call, an object definition file such as
 YAML or JSON, or the CLI tool.

The first example shows how you can use the CLI to create a route with a
 hostname that exposes a service called `hello-service`.

As you can see,  you use the `oc expose` command to create a `route` for
 external access to your `service` Note that the route routes directly to the
  pods, not to the `service`. The route gets the pod connection details from
   the service.

The second example shows how to display the `routes` in your current project.

endif::showscript[]
