== Routes


.Secured TLS Termination Types: Edge Termination Route Definition

[source,yaml]
----
apiVersion: v1
kind: Route
metadata:
  name: route-edge-secured
spec:
  host: www.example.com
  to:
    kind: Service
    name: service-name
  tls:
    termination: edge            <1>
    key: |-                      <2>
      BEGIN PRIVATE KEY
      [...]
      END PRIVATE KEY
    certificate: |-              <3>
      BEGIN CERTIFICATE
      [...]
      END CERTIFICATE
    caCertificate: |-            <4>
      BEGIN CERTIFICATE
      [...]
      END
----

<1> `termination` field is `edge` for edge termination.
<2> `key` field is contents of PEM format key file
<3> `certificate` field is contents of PEM format certificate file
<4> An optional CA certificate may be required to establish certificate chain
 for validation

ifdef::showscript[]

=== Transcript

Here is an example of a secured route definition using edge termination.

Note the following:

. The `termination` field is `edge` for edge termination.
. The `key` field is the contents of the PEM format key file.
. The `certificate` field is the contents of the PEM format certificate file.
. An optional CA certificate may be required to establish a certificate chain
 for validation.

Because TLS is terminated at the router, connections from the router to the endpoints over the internal network are not encrypted.

endif::showscript[]
:noaudio:
