== Routes


.Secured TLS Termination Types: Re-encryption Termination Route Definition

[source,yaml]
----
apiVersion: v1
kind: Route
metadata:
  name: route-pt-secured
spec:
  host: www.example.com
  to:
    kind: Service
    name: service-name
  tls:
    termination: reencrypt        <1>
    key: [as in edge termination]
    certificate: [as in edge termination]
    caCertificate: [as in edge termination]
    destinationCaCertificate: |-  <2>
      BEGIN CERTIFICATE
      [...]
      END CERTIFICATE
----

<1> `termination` field is set to `reencrypt`
** Other fields are same as edge termination
<2> Optional `destinationCaCertificate` field specifies CA certificate to
 validate endpoint certificate, which secures connection from router to destination

ifdef::showscript[]

=== Transcript

Here is an example of a secured route definition using re-encryption termination.

Note the following:

. The `termination` field is set to `reencrypt`. Other fields are the same as in
 edge termination.
. Optionally, the `destinationCaCertificate` field specifies a CA certificate to
 validate the endpoint certificate, securing the connection from the router to
  the destination.

endif::showscript[]
:noaudio:
