
:scrollbar:
:data-uri:
== Concepts

=== BuildConfig

* The BuildConfig object is the definition of the entire build process. It consists of the following elements:
** triggers: Define policies used for automatically invoking builds.
*** GitHub webhooks: GitHub specific webhooks that specify which repository changes, such as a new 	commit, should invoke a new build. This trigger is specific to the GitHub API.
*** generic webhooks: Similar to GitHub webhooks in that they invoke a new build whenever it gets a notification. The difference is its payload is slightly different than GitHub’s.
*** image change: Defines a trigger which is invoked upon availability of a new image in the specified ImageRepository.
** parameters
*** source: Describes the SCM used to locate the sources. Currently only supports Git.
*** strategy: Describes which build type is invoked along with build type specific details.
*** output: Describes the resulting image name, tag, and registry to which the image should be pushed.




ifdef::showScript[]

=== Transcript

* The BuildConfig object is the definition of the entire build process. It consists of the following elements: the triggers who define policies used for automatically invoking builds and the parameters who will point OpenShift to your source code and builder image.


endif::showScript[]




