
:scrollbar:
:data-uri:
== Modify Application Environment
:noaudio:

.Command Output

* The `new-app` command generates OpenShift resources that will build, deploy,
and run the application being created. Normally, these resources are created in
the current project using names derived from the input source repositories or
the input images. However, `new-app` allows you to modify this behavior.

* Output Without Creation
To see a dry-run of what `new-app` will create, you can use the `-o|--output`
flag with a value of either `yaml` or `json`. You can then use the output to
preview the resources that will be created, or redirect it to a file that you
can edit and then use with `oc create` to create the OpenShift resources.

* To Output `new-app` Artifacts to a File, Edit Them, Then Create Them Using `oc create`:
+
----
$ oc new-app https://github.com/openshift/ruby-hello-world -o json > myapp.json
$ vi myapp.json
$ oc create -f myapp.json
----


ifdef::showscript[]

=== Transcript

endif::showscript[]


