== Authentication
:noaudio:

.Users and Groups


* A _user_ in OpenShift is an entity that can make requests to the OpenShift API.
Typically, this represents the account of a developer or administrator that is
interacting with OpenShift.

* A user can be assigned to one or more _groups_, each of which represent a
certain set of users.
* Groups are useful when
link:https://docs.openshift.com/enterprise/3.0/admin_guide/manage_authorization_policy.html[managing authorization
policies] to grant permissions to multiple users at once, for example allowing
access to link:https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/overview.html[objects] within a
link:https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/projects_and_users.html#projects[project], versus granting
them to users individually.

NOTE: Support for developers and administrators to define their own custom groups is
currently under active development. At this time, the only groups that exist are
system groups, or _virtual groups_, that are automatically provisioned by
OpenShift. These can be seen when
link:https://docs.openshift.com/enterprise/3.0/admin_guide/manage_authorization_policy.html#viewing-cluster-bindings[viewing
cluster bindings].

In the default set of virtual groups, note the following in
particular:

[cols="2,5",options="header"]
|===

|Virtual Group |Description

|*system:authenticated* |Automatically associated with any currently-authenticated users.
|*system:unauthenticated* |Automatically associated with any currently-unauthenticated users.

|===

ifdef::showscript[]
=== Transcript

endif::showscript[]

