== Authentication
:noaudio:

.API Authentication

* Requests to the OpenShift API are authenticated using the following methods:

** OAuth Access Tokens::
- Obtained from the OpenShift OAuth server using the `_<master>_/oauth/authorize` and `_<master>_/oauth/token` endpoints.
- Sent as an `Authorization: Bearer+++...+++` header or an `access_token=+++...+++` query parameter

** X.509 Client Certificates:
*** Requires a HTTPS connection to the API server.
*** Verified by the API server against a trusted certificate authority bundle.
*** The API server creates and distributes certificates to controllers to authenticate themselves.

NOTE: Any request with an invalid access token or an invalid certificate is rejected
by the authentication layer with a 401 error.

NOTE: If no access token or certificate is presented, the authentication layer assigns
the `system:anonymous` virtual user and the `system:unauthenticated` virtual
group to the request. This allows the authorization layer to determine which
requests, if any, an anonymous user is allowed to make.

ifdef::showscript[]
=== Transcript

endif::showscript[]

