== Lab: Allow User to run Priviledges container

=== Authenticate to OpenShift Enterprise and Choose Your Project

. Connect to the OpenShift Enterprise master by following the same steps you used previously.
. Authenticate user `marina` to Openshift Enterprise
+
----

[root@master00 ~]# su - marina
[marina@master00 ~]$ guid=`hostname|cut -f2 -d-|cut -f1 -d.`
[marina@master00 ~]$ oc login -u marina --insecure-skip-tls-verify --server=https://master00-${guid}.oslab.opentlc.com:8443

----
+
You will See
+
----
Password: (Enter r3dh4t1!)
Login successful.
Welcome to OpenShift! See 'oc help' to get started.
----

. Create a project to work in:
+
----
[marina@master00 ~]$ oc new-project managesecurity-lab

----
=== Create the Privileged Pod Definition

. Run the following command to create the `hello-pod-priv.json` file:
. Note the setting : "privileged": true"
----

[marina@master00 ~]$ cat <<EOF > hello-pod-priv.json
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "hello-openshift",
    "creationTimestamp": null,
    "labels": {
      "name": "hello-openshift"
    }
  },
  "spec": {
    "containers": [
      {
        "name": "hello-openshift",
        "image": "openshift/hello-openshift:v0.4.3",
        "ports": [
          {
            "containerPort": 8080,
            "protocol": "TCP"
          }
        ],
        "resources": {
          "limits": {
            "cpu": "10m",
            "memory": "16Mi"
          }
        },
        "terminationMessagePath": "/dev/termination-log",
        "imagePullPolicy": "IfNotPresent",
        "capabilities": {},
        "securityContext": {
          "capabilities": {},
          "privileged": true
        },
        "nodeSelector": {
          "region": "primary"
        }
      }
    ],
    "restartPolicy": "Always",
    "dnsPolicy": "ClusterFirst",
    "serviceAccount": ""
  },
  "status": {}
}

EOF

----

. Try (and fail) to create the pod from the `hello-pod-priv.json`definition file
+
----
[marina@master00-GUID ~]$ oc create -f hello-pod-priv.json
Error from server: Pod "hello-openshift" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.containers[0].securityContext.privileged: invalid value 'true': Privileged containers are not allowed]
----


=== Add User to Privileged SCC

. One way to  allow *marina* to deploy "Privileged" Containers is to add her to
the "privileged" *SCC* :
- as *root*, Display the available *SCCs*:
+
----
[root@master00 ~]# oc get scc
NAME         PRIV      CAPS      HOSTDIR   SELINUX     RUNASUSER
privileged   true      []        true      RunAsAny    RunAsAny
restricted   false     []        false     MustRunAs   MustRunAsRange
----

. Edit the *privileged scc*, to look similar to the example:
- Add _- marina_ at the last line of the file. (for clarity: "-<space>marina")
+
----
[root@master00 ~]# oc edit scc privileged
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
apiVersion: v1
groups:
- system:cluster-admins
- system:nodes
kind: SecurityContextConstraints
metadata:
  creationTimestamp: 2015-07-30T02:46:22Z
  name: privileged
  resourceVersion: "5104"
  selfLink: /api/v1/securitycontextconstraints/privileged
  uid: 29c38820-3665-11e5-9899-2cc260072896
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:openshift-infra:build-controller
- marina
----

=== Retry to deploy Pod

. Go back to the *marina* user, and test your new priviliges:
+
----
[marina@master00-GUID ~]$ oc create -f hello-pod-priv.json
----

* Did the pod deploy this time? (It should have).

. Lets clean up the environment and try another way of granting users permissions.
- As *marina*, Delete the Pod you created
+
----
[marina@master00-GUID ~]$ oc delete -f hello-pod-priv.json
----

. As *root*, remove *marina* from the "privileged" SCC. Remove _- marina_ from
the last line of the file:
+
----
[root@master00 ~]# oc edit scc privileged
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
apiVersion: v1
groups:
- system:cluster-admins
- system:nodes
kind: SecurityContextConstraints
metadata:
  creationTimestamp: 2015-07-30T02:46:22Z
  name: privileged
  resourceVersion: "5104"
  selfLink: /api/v1/securitycontextconstraints/privileged
  uid: 29c38820-3665-11e5-9899-2cc260072896
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:openshift-infra:build-controller

----

=== Create SCCs to allocation permissions and capabilities

It's not always desired to add users directly to the very permissive "privileged"
SCC, In this section we will create a couple of SCCs to control our users
permissions and capabilities.

. Create the *scc-ops* SCC:
- We are creating an SCC to allow specific users to run "Privileged" containers.
+
[source,yaml]
----
cat << EOF > scc-ops.yaml
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-ops
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- marina

EOF

----

NOTE: This is different than the "privileged" built-in SCC, it is more restrictive, it
doesn't allow to mount local host directories with: _allowHostDirVolumePlugin_

. After saving the file, use the *oc create* command to create the scc
+
----
[root@master00 ~] oc create -f scc-ops.yaml

----


. Check your available SCCs:
+
----

[root@master00 ~]# oc get scc
NAME         PRIV      CAPS      HOSTDIR   SELINUX     RUNASUSER
privileged   true      []        true      RunAsAny    RunAsAny
restricted   false     []        false     MustRunAs   MustRunAsRange
scc-ops      true      []        false     RunAsAny    RunAsAny

----


. Create the *scc-dev* SCC:
- This SCC is for our developer team, it allows them create docker builds that
use *any user other than root*.
- We will take another approach to achieving this, we will *oc export* the
"restricted" built-in SCC and make changed to it.

+
[source,yaml]
----
[root@master00 ~] oc export scc restricted | tee scc-dev.yaml
apiVersion: v1
groups:
- system:authenticated
kind: SecurityContextConstraints
metadata:
  creationTimestamp: null
  name: restricted
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
----

. Edit the file to look like the following:
- Delete the _groups_ section.
- Change _RunAsUser_ Type value to "*MustRunAsNonRoot*".
- Change the SCC _name_ to "*scc-dev*".
- Add the _users_ section, and make sure user *andrew* is on the list
+
[source,yaml]
----
apiVersion: v1
kind: SecurityContextConstraints
metadata:
  creationTimestamp: null
  name: scc-dev
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
users:
 - andrew
----

. After saving the file, use the *oc create* command to create the scc
+
----
[root@master00 ~] oc create -f scc-dev.yaml

----

. Check your available SCCs:
+
----
[root@master00-GUID ~]# oc get scc
NAME         PRIV      CAPS      HOSTDIR   SELINUX     RUNASUSER
privileged   true      []        true      RunAsAny    RunAsAny
restricted   false     []        false     MustRunAs   MustRunAsRange
scc-ops      true      []        false     RunAsAny    RunAsAny
scc-dev      false     []        false     MustRunAs   MustRunAsNonRoot
----

=== Test your new SCCs

. Go back to the *marina* user, and test your new priviliges:
+
----
[marina@master00-GUID ~]$ oc create -f hello-pod-priv.json
----

* Did the pod deploy this time? (It should have).
