== Lab: Allow User to run Priviledges container

=== Authenticate to OpenShift Enterprise and Choose Your Project

. Connect to the OpenShift Enterprise master by following the same steps you used previously.
. Authenticate user `marina` to Openshift Enterprise and create a token in the `.config/openshift/.config` file:
+
----

[root@master00 ~]# su - marina
[marina@master00 ~]$ guid=`hostname|cut -f2 -d-|cut -f1 -d.`
[marina@master00 ~]$ oc login -u marina --insecure-skip-tls-verify --server=https://master00-${guid}.oslab.opentlc.com:8443

----
+
You will See
+
----
Password: (Enter r3dh4t1!)
Login successful.
Welcome to OpenShift! See 'oc help' to get started.
----

. Create a project to work in:
+
----
[marina@master00 ~]$ oc new-project managesecurity-lab

----
=== Create the Privileged Pod Definition

. Run the following command to create the `hello-pod-priv.json` file:
. Note the setting : "privileged": true"
----

[marina@master00 ~]$ cat <<EOF > hello-pod-priv.json
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "hello-openshift",
    "creationTimestamp": null,
    "labels": {
      "name": "hello-openshift"
    }
  },
  "spec": {
    "containers": [
      {
        "name": "hello-openshift",
        "image": "openshift/hello-openshift:v0.4.3",
        "ports": [
          {
            "containerPort": 8080,
            "protocol": "TCP"
          }
        ],
        "resources": {
          "limits": {
            "cpu": "10m",
            "memory": "16Mi"
          }
        },
        "terminationMessagePath": "/dev/termination-log",
        "imagePullPolicy": "IfNotPresent",
        "capabilities": {},
        "securityContext": {
          "capabilities": {},
          "privileged": true
        },
        "nodeSelector": {
          "region": "primary"
        }
      }
    ],
    "restartPolicy": "Always",
    "dnsPolicy": "ClusterFirst",
    "serviceAccount": ""
  },
  "status": {}
}

EOF

----

. Try (and fail) to create the pod from the `hello-pod-priv.json`definition file
+
----
[marina@master00-312b ~]$ oc create -f hello-pod-priv.json
Error from server: Pod "hello-openshift" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.containers[0].securityContext.privileged: invalid value 'true': Privileged containers are not allowed]
----


=== Add User to Privileged SCC

. One way to  allow *marina* to deploy "Privileged" Containers is to add her to
the "privileged" *SCC* :
.. as *root*, Display the available *SCCs*:
+
----
[root@master00 ~]# oc get scc
NAME         PRIV      CAPS      HOSTDIR   SELINUX     RUNASUSER
privileged   true      []        true      RunAsAny    RunAsAny
restricted   false     []        false     MustRunAs   MustRunAsRange
----

. Edit the *privileged SSC*, to look similar to the example:
.. Add _- marina_ at the last line of the file. (for clarity: "-<space>marina")
+
----
[root@master00 ~]# oc edit scc privileged
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
apiVersion: v1
groups:
- system:cluster-admins
- system:nodes
kind: SecurityContextConstraints
metadata:
  creationTimestamp: 2015-07-30T02:46:22Z
  name: privileged
  resourceVersion: "5104"
  selfLink: /api/v1/securitycontextconstraints/privileged
  uid: 29c38820-3665-11e5-9899-2cc260072896
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:openshift-infra:build-controller
- marina
----

=== Retry to deploy Pod

. Go back to the *marina* user, and test your new priviliges:
+
----
[marina@master00-312b ~]$ oc create -f hello-pod-priv.json
----

* Did the pod deploy this time? (It should)


//Create scc_dev
//Create scc_ops

//add marina to scc ops
//* Define scc ops to allow privileged containers
//* Define scc Dev

//add andrew to scc dev
