== Authentication
:noaudio:

.Users and Groups

In the default set of virtual groups, note the following in
particular:

[cols="2,5",options="header"]
|===

|Virtual Group |Description

|*system:authenticated* |Automatically associated with any currently-authenticated users.
|*system:unauthenticated* |Automatically associated with any currently-unauthenticated users.

|===

NOTE: Support for developers and administrators to define their own custom groups is
currently under active development. At this time, the only groups that exist are
system groups, or _virtual groups_, that are automatically provisioned by
OpenShift. These can be seen when
link:https://docs.openshift.com/enterprise/3.0/admin_guide/manage_authorization_policy.html#viewing-cluster-bindings[viewing
cluster bindings].


ifdef::showscript[]
=== Transcript
In the default set of virtual groups, note the following groups in particular.

Support for developers and administrators to define their own custom groups is
currently under active development. At this time, the only groups that exist are
system groups, or _virtual groups_, that are automatically provisioned by
OpenShift.


endif::showscript[]

