== Authentication
:noaudio:

.API Authentication

* Requests to the OpenShift API are authenticated using the following methods:

** OAuth Access Tokens:
- Obtained from the OpenShift OAuth server using the
`_<master>_/oauth/authorize` and `_<master>_/oauth/token` endpoints.
- Sent as an `Authorization: Bearer+++...+++` header or an
`access_token=+++...+++` query parameter

** X.509 Client Certificates:
*** Requires a HTTPS connection to the API server.
*** Verified by the API server against a trusted certificate authority bundle.
*** The API server creates and distributes certificates to controllers to authenticate themselves.

NOTE: Any request with an invalid access token or an invalid certificate is rejected
by the authentication layer with a 401 error.

ifdef::showscript[]
=== Transcript
Requests to the OpenShift API are authenticated using the following methods:
Oauth Access Tokens and X.509 Client Certificates.

Any request with an invalid access token or an invalid certificate is rejected
by the authentication layer with a 401 error.

endif::showscript[]

