== Authentication
:noaudio:

.OAuth
* The OpenShift master includes a built-in OAuth server. Users obtain OAuth
access tokens to authenticate themselves to the API.

* When a person requests a new OAuth token, the OAuth server uses the configured
link:https://docs.openshift.com/enterprise/3.0/admin_guide/configuring_authentication.html[identity
provider] to determine the identity of the person making the request.

- It then determines what user that identity maps to, creates an access token for
that user, and returns the token for use.


NOTE: If no access token or certificate is presented, the authentication layer assigns
the `system:anonymous` virtual user and the `system:unauthenticated` virtual
group to the request. This allows the authorization layer to determine which
requests, if any, an anonymous user is allowed to make.

ifdef::showscript[]
=== Transcript
The OpenShift master includes a built-in OAuth server. Users obtain OAuth
access tokens to authenticate themselves to the API.

* When a person requests a new OAuth token, the OAuth server uses the configured
identity provider to determine the identity of the person making the request.

- It then determines what user that identity maps to, creates an access token for
that user, and returns the token for use.

endif::showscript[]

