== Configuring Authentication
:noaudio:

.Overview
* The OpenShift _master_ includes a built-in OAuth Server.
* Developers and administrators obtain _OAuth access tokens_ to authenticate
themselves to the API.

* As an administrator, you can configure _OAuth_ using a
_master configuration file_ to specify an _identity provider_.

* The _Deny All_ identity provider is used by default, which denies access for
all user names and passwords. To allow access, you must choose a different
identity provider and configure the master
configuration file appropriately (located at
*_/etc/openshift/master/master-config.yaml_* by default).

* When running a master without a configuration file, the _Allow All_ identity
provider is used by default, which allows any non-empty user name and password to log in. This is
useful for testing purposes.

ifdef::showscript[]
=== Transcript
The OpenShift _master_ includes a built-in OAuth Server.
* Developers and administrators obtain _OAuth access tokens_ to authenticate
themselves to the API.

* As an administrator, you can configure _OAuth_ using a
_master configuration file_ to specify an _identity provider_.

* The _Deny All_ identity provider is used by default, which denies access for
all user names and passwords. To allow access, you must choose a different
identity provider and configure the master
configuration file appropriately (located at
*_/etc/openshift/master/master-config.yaml_* by default).

* When running a master without a configuration file, the _Allow All_ identity
provider is used by default, which allows any non-empty user name and password
to log in. This is useful for testing purposes.

endif::showscript[]

