== Configuring Authentication
:noaudio:

.Identity Providers

* You can configure the master for authentication using your desired identity
provider by modifying the _master configuration file_.

* There are three parameters common to all identity providers:
+
[cols="2a,8a",options="header"]
|===
|Parameter     | Description
.^|`name`      | The provider name is prefixed to provider user names to form an
identity name.
.^|`challenge` | When *true*, unauthenticated token requests from non-web
clients (like the CLI) are sent a `WWW-Authenticate` challenge header. Not
supported by all identity providers.

To prevent cross-site request forgery (CSRF) attacks against browser clients
Basic authentication challenges are only sent if a `X-CSRF-Token` header is
present on the request. Clients that expect to receive Basic `WWW-Authenticate`
challenges should set this header to a non-empty value.

.^|`login`     | When *true*, unauthenticated token requests from web clients
(like the web console) are redirected to a login page backed by this provider.
Not supported by all identity providers.
|===

[[AllowAllPasswordIdentityProvider]]

ifdef::showscript[]
=== Transcript
You can configure the master for authentication using your desired identity
provider by modifying the _master configuration file_.

* There are three parameters common to all identity providers: Name, Challange
and Login.

In the next few slides we will review the different Identity Providers.

endif::showscript[]

