== Configuring Authentication
:noaudio:

.Identity Providers

* Can modify _master configuration file_ to configure master for authentication
 using desired identity provider

* Three parameters common to all identity providers:

[cols="2a,8a"]
|===
|Parameter     | Description
|`name`      | Provider name prefixed to provider usernames to form identity
 name
|`challenge` a|* When `true`, unauthenticated token requests from non-web
clients (i.e., CLI) sent `WWW-Authenticate` challenge header
* Not supported by all identity providers
* To prevent cross-site request forgery (CSRF) attacks against browser clients:
** Basic authentication challenges sent only if `X-CSRF-Token` header  present
 on request
** Clients expecting to receive basic `WWW-Authenticate` challenges should set
 header to non-empty value
|`login`     a|* When `true`, unauthenticated token requests from web clients
 (i.e., web console) redirected to login page backed by provider
* Not supported by all identity providers
|===

[[AllowAllPasswordIdentityProvider]]

ifdef::showscript[]
=== Transcript
To configure the master for authentication using your desired identity provider,
 you modify the _master configuration file_.

Three parameters are common to all identity providers:

* `name` is the provider name prefixed to provider usernames to form the
 identity name.
* When `challenge` is `true`, unauthenticated token requests from non-web
 clients such as the CLI are sent the `WWW-Authenticate` challenge header.
  Some identity providers do not support the `challenge` parameter.
   To prevent cross-site request forgery (CSRF) attacks against browser clients,
    Basic authentication challenges are sent only if the `X-CSRF-Token` header
     is present on the request. Clients expecting to receive basic
      `WWW-Authenticate` challenges should set the header to a non-empty value.
* When `login` is `true`, unauthenticated token requests from web clients such
 as the web console are redirected to the login page backed by the provider.
  Some identity providers do not support the `login` parameter.

The next few slides review the different identity providers.

endif::showscript[]
