== Configuring Authentication


.Identity Providers: Deny All

* Set `DenyAllPasswordIdentityProvider` in `identityProviders` stanza to deny
 access for all usernames/passwords
* Default identity provider when running OpenShift Enterprise with
_master configuration file_

* Master configuration using `DenyAllPasswordIdentityProvider`:
+
[source,yaml]
----
oauthConfig:
  ...
  identityProviders:
  - name: my_deny_provider <1>
    challenge: true <2>
    login: true <3>
    provider:
      apiVersion: v1
      kind: DenyAllPasswordIdentityProvider
----

. This provider name is prefixed to provider usernames to form an identity name.
. When `true`, unauthenticated token requests from non-web clients
 (like the CLI) are sent a `WWW-Authenticate` challenge header for this provider.
. When `true`, unauthenticated token requests from web clients (like the web
   console) are redirected to a login page backed by this provider.


ifdef::showscript[]
=== Transcript

You can set `DenyAllPasswordIdentityProvider` in the `identityProviders` stanza
 to deny access for all usernames and passwords.

The _Deny All_ identity provider is the default identity provider when running
 OpenShift Enterprise with a _master configuration file_.

The example here shows the master configuration using
 `DenyAllPasswordIdentityProvider`. 



endif::showscript[]
