== Configuring Authentication


//ISSUE: Bob - This could benefit from expand/collapse I think

.Identity Providers: LDAP Authentication

* Set `LDAPPasswordIdentityProvider` in `identityProviders` stanza to validate
 usernames and passwords against LDAPv3 server
** Uses simple bind authentication

* During authentication:
** LDAP directory searched for entry matching provided username
** If single unique match found, simple bind attempted using entry distinguished
 name (DN) plus password

* Authentication steps:

. To generate search filter, combine attribute and filter in configured `url`
 with user-provided username
. Search directory using filter
** If search does not return exactly one entry, deny access
. Attempt to bind to LDAP server using DN of entry retrieved from search and
 user-provided password
** If bind unsuccessful, deny access
** If bind successful, build identity using configured attributes as:
*** Identity
*** Email address
*** Display name
*** Preferred username


ifdef::showscript[]
=== Transcript

You can set `LDAPPasswordIdentityProvider` in the `identityProviders` stanza to
 validate usernames and passwords against an LDAPv3 server, using simple bind
  authentication.

During authentication, the LDAP directory is searched for an entry that matches
 the provided username. If search finds a single unique match, it attempts a
  simple bind using the distinguished name (DN) of the entry plus the provided
   password.

The authentication steps are as follows:

. Generate a search filter by combining the attribute and filter in the
 configured `url` with the user-provided username.
. Search the directory using the generated filter. If the search does not return
 exactly one entry, deny access.
. Attempt to bind to the LDAP server using the DN of the entry retrieved from
 the search and the user-provided password.
** If the bind is unsuccessful, deny access.
** If the bind is successful, build an identity using the configured attributes
 as the identity, email address, display name, and preferred username.

endif::showscript[]
