== Configuring Authentication
:noaudio:

* Master configuration using `HTPasswdPasswordIdentityProvider`:
+
[source,yaml]
----
oauthConfig:

  identityProviders:
  - name: my_htpasswd_provider <1>
    challenge: true <2>
    login: true <3>
    provider:
      apiVersion: v1
      kind: HTPasswdPasswordIdentityProvider
      file: /path/to/users.htpasswd <4>
----


ifdef::showscript[]
=== Transcript
Here is an example of the `oauthConfig` section of the master configuration file that defines the use of `HTPasswdPasswordIdentityProvider` with the file `/path/to/users.htpasswd`.

Note the following:

. This provider name is prefixed to provider usernames to form an identity name.
. When `true`, unauthenticated token requests from non-web clients (like the CLI) are sent a `WWW-Authenticate` challenge header for this provider.
. When `true`, unauthenticated token requests from web clients (like the web console) are redirected to a login page backed by this provider.
. This is the file generated using `htpasswd`.

endif::showscript[]

