== Authorization
:noaudio:

.Overview - Continued
* Rules, roles, and bindings can be visualized using the CLI. For example,
consider the following excerpt showing rule sets for the *admin* and
*basic-user* (Using the command `oc describe clusterPolicy default`):
+
[options="nowrap"]
----
admin			Verbs					Resources															Resource Names	Extension
			[create delete get list update watch]	[projects resourcegroup:exposedkube resourcegroup:exposedopenshift resourcegroup:granter secrets]				[]
			[get list watch]			[resourcegroup:allkube resourcegroup:allkube-status resourcegroup:allopenshift-status resourcegroup:policy]			[]
basic-user		Verbs					Resources															Resource Names	Extension
			[get]					[users]																[~]
			[list]					[projectrequests]														[]
			[list]					[projects]															[]
			[create]				[subjectaccessreviews]														[]		IsPersonalSubjectAccessReview
----



* The following excerpt of viewing policy bindings shows the above roles
bound to various users and groups (Using the command: `oc describe clusterPolicy default`):
+
[options="nowrap"]
----
RoleBinding[admins]:
				Role:	admin
				Users:	[alice system:admin]
				Groups:	[]
RoleBinding[basic-user]:
				Role:	basic-user
				Users:	[joe]
				Groups:	[devel]
----


ifdef::showscript[]
=== Transcript
Rules, roles, and bindings can be visualized using the CLI. For example,
consider the following excerpt showing rule sets for the *admin* and
*basic-user* (Using the command `oc describe clusterPolicy default`)

The second excerpt of viewing policy bindings shows the above roles bound to
various users and groups (Using the command:
  `oc describe clusterPolicy default`):
endif::showscript[]

