== Authorization
:noaudio:

.Visualizing Rules, Roles, and Bindings

//ISSUE: Bob - This could benefit from expand/collapse I think

* Can use CLI to visualize rules, roles, bindings
* Example: Show rule sets for `admin` and `basic-user`
** Uses `oc describe clusterPolicy default`:
+
[options="nowrap"]
----
admin			Verbs					Resources															Resource Names	Extension
			[create delete get list update watch]	[projects resourcegroup:exposedkube resourcegroup:exposedopenshift resourcegroup:granter secrets]				[]
			[get list watch]			[resourcegroup:allkube resourcegroup:allkube-status resourcegroup:allopenshift-status resourcegroup:policy]			[]
basic-user		Verbs					Resources															Resource Names	Extension
			[get]					[users]																[~]
			[list]					[projectrequests]														[]
			[list]					[projects]															[]
			[create]				[subjectaccessreviews]														[]		IsPersonalSubjectAccessReview
----



* Example: View policy bindings
** Shows above roles bound to various users/groups
** Uses `oc describe clusterPolicy default`:
+
[options="nowrap"]
----
RoleBinding[admins]:
				Role:	admin
				Users:	[alice system:admin]
				Groups:	[]
RoleBinding[basic-user]:
				Role:	basic-user
				Users:	[joe]
				Groups:	[devel]
----


ifdef::showscript[]
=== Transcript
You can use the CLI to visualize rules, roles, and bindings. The first sample here shows rule sets for the `admin` and `basic-user`, using the command `oc describe clusterPolicy default`.

The second sample views policy bindings and shows the above roles bound to various users and groups, using the command: `oc describe clusterPolicy default`.
endif::showscript[]

