== Authorization
:noaudio:

.Roles
* Roles are collections of policy _rules_, which are sets of
permitted verbs that can be performed on a set of resources.
* OpenShift includes a set of default roles that can be added to users and
groups in the _cluster policy_ or the  _local policy_. (Detailed in the next
  slide)

* These roles, including a matrix of the verbs and resources each are associated
  with, can be visualized in the cluster policy by using the CLI. Additional
  _system_ roles are listed as well, which are used for various OpenShift
  system and component operations.

NOTE: By default in a local policy, only the binding for the _admin_ role is
  immediately listed when using the CLI to _view local bindings_. However, if
  other default roles are added to users and groups within a local policy,
  they become listed in the CLI output, as well.

ifdef::showscript[]
=== Transcript
* Roles are collections of policy _rules_, which are sets of
permitted verbs that can be performed on a set of resources.
* OpenShift includes a set of default roles that can be added to users and
groups in the _cluster policy_ or the  _local policy_. (Detailed in the next
  slide)


endif::showscript[]

