== Authorization
:noaudio:

.Roles: Default Roles
* OpenShift Enterprise includes default roles
* Can add to users/groups in _cluster policy_ or _local policy_

[cols="1,4"]
|===
|Default Role |Description
|`admin` a|* Project manager
* If used in _local binding_, has rights to view any resource in project and modify any resource in project 
* Exceptions: Role creation and quota
|`basic-user` |User that can get basic information about projects and users
|`cluster-admin` a|* Super-user that can perform any action in any project
* When granted to user within local policy, user has full control over quota and roles and every action on every resource in project
|`cluster-status` |User that can get basic cluster status information
|`edit` a|* User that can modify most objects in project
* Does not have power to view or modify roles or bindings
|`self-provisioner` a|* User that can create own projects
* Default for all users
|`view` a|* User who cannot make any modifications
* Can see most objects in project
* Cannot view or modify roles or bindings
|===

* Can associate users and groups with, or bind them to, multiple roles at same time.
** Learn more: https://docs.openshift.com/enterprise/3.0/architecture/additional_concepts/authentication.html#users-and-groups

ifdef::showscript[]
=== Transcript
OpenShift Enterprise includes a set of default roles that you can add to users and groups in either the _cluster policy_ or the _local policy_.

The `admin` user is a project manager. If used in a _local binding_, an `admin` user has rights to view any resource in the project and modify
any resource in the project except for role creation and quota.

The `basic-user` is a user that can get basic information about projects they participate in and the projects' users.

The `cluster-admin` is a super-user that can perform any action in any project. When granted to a user within a local policy, this user has full control over quota and roles and every action on every resource in the project.

The `cluster-status` role lets a user get basic cluster status information.

The `edit` role lets a user modify most objects in a project, but does not give the user the power to view or modify roles or bindings.

The `self-provisioner` is a user that can create his or her own projects, All users are granted this role by default.

The `view` role prohibits a user from making any modifications but lets the user see most objects in a project. These users cannot view or modify roles or bindings.

You can associate users and groups with, or bind them to, multiple roles at same time.

endif::showscript[]

