== Authorization
:noaudio:

.Roles - Continued

* If you find that these roles do not suit you, a *cluster-admin* user can create
a `policyBinding` object named `_<projectname>_:default` with the CLI using a
JSON file.
** This allows the project *admin* to bind users to roles that are
defined only in the `_<projectname>_` local policy.


NOTE: After a product update, the recommended default roles may be updated.  To check
if an update is recommended for your environment, you can run `oadm policy reconcile-cluster-roles`.
This command will output a list of roles that are out of date and their new values.
You may either take this output, modify, and apply it yourself or you may run
`oadm policy reconcile-cluster-roles --confirm` and automatically apply the changes.



ifdef::showscript[]
=== Transcript
* If you find that these roles do not suit you, a *cluster-admin* user can create
a `policyBinding` object named `_<projectname>_:default` with the CLI using a
JSON file.
** This allows the project *admin* to bind users to roles that are
defined only in the `_<projectname>_` local policy.
endif::showscript[]

