== Authorization
:noaudio:

.Roles: Creating Roles

* If default roles unsuitable, `cluster-admin` can:
** Create `policyBinding` object named `_<projectname>_:default`
** With CLI using JSON file
* Lets project `admin` bind users to roles  defined in `_<projectname>_` local policy

* Default role may be updated after product update
* To check if update recommended for your environment, run `oadm policy reconcile-cluster-roles`
** Outputs list of out-of-date roles and new values
* Can either:
** Modify and apply output yourself
** Run `oadm policy reconcile-cluster-roles --confirm` and automatically apply changes

ifdef::showscript[]
=== Transcript
If you find that the default roles do not suit you, a `cluster-admin` user can create a `policyBinding` object named `_<projectname>_:default` with the CLI using a JSON file. This lets the project `admin` bind users to roles that are defined in the `_<projectname>_` local policy only.

After a product update, the recommended default roles may be updated.  To check if an update is recommended for your environment, you can run `oadm policy reconcile-cluster-roles`. This command outputs a list of roles that are out-of-date, along with their new values. You can either modify and apply this output yourself, or run `oadm policy reconcile-cluster-roles --confirm` and automatically apply the changes.

endif::showscript[]

