== Security Context Constraints
:noaudio:

.Overview

* In addition to _authorization policies_ that control what a user
can do, OpenShift provides _security context constraints_ (SCC) that control the
actions that a _pod_ can perform and what it has the ability to access.

* SCCs are objects that define a set of conditions that a pod must run with in
order to be accepted into the system. They allow an administrator to control the
following:

. Running of privileged containers.
. Capabilities a container can request to be added.
. Use of host directories as volumes.
. The SELinux context of the container.
. The user ID. (within the container)

ifdef::showscript[]
=== Transcript
In addition to _authorization policies_ that control what a user
can do, OpenShift provides _security context constraints_ (SCC) that control the
actions that a _pod_ can perform and what it has the ability to access.

* SCCs are objects that define a set of conditions that a pod must run with in
order to be accepted into the system. They allow an administrator to control the
following:

. Running of privileged containers.
. Capabilities a container can request to be added.
. Use of host directories as volumes.
. The SELinux context of the container.
. The user ID. (within the container)
endif::showscript[]

