== Security Context Constraints
:noaudio:

.Privileged and Restricted SCCs

* Two SCCs are added to the cluster by default, _privileged_ and _restricted_,
which are viewable by cluster administrators using the CLI:
+
----
$ oc get scc
NAME         PRIV      CAPS      HOSTDIR   SELINUX     RUNASUSER
privileged   true      []        true      RunAsAny    RunAsAny
restricted   false     []        false     MustRunAs   MustRunAsRange

----

* The privileged SCC:
** allows privileged pods.
**  allows host directories to be mounted as volumes.
**  allows a pod to run as any user.
**  allows a pod to run with any MCS label.

* The restricted SCC:
** ensures pods cannot run as privileged.
** ensures pods cannot use host directory volumes.
** requires that a pod run as a user in a pre-allocated range of UIDs.
** requires that a pod run with a pre-allocated MCS label.


ifdef::showscript[]
=== Transcript
Two SCCs are added to the cluster by default, _privileged_ and _restricted_,
which are viewable by cluster administrators using the CLI:

* The privileged SCC allows privileged pods, allows host directories to be
mounted as volumes, allows a pod to run as any user and allows a pod to run
with any MCS label.


* The restricted SCC ensures pods cannot run as privileged, ensures pods cannot
use host directory volumes, requires that a pod run as a user in a pre-allocated
 range of UIDs and requires that a pod run with a pre-allocated MCS label.

endif::showscript[]

