== Security Context Constraints
:noaudio:

.Privileged and Restricted SCCs

* The _users_ and _groups_ fields on the SCC control which SCCs can be used.
By default, cluster administrators, nodes, and the build controller are granted
access to the privileged SCC.
* All authenticated users are granted access to the restricted SCC.

* The definition for each SCC is also viewable by cluster administrators using the
CLI. For example, for the privileged SCC:
+
----
# oc export scc/privileged
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
apiVersion: v1
groups: <1>
- system:cluster-admins
- system:nodes
kind: SecurityContextConstraints
metadata:
  creationTimestamp: null
  name: privileged
runAsUser:
  type: RunAsAny <2>
seLinuxContext:
  type: RunAsAny <3>
users: <4>
- system:serviceaccount:openshift-infra:build-controller
----

<1> The groups that have access to this SCC
<2> The run as user strategy type which dictates the allowable values for the Security Context
<3> The SELinux context strategy type which dictates the allowable values for the Security Context
<4> The users who have access to this SCC

ifdef::showscript[]
=== Transcript

* The _users_ and _groups_ fields on the SCC control which SCCs can be used.
By default, cluster administrators, nodes, and the build controller are granted
access to the privileged SCC.
* All authenticated users are granted access to the restricted SCC.

* The definition for each SCC is also viewable by cluster administrators using
the CLI.
endif::showscript[]

