== Managing Security Context Constraints
:noaudio:

.Grant Access to the Privileged SCC

* In some cases, an administrator might want to allow users or groups outside
the administrator group access to create more privileged pods. To do so, you can:

* To do that Add the user or group to the users or groups field of the SCC by
using the *oc edit* command.
- For example, to allow the *e2e-user* access to the *privileged* SCC, add
the user name to the users list:
+
[source,yaml]
----
$ oc edit scc privileged

allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
apiVersion: v1
groups:
- system:cluster-admins
- system:nodes
kind: SecurityContextConstraints
metadata:
  creationTimestamp: 2015-06-15T20:44:53Z
  name: privileged
  resourceVersion: "58"
  selfLink: /api/v1/securitycontextconstraints/privileged
  uid: 602a0838-139f-11e5-8aa4-080027c5bfa9
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:openshift-infra:build-controller
- e2e-user <1>

----

<1> The *e2e-user* added to the users section.


ifdef::showscript[]
=== Transcript
* In some cases, an administrator might want to allow users or groups outside
the administrator group access to create more privileged pods. To do so, you can:

* To do that Add the user or group to the users or groups field of the SCC by
using the *oc edit* command.
In this example, We added *e2e-user* to the users list of the privileged SCC to
allow the *e2e-user* to create privileged pods.
endif::showscript[]

