== Managing SCCs
:noaudio:

.Granting Access to the Privileged SCC

* Administrator might want to create privileged pods
** Provide access to users/groups outside administrator group
** To do so, use `oc edit` to add user/group to `users` or `groups` field of SCC
** Example: To allow `e2e-user` access to `privileged` SCC, add username to
 `users` list:
+
[source,yaml]
----
$ oc edit scc privileged

allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
apiVersion: v1
groups:
- system:cluster-admins
- system:nodes
kind: SecurityContextConstraints
metadata:
  creationTimestamp: 2015-06-15T20:44:53Z
  name: privileged
  resourceVersion: "58"
  selfLink: /api/v1/securitycontextconstraints/privileged
  uid: 602a0838-139f-11e5-8aa4-080027c5bfa9
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:openshift-infra:build-controller
- e2e-user <1>

----


ifdef::showscript[]
=== Transcript
In some cases, an administrator might want to provide access to users or groups
 outside the administrator group to create more privileged pods.

To do so, you use the `oc edit` command to add the user or group to the `users`
 or `groups` field of the SCC.
In the example shown here, you add `e2e-user` to the `user` list of the
 privileged SCC to allow `e2e-user` to create privileged pods.

Note the following:

. This shows `e2e-user` added to the users section.

endif::showscript[]
