
:noaudio:

ifdef::revealjs_slideshow[]

[#cover,data-background-image="image/1156524-bg_redhat.png" data-background-color="#cc0000"]

== &nbsp;
:noaudio:

[#cover-h1]
Red Hat OpenShift Enterprise Implementation

[#cover-h2]
Templates
[#cover-logo]
image::{revealjs_cover_image}[]

endif::[]
== Module Topics

* Template Overview
* Template File Creation
* New Configuration From Template
* Processing Template Parameters

ifdef::showscript[]

=== Transcript

Welcome to module seven of the OpenShift Enterprise Implementation course.

In this module you learn about the various sections of a template; how to
 deploy, process, and modify a template;
and how to "wire" templates together.

endif::showscript[]
== Template Overview

.What Is a Template?


* Describes set of resources that can be customized and processed to produce
 configuration
* Parameterized list OpenShift Enterprise uses to create list of resources,
 including services, pods, routes, and build configurations
* Defines set of labels to apply to every resource created by template

.Reference
* https://docs.openshift.com/enterprise/latest/dev_guide/templates.html

ifdef::showscript[]

=== Transcript

A template describes a set of resources that can be customized and processed to
 produce a configuration.

Each template is a parameterized list that OpenShift Enterprise uses to create a
 list of resources, including services, pods, routes, and build configurations.

A template also defines a set of labels to apply to every resource it creates.

endif::showscript[]
== Template Overview

.What Are Templates For?

* Can create instantly deployable applications for developers or customers
* Can use preset variables or randomize values (like passwords)


ifdef::showscript[]

=== Transcript
With templates you can create instantly deployable applications for developers
 or customers.

A template can use preset variables or randomize values (like passwords).


endif::showscript[]
== Template Overview

.Template Elements

----
{
  "kind": "Template",
  "apiVersion": "v1",
  "metadata": {
    "name": "quickstart-keyvalue-application", <1>
    "creationTimestamp": null,
    "annotations": {
      "description": "This is an example of a Ruby and MySQL application on OpenShift 3", <2>
      "iconClass": "icon-ruby",
      "tags": "instant-app,ruby,mysql"

    }
  },
  "parameters": [  <3>
    {
      "name": "username"
      "value": "admin"
      "description": "administrative user"
    }
  ],
  "labels": {  <4>
    "custom_label": "Label_Name"
  },
  "objects": [  <5>
    {
      ...
    }
  ]
}

----

<1> `name`: Name of template
<2> `description`: Optional description for template
<3> `parameters`: List of parameters, like username, passwords, and others
<4> `labels`: List of labels to apply to resources created by template
<5> `object`: List of resources to create, such as pods, services, and routes


ifdef::showscript[]

=== Transcript

This sample template file is constructed from the following elements:

. `name` is the name of the template.
. `description` is an optional description for the template.
. `parameters` is where you list parameters like username, passwords, and
 others.
. `labels` is a list of labels to apply to resources created by the template.
. `object` lists resources to create, like pods, services, and routes.

endif::showscript[]
== Template Overview

.Labels

* Used to manage generated resources
* Apply to _every resource that is generated from the template_
* Used to organize, group, or select objects and resources
* Resources and pods are "tagged" with labels
* Allows services and replication controllers to:
** Indicate pods they relate to
** Reference groups of pods
** Treat pods with different Docker containers as similar entities

ifdef::showscript[]

=== Transcript

Labels are used to manage generated resources, such as pods. The labels
 specified in the template are applied to
  _every resource that is generated from the template_.

Labels are used to organize, group, or select objects and resources.

Resources and pods are "tagged" with labels, and services and replication
 controllers use the labels to indicate the pods they relate to. This makes it
  possible for services and replication controllers to reference groups of pods,
   or treat pods with potentially different Docker containers as similar
    entities.

endif::showscript[]
== Template Overview

.Parameters

* Share configuration values between different objects in template
* Example: Database username, password, or port needed by front-end pods to
 communicate to back-end database pods
* Values can be static or generated by template
* Templates let you define parameters that take on values
** Value substituted wherever parameter is referenced
** Can define references in any text field in objects list field

* Example:
** Can set `generate` to `expression` to specify generated values
** `from` specifies pattern for generating value using pseudo-regular expression syntax
+
[source,json]
----
 parameters:
   - name: PASSWORD
     description: "The random user password"
     generate: expression
     from: "[a-zA-Z0-9]{12}"
----



ifdef::showscript[]

=== Transcript

Parameters are used to share configuration values between the different objects
 in the template. Some examples are the database username, password, and port
  needed by the front-end pods to communicate to the back-end database pods.

Values can be static or generated by a template.

Templates allow you to define parameters that take on a value.
     That value is then substituted wherever the parameter is referenced.
      You can define references in any text field in the objects list field.

In the example shown here, you set the `generate` field to `expression` to specify generated values.
 The `from` field should specify the pattern for generating the value using a
  pseudo-regular expression syntax.


endif::showscript[]
== Template Overview

.Objects

* Can be any resources that needs to be created for template
* Examples: pods, services, replication controllers, and routes
* Other objects can be build configurations and image streams


ifdef::showscript[]

=== Transcript
Objects can be any resources that needs to be created for the template. Examples
 are pods, services, replication controllers, and a route for your application.
  Other objects can be build configurations and image streams.

The next few slides show sections of a sample template, which illustrate most of
 these objects.


endif::showscript[]
== Template File Creation

.Example Template
- `metadata`
[subs="verbatim,macros"]
----
{
  "kind": "Template",
  "apiVersion": "v1",
  "metadata": {
    "name": "quickstart-keyvalue-application",
    "creationTimestamp": null,
    "annotations": {
      "description": "This is an example of a Ruby and MySQL application on OpenShift 3",
      "iconClass": "icon-ruby",
      "tags": "instant-app,ruby,mysql"
    }
  },
----

ifdef::showscript[]

=== Transcript

This slide shows the `metadata` section of a sample template.


endif::showscript[]
== Template File Creation

.Example Template
- `objects:` `Service` `frontend` / `web`
[subs="verbatim,macros"]
----
"objects": [
    {
      "kind": "Service",
      "apiVersion": "v1",
      "metadata": {
      "name": "frontend",
        "creationTimestamp": null
      },
      "spec": {
        "ports": [
          {
            "name": "web",
            "protocol": "TCP",
            "port": 5432,
            "targetPort": 8080,
            "nodePort": 0
          }
        ],
        "selector": {
          "name": "frontend"
        },
        "portalIP": "",
        "type": "ClusterIP",
        "sessionAffinity": "None"
      },
      "status": {
        "loadBalancer": {}
      }
    },

----

ifdef::showscript[]

=== Transcript

This section shows the service named `frontend`.


endif::showscript[]
== Template File Creation

.Example Template
- `objects:`  `Service` `database`
[subs="verbatim,macros"]
----
  {
    *"kind": "Service",
      "apiVersion": "v1",
      "metadata": {
        "name": "database",
        "creationTimestamp": null
      },
      "spec": {
        "ports": [
          {
            "name": "db",
            "protocol": "TCP",
            "port": 5434,
            "targetPort": 3306,
            "nodePort": 0
          }
        ],
        "selector": {
          "name": "database"
        },
        "portalIP": "",
        "type": "ClusterIP",
        "sessionAffinity": "None"
      },
      "status": {
        "loadBalancer": {}
      }
    },
----

ifdef::showscript[]

=== Transcript

This slide shows the database Service object.
endif::showscript[]
== Template File Creation

.Example Template
- `objects:` `Route`
[subs="verbatim,macros"]
----
    {
      pass:quotes[*"kind": "Route",*]
      "apiVersion": "v1",
      "metadata": {
        "name": "route-edge",
        "creationTimestamp": null
      },
      "spec": {
        pass:quotes[*"host": "integrated.cloudapps.example.com",*]
        "to": {
          "kind": "Service",
          pass:quotes[*"name": "frontend"*]
        }
      },
      "status": {}
    },
----

ifdef::showscript[]

=== Transcript

This slide shows the `frontend` `route` object, and the hostname defined.

endif::showscript[]
== Template File Creation

.Example Template
- `objects:` `ImageStream` `ruby-sample` and `ruby-20-rhel7`
[subs="verbatim,macros"]
----
 {
pass:quotes[*"kind": "ImageStream",*]
      "apiVersion": "v1",
      "metadata": {
        pass:quotes[*"name": "ruby-sample",*]
        "creationTimestamp": null
      },
      "spec": {},
      "status": {
        "dockerImageRepository": ""
      }
    },
    {
      pass:quotes[*"kind": "ImageStream",*]
      "apiVersion": "v1",
      "metadata": {
        pass:quotes[*"name": "ruby-20-rhel7",*]
        "creationTimestamp": null
      },
      "spec": {
        "dockerImageRepository": "registry.access.redhat.com/openshift3/ruby-20-rhel7"
      },
      "status": {
        "dockerImageRepository": ""
      }
    },
----

ifdef::showscript[]

=== Transcript

This slide shows the `ruby-sample` and `ruby-20-rhel7` `ImageStream` objects.

Note that there are two `imagestream` objects in this template, one for the
 _builder image_ (`ruby-20-rhel7`) and one for the S2I image (`ruby-sample`)
  that will be created for this deployment.

endif::showscript[]
== Template File Creation

.Example Template
- `objects:` `DeploymentConfig` `frontend`

[subs="verbatim,macros"]
----
 {
      pass:quotes[*"kind": "DeploymentConfig",*]
      "apiVersion": "v1",
      "metadata": {
        pass:quotes[*"name": "frontend",*]
        "creationTimestamp": null
      },
      "spec": {
        "strategy": {
          "type": "Recreate"
        },
        "triggers": [
          {
            "type": "ImageChange",
            "imageChangeParams": {
              "automatic": true,
              "containerNames": [
                "ruby-helloworld"
              ],
              "from": {
                "kind": "ImageStreamTag",
                "name": "ruby-sample:latest"
              },
              "lastTriggeredImage": ""
            }
          },
          {
            "type": "ConfigChange"
          }
        ],
        "replicas": 2,
        "selector": {
          "name": "frontend"
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "name": "frontend"
            }
          },
          "nodeSelector": {
            "region": "primary"
          },
          "spec": {
            "containers": [
              {
                "name": "ruby-helloworld",
                "image": "ruby-sample",
                "ports": [
                  {
                    "containerPort": 8080,
                    "protocol": "TCP"
                  }
                ],
              "env": [
                  {
                    "name": "ADMIN_USERNAME",
                    "value": "${ADMIN_USERNAME}"
                  },
                  {
                    "name": "ADMIN_PASSWORD",
                    "value": "${ADMIN_PASSWORD}"
                  },
                  {
                    "name": "MYSQL_USER",
                    "value": "${MYSQL_USER}"
                  },
                  {
                    "name": "MYSQL_PASSWORD",
                    "value": "${MYSQL_PASSWORD}"
                  },
                  {
                    "name": "MYSQL_DATABASE",
                    "value": "${MYSQL_DATABASE}"*]
                  }
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "IfNotPresent",
                "capabilities": {},
                "securityContext": {
                  "capabilities": {},
                  "privileged": false
                }
              }
            ],
            "restartPolicy": "Always",
            "dnsPolicy": "ClusterFirst",
            "serviceAccount": ""
          }
        }
      },
      "status": {}
    },
----

ifdef::showscript[]

=== Transcript

This slide shows the `frontend` `DeploymentConfig` object.


Notice that the `env` parameters for MySQL access are set. You see them again in
 the next part of the template.

endif::showscript[]
== Template File Creation

.Template Example - `objects:` `DeploymentConfig` `database`
[subs="verbatim,macros"]
----
  {
      pass:quotes[*"kind": "DeploymentConfig",*]
      "apiVersion": "v1",
      "metadata": {
        pass:quotes[*"name": "database",*]
        "creationTimestamp": null
      },
      "spec": {
        "strategy": {
          "type": "Recreate"
        },
        "triggers": [
          {
            "type": "ConfigChange"
          }
        ],
        "replicas": 1,
        "selector": {
          "name": "database"
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "name": "database"
            }
          },
          "nodeSelector": {
            "region": "primary"
          },
          "spec": {
            "containers": [
              {
                "name": "ruby-helloworld-database",
                "image": "registry.access.redhat.com/openshift3/mysql-55-rhel7:latest",
                "ports": [
                  {
                    "containerPort": 3306,
                    "protocol": "TCP"
                  }
                ],
                "env": [
                  {
                    "name": "MYSQL_USER",
                    "value": "${MYSQL_USER}"
                  },
                  {
                    "name": "MYSQL_PASSWORD",
                    "value": "${MYSQL_PASSWORD}"
                  },
                  {
                    "name": "MYSQL_DATABASE",
                    "value": "${MYSQL_DATABASE}"*]
                  }
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "Always",
                "capabilities": {},
                "securityContext": {
                  "capabilities": {},
                  "privileged": false
                }
              }
            ],
            "restartPolicy": "Always",
            "dnsPolicy": "ClusterFirst",
            "serviceAccount": ""
          }
        }
      },
      "status": {}
    }
----

ifdef::showscript[]

=== Transcript

This slide shows the `database` `DeploymentConfig` object.

Notice that the `env` parameters for MySQL access are set the same as they were
 in the `frontend` `DeploymentConfig` object.

endif::showscript[]
== Template File Creation

.Example Template - `parameters`

[subs="verbatim,macros"]
----
  ],
  pass:quotes[*"parameters": [*]
    {
      "name": "ADMIN_USERNAME",
      "description": "administrator username",
      "generate": "expression",
      "from": "admin[A-Z0-9]{3}"
    },
    {
      "name": "ADMIN_PASSWORD",
      "description": "administrator password",
      "generate": "expression",
      "from": "[a-zA-Z0-9]{8}"
    },
    {
      "name": "MYSQL_USER",
      "description": "database username",
      "generate": "expression",
      "from": "user[A-Z0-9]{3}"
    },
    {
      "name": "MYSQL_PASSWORD",
      "description": "database password",
      "generate": "expression",
      "from": "[a-zA-Z0-9]{8}"
    },
    {
      "name": "MYSQL_DATABASE",
      "description": "database name",
      "value": "root"
    }
  ],
  "labels": {
    "template": "application-template-stibuild"
  }
----

ifdef::showscript[]

=== Transcript

This slide shows the template `parameters` generated from expressions.
 Parameters are essentially variables that the entire template can access.

endif::showscript[]
== New Configuration From Template

.Uploading a Template

* Can create configuration from template using CLI or management console
** To use from web console, template must exist in project or global template
 library
* Can create JSON template file, then upload it with CLI to project’s template
 library by passing file:
+
----
$ oc create -f <filename>
----

* Can upload template to different project with `-n` option and project name:
+
----
$ oc create -f <filename> -n <project>
----

* Template now available for configuration using management console or CLI

ifdef::showscript[]

=== Transcript

You can create a configuration from a template file or the management console.
 Using the web console, however, requires the template to be uploaded to
your project or global template library.

You can create a JSON template file and then upload it to your project's
 template library with with the CLI as shown. If you want to upload the JSON
  file to a different project, use the `-n` option with the project's name.

After you upload the template, you can configure it using the web console
 or the CLI.

endif::showscript[]
== New Configuration From Template

.Generating a Configuration

* `oc process` examines template, generates parameters, and outputs JSON
 configuration

**  Create configuration with `oc create`

* To generate configuration:
+
----
$ oc process -f <filename>
----

* Can override parameters defined in JSON file by adding `-v` option and
 parameters

* To override `ADMIN_USERNAME` and `MYSQL_DATABASE` parameters to create
 configuration with customized environment variables:
+
----
$ oc process -f my_template_file.json -v ADMIN_USERNAME=root,MYSQL_DATABASE=admin
----

.Creating an Application From a Template

* `oc new-app` can instantiate template from stored template or template file
* To instantiate stored template, specify template name as argument
* To create application from stored template or template file:
+
----
# Create an application based on a stored template, explicitly setting a parameter value
$ oc new-app --template=ruby-helloworld-sample --param=MYSQL_USER=admin

# Create an application based on a template file, explicitly setting a parameter value
  $ oc new-app --file=./example/myapp/template.json --param=MYSQL_USER=admin
----

ifdef::showscript[]

=== Transcript

You can generate a configuration with the `oc process` command. `oc process`
 examines a template, generates any desired parameters, and outputs a JSON
  configuration that can be created with `oc create`.

Alternatively, you can pipe both commands together to create from a template
 without uploading it to the template library.

You can also override any parameters defined in the template file by adding the
 `-v` option and any desired parameters. For example, you can override the
  `ADMIN_USERNAME` and `MYSQL_DATABASE` parameters to create a configuration
   with customized environment variables.

You can use the `oc new-app` command to deploy templates from a local template
 file or a stored template. To instantiate a stored template, specify the template name as an argument. The example here shows  how to create a new application and override the template parameter value for `MYSQL_USER`.

endif::showscript[]
== Processing Template Parameters

.Overview

* May want to build components separately

** Database team deploys database templates and development team deploys
 front-end template
* Treat as two applications wired together:
** Process and create template for `frontend`
** Extract values of `mysql` credentials from configuration file
** Process and create template for `db`
** Override values with values extracted from `frontend` configuration file

ifdef::showscript[]

=== Transcript

Sometimes you might want to build various components separately. For example, a
 database team deploys database templates and the development team deploys the
  front-end template.

You can take these two separate templates and wire them together. First, process
 and create a `frontend` template, and extract the values of the `mysql`
  credentials from its configuration file. Then process and create a `db`
   template and override its `mysq1` credentials' values with the values
    extracted from the `frontend` configuration file.

endif::showscript[]
== Processing Template Parameters

.Process `frontend`

* First stand up front end of application
* Process `frontend` template and create configuration file:
+
----
$ oc process -f frontend-template.json > frontend-config.json
----

* Create configuration:
+
----
$ oc create -f frontend-config.json
----

** When command is run, resources are created and build started

NOTE: Remember we could also use `oc new-app` to create the app in a single
 command. We are using `oc process` to generate a file, modify/review it before
  we create the application.

ifdef::showscript[]

=== Transcript

The first step is to create the front end of your application and process the
 `frontend` template to create the configuration file.

When you run the command, resources are created and the build is started.

endif::showscript[]
== Processing Template Parameters

.Extract Configuration File Values

* Before creating `db` template, review `frontend` configuration file
* Note that database password and other parameters were generated
* For existing deployment, can extract these values with `oc env`
+
----
grep -A 1 MYSQL_* frontend-config.json
                                            "name": "MYSQL_USER",
                                            "key": "MYSQL_USER",
                                            "value": "userMXG"

                                            "name": "MYSQL_PASSWORD",
                                            "key": "MYSQL_PASSWORD",
                                            "value": "slDrggRv"

                                            "name": "MYSQL_DATABASE",
                                            "key": "MYSQL_DATABASE",
                                            "value": "root"

----


ifdef::showscript[]

=== Transcript

Before creating the `db` template, review the `frontend` config file.  You can
 see that a database password and other parameters were generated.

For an existing deployment, you can extract these values with the `oc env`
 command.

endif::showscript[]
== Processing Template Parameters

.Process `db`

* Values used to create `frontend` can be used to process `db` template

* To process `db` template and create configuration file:
+
----
$ oc process -f db-template.json  -v MYSQL_USER=userMXG,MYSQL_PASSWORD=slDrggRv,MYSQL_DATABASE=root > db-config.json
----

** This example processes and creates `db` template while overriding `mysql`
 credentials' variables

* Create configuration:
+
----
$ oc create -f db-template.json
----

* Can also process and create application in single step:
+
----
oc process -f db-template.json \
    -v MYSQL_USER=userMXG,MYSQL_PASSWORD=slDrggRv,MYSQL_DATABASE=root \
    | oc create -f -
----
+
** Or, use `oc new-app` to achieve same result:
+
----
$ oc new-app --file=./db-template.json --param=MYSQL_USER=userMXG,MYSQL_PASSWORD=slDrggRv,MYSQL_DATABASE=root
----

ifdef::showscript[]

=== Transcript

Now that you know the values used to create the `frontend` template, you can use
 them when the `db` template is processed.

In this example you process and create the `db` template while
 overriding the `mysql` credentials' variables.

You can also process and create the application in a single step, or use the
 `oc new-app` command to achieve the same result.

endif::showscript[]
== Summary

* Template Overview
* Template File Creation
* New Configuration From Template
* Processing Template Parameters



ifdef::showscript[]

=== Transcript

In this module you learned about the various sections of a template; how to
 deploy , process, and modify a template; and how to "wire" templates together.

endif::showscript[]
