== Template Overview
:noaudio:

.Components

* Review the following sample template file:

[source,json]
----
{
  "kind": "Template",
  "apiVersion": "v1",
  "metadata": {
    "name": "quickstart-keyvalue-application",
    "creationTimestamp": null,
    "annotations": {
      "description": "This is an example of a Ruby and MySQL application on OpenShift 3",
      "iconClass": "icon-ruby",
      "tags": "instant-app,ruby,mysql"

    }
  },
  "parameters": [
    {
      "name": "username"
      "value": "admin"
      "description": "administrative user"
    }
  ],
  "labels": {
    "custom_label": "Label_Name"
  },
  "objects": [
    {
      ...
    }
  ]
}

----

* Notice the following elements:
** *"name":* - The name of the template
** *"description":* - Optional description for the template
** *"parameters":* - A list of parameters for the template (Parameters like
  Username, Passwords and others)
** *"labels":* - A list of labels to apply to resources
** *"objects":* - A list of resources to create (Resources like *Pods*,
  *Services* and *Routes*)


ifdef::showScript[]

=== Transcript

Review the following sample template file, take note of the following elements:
Notice the following elements:
The *"name":* Element, The name of the template
The *"description":* Element, Optional description for the template
The *"parameters":* Element, A list of parameters for the template (Parameters
  like Username, Passwords and others)
The *"labels":* Element, A list of labels to apply to resources
The *"objects":* Element, A list of resources to create (Resources like *Pods*,
  *Services* and *Routes*)

endif::showScript[]


