== Template Overview

.Template Elements

----
{
  "kind": "Template",
  "apiVersion": "v1",
  "metadata": {
    "name": "quickstart-keyvalue-application", <1>
    "creationTimestamp": null,
    "annotations": {
      "description": "This is an example of a Ruby and MySQL application on OpenShift 3", <2>
      "iconClass": "icon-ruby",
      "tags": "instant-app,ruby,mysql"

    }
  },
  "parameters": [  <3>
    {
      "name": "username"
      "value": "admin"
      "description": "administrative user"
    }
  ],
  "labels": {  <4>
    "custom_label": "Label_Name"
  },
  "objects": [  <5>
    {
      ...
    }
  ]
}

----

<1> `name`: Name of template
<2> `description`: Optional description for template
<3> `parameters`: List of parameters, like username, passwords, and others
<4> `labels`: List of labels to apply to resources created by template
<5> `object`: List of resources to create, such as pods, services, and routes


ifdef::showscript[]

=== Transcript

This sample template file is constructed from the following elements:

. `name` is the name of the template.
. `description` is an optional description for the template.
. `parameters` is where you list parameters like username, passwords, and
 others.
. `labels` is a list of labels to apply to resources created by the template.
. `object` lists resources to create, like pods, services, and routes.

endif::showscript[]
