== Template Overview


.Parameters

* Share configuration values between different objects in template
* Example: Database user name, password, or port needed by front-end pods to
 communicate to back-end database pods.
* Values can be static or generated by the template
- Pseudo regular expressions can be used to generate a value
+
[source,json]
----
 parameters:
   - name: PASSWORD
     description: "The random user password"
     generate: expression
     from: "[a-zA-Z0-9]{12}"
----



ifdef::showscript[]

=== Transcript

Parameters are used to share configuration values between the different objects
 in the template. An easy example is the database user name, password, or port
  needed by the front-end pods to communicate to the back-end database pods.

Templates allow you to define parameters which take on a value.
     That value is then substituted wherever the parameter is referenced.
      References can be defined in any text field in the objects list field.

The generate field can be set to 'expression' to specify generated values.
 The from field should specify the pattern for generating the value using a
  pseudo regular expression syntax.


endif::showscript[]
