== Template Overview

.Parameters

* Share configuration values between different objects in template
* Example: Database username, password, or port needed by front-end pods to
 communicate to back-end database pods
* Values can be static or generated by template
* Templates let you define parameters that take on values
** Value substituted wherever parameter is referenced
** Can define references in any text field in objects list field

* Example:
** Can set `generate` to `expression` to specify generated values
** `from` specifies pattern for generating value using pseudo-regular expression
 syntax
+
[source,json]
----
 parameters:
   - name: PASSWORD
     description: "The random user password"
     generate: expression
     from: "[a-zA-Z0-9]{12}"
----



ifdef::showscript[]

=== Transcript

Parameters are used to share configuration values between the different objects
 in the template. Some examples are the database username, password, and port
  needed by the front-end pods to communicate to the back-end database pods.

Values can be static or generated by a template.

Templates allow you to define parameters that take on a value.
     That value is then substituted wherever the parameter is referenced.
      You can define references in any text field in the object definition.

In the example shown here, you set the `generate` field to `expression` to
 specify generated values.
  The `from` field should specify the pattern for generating the value using a
   pseudo-regular expression syntax.


endif::showscript[]
