== New Configuration From Template
:noaudio:

.Generating a Configuration

* `oc process` examines template, generates parameters, and outputs JSON
 configuration

**  Create configuration with `oc create`

* To generate configuration:
+
----
$ oc process -f <filename>
----

** Alternatively, can pipe both commands to create from template without
 uploading it to library
** To process template and create from same template:
+
----
$ oc process -f <filename.json> | sed s/oldvalue/newvalue/g |oc create -f -
----

* Can override parameters defined in JSON file by adding `-v` option and
 parameters

* To override `ADMIN_USERNAME` and `MYSQL_DATABASE` parameters to create
 configuration with customized environment variables:
+
----
$ oc process -f examples/sample-app/application-template-dockerbuild.json -v ADMIN_USERNAME=root,MYSQL_DATABASE=admin
----


ifdef::showscript[]

=== Transcript

You can generate a configuration with the `oc process` command. `oc process`
 examines a template, generates any desired parameters, and outputs a JSON
  configuration that can be created with `oc create`.

Alternatively, you can pipe both commands together to create from a template
 without uploading it to the template library. You can process the template and
  create from the same template.

You can also override any parameters defined in the JSON file by adding the `-v`
 option and any desired parameters. For example, you can override the
  `ADMIN_USERNAME` and `MYSQL_DATABASE` parameters to create a configuration
   with customized environment variables.

endif::showscript[]
