== New Configuration From Template

.Generating a Configuration

* `oc process` examines template, generates parameters, and outputs JSON
 configuration

**  Create configuration with `oc create`

* To generate configuration:
+
----
$ oc process -f <filename>
----

* Can override parameters defined in JSON file by adding `-v` option and
 parameters

* To override `ADMIN_USERNAME` and `MYSQL_DATABASE` parameters to create
 configuration with customized environment variables:
+
----
$ oc process -f my_template_file.json -v ADMIN_USERNAME=root,MYSQL_DATABASE=admin
----

.Creating an Application From a Template

* `oc new-app` can instantiate template from stored template or template file
* To instantiate stored template, specify template name as argument
* To create application from stored template or template file:
+
----
# Create an application based on a stored template, explicitly setting a parameter value
$ oc new-app --template=ruby-helloworld-sample --param=MYSQL_USER=admin

# Create an application based on a template file, explicitly setting a parameter value
  $ oc new-app --file=./example/myapp/template.json --param=MYSQL_USER=admin
----

ifdef::showscript[]

=== Transcript

You can generate a configuration with the `oc process` command. `oc process`
 examines a template, generates any desired parameters, and outputs a JSON
  configuration that can be created with `oc create`.

Alternatively, you can pipe both commands together to create from a template
 without uploading it to the template library.

You can also override any parameters defined in the template file by adding the
 `-v` option and any desired parameters. For example, you can override the
  `ADMIN_USERNAME` and `MYSQL_DATABASE` parameters to create a configuration
   with customized environment variables.

You can use the `oc new-app` command to deploy templates from a local template
 file or a stored template. To instantiate a stored template, specify the template name as an argument. The example here shows  how to create a new application and override the template parameter value for `MYSQL_USER`.

endif::showscript[]
