== Module Topics

* Overview
* Source-to-Image
* Source-to-Image Builds
* Application Creation
* New App From Source Code
* New App From Image
* New App From Template
* Application Environment
* Advanced Application Creation
* Web Console


ifdef::showscript[]

=== Transcript

Welcome to Module 6 of the OpenShift Enterprise Implementation course.

This module covers the following topics:

* Concepts such as build and deployment automation; the definition of
 Source-to-Image, or S2I; the build process; the `BuildConfig` object; and build
  strategies.

* Creating an S2I build, including creating the build file and understanding the
 various sections of the build file: `Service,`, `ImageStream`, `BuildConfig`,
  `DeploymentConfig`, and `Templates`.

* Deploying an image created by the an S2I build process, including creating the
 build environment, starting the build, and using the web console.

* How to deploy applications from source or image using the `oc new-app` CLI
 tool or the web console, and information about templates and advanced
  application creation.

endif::showscript[]
