== Overview
:noaudio:

* You can create a new OpenShift application using the web console or by running
the `oc new-app` command from the CLI.
* The user can create a new application by specifying source code, images, or
templates.
* In this context, an application is set of objects such as: `DeploymentConfig`,
`BuildConfig`, `ReplicationController`, `Pod`, `Service` and more that make up
 a *Deployment*.

* The *oc new-app* command uses the S2I build process underneath the covers.

NOTE: In this module we will start by learning the "manual" way of creating each
 of these objects and then cover the, much simpler, *oc new-app* method.


ifdef::showscript[]

=== Transcript

You can create a new OpenShift application using the web console or by running
the `oc new-app` command from the CLI.

In this context, an application is set of objects such as: `DeploymentConfig`,
`BuildConfig`, `ReplicationController`, `Pod`, `Service` and more that make up
a *Deployment*.

The *oc new-app* command uses the S2I build process underneath the covers.

In this module we will start by learning the "manual" way of creating each
of these objects and then cover the, much simpler, *oc new-app* method.


endif::showscript[]
