== Overview


* Users can create new OpenShift Enterprise application using web console or
 `oc new-app` command
** Users can specify application creation from _source code_, _image_, or
 _template_
* Application is set of deployed objects such as `DeploymentConfig`,
 `BuildConfig`, `ReplicationController`, `pod`, `service`, and others

* `oc new-app` uses S2I (Source-to-Image) build process

NOTE: You start by learning the manual way of creating objects and then the much
 simpler `oc new-app` method.


ifdef::showscript[]

=== Transcript

You can create a new OpenShift Enterprise application using the web console or
 by running the `oc new-app` command from the CLI.

In this context, an application is set of objects, such as `DeploymentConfig`,
 `BuildConfig`, `ReplicationController`, `pod`, `service`, and others that make
  up a _deployment_.

The `oc new-app` command uses the S2I build process underneath the cover.

In this module you start by learning the manual way of creating each of these
 objects, and then the much simpler `oc new-app` method.


endif::showscript[]
