== Source-to-Image

.What Is S2I?

* Tool for building reproducible Docker images

* Produces ready-to-run images by injecting user source into Docker image and
 assembling new Docker image

** New image incorporates base image (_builder image_) and built source
*** Ready to use within OpenShift Container Platform or other platforms (e.g., Atomic
   Host)



ifdef::showscript[]

=== Transcript

A Source-to-Image, or S2I, build is a process in which a developer points to a
 code repository in a supported framework and selects a _builder_ image that
  contains the operating system and framework to support the code.

To start an S2I build, your code must reside in a supported code repository, and
 you need a base, or builder, image--for example, `ruby-20-rhel7`--on top of
  which to start building. These base images are available in OpenShift
   Enterprise--you do not need to create them yourself.



endif::showscript[]
// ISSUE: Waiting for Erik to answer regarding  3.1
//   * Supports incremental builds
//   ** Reuses previous dependencies, built artifacts, etc.
//S2I supports incremental builds and reuses previous dependencies, built artifacts, and so on.
// https://docs.openshift.com/enterprise/3.1/architecture/core_concepts/builds_and_image_streams.html
