== S2I Applications Expanded
:noaudio:

.Build and Deployment Automation

* Integrated Docker registry and automated image builds
* Source code deployments leveraging S2I build automation
* Binary deployments integrated with existing build and CI infrastructure
* Configurable deployment patterns--rolling, etc.

ifdef::showscript[]

=== Transcript

The S2I, Source to Image  build is a process in which a developer points to a code repository in any of the supported frameworks and selects a "builder" image that will contain the operating system and framework to support the code.

OpenShift Enterprise then creates an image based on the builder image that contains the selected code.

OpenShift Enterprise offers an integrated Docker registry and automated image builds, enabling both source code deployments leveraging S2I build automation
and binary deployments integrated with your existing build and CI infrastructure.

OpenShift Enterprise also offers configurable deployment patterns, which would be covered in future courses.

endif::showscript[]


