== Source-to-Image Builds

.JSON Build File - `ImageStream`

* Describes `ImageStream` resource to be created to support application
* OpenShift components such as builds and deployments can watch an image stream
 to receive notifications when new images are added and react by performing a
  build or a deployment.
** OpenShift Enterprise _rebuilds_ when a change like this occurs
+
[subs="verbatim,macros"]
----
        {
            pass:quotes[*"kind": "ImageStream",*]
            "apiVersion": "v1",
            "metadata": {
                "name": "simple-openshift-sinatra-sti",
                "creationTimestamp": null
            },
            "spec": {
                "tags": [
                    {
                        "name": "latest",
                        "from": {
                            "kind": "DockerImage",
                            "name": "simple-openshift-sinatra-sti:latest"
                        }
                    }
                ]
            },
            "status": {
                "dockerImageRepository": ""
            }
        },

----


ifdef::showscript[]

=== Transcript

The `ImageStream` section describes the `ImageStream` resource to be created to
 support the built application.

 OpenShift components such as builds and deployments can watch an image stream
  to receive notifications when new images are added and react by performing a
   build or a deployment. OpenShift Enterprise _rebuilds_ when a
  change like this occurs.

endif::showscript[]
