== Create App from Source Code
:noaudio:

.Specifying Source Code

* You can create a new application using the `oc new-app` command from the CLI.

* The `new-app` command allows you to create applications using source code from a
local or remote Git repository.
* If only a source repository is specified, `new-app` tries to automatically
determine the type of build strategy to use (`Docke*` or `Source`), and in the
case of `Source` type builds, an appropriate language builder image.

* You can tell `new-app` to use a subdirectory of your source code repository by
specifying a `--context-dir` flag. Also, when specifying a remote URL, you can
specify a Git reference to use by appending `#[reference]` to the end of the
URL.

NOTE: If using a local Git repository, the repository must have an *origin* remote
that points to a URL accessible by the OpenShift cluster.

ifdef::showscript[]

=== Transcript
The `new-app` command allows you to create applications using source code from a
local or remote Git repository. If only a source repository is specified,
`new-app` tries to automatically determine the type of build strategy to use
(`Docke*` or `Source`), and in the case of `Source` type
builds, an appropriate language builder image.

If using a local Git repository, the repository must have an *origin* remote
that points to a URL accessible by the OpenShift cluster.

endif::showscript[]


