== New App From Image

.Specifying an Image

* `new-app` generates artifacts to deploy existing image as application

* Images can come from:
**  OpenShift Enterprise server
** Specific registry
** Docker Hub
** Local Docker server

* `new-app` attempts to determine type of image from arguments passed to it

* Can explicitly tell `new-app` what image is:
** For Docker image, use `--docker-image` argument
** For image stream, use `-i|--image` argument


NOTE: If you specify an image from your local Docker repository, you must ensure
 that the same image is available to the OpenShift Enterprise cluster nodes.

ifdef::showscript[]

=== Transcript
The `new-app` command generates the necessary artifacts to deploy an existing
image as an application. Images can come from image streams in the OpenShift
 Enterprise server, a specific registry, Docker Hub, or a local Docker server.

The `new-app` command attempts to determine the type of image specified in the
 arguments passed to it. However, you can explicitly tell `new-app` that the
  image is a Docker image by using the `--docker-image` argument, or an image
   stream by using the `-i|--image` argument.

If you specify an image from your local Docker repository, you must ensure that
 the same image is available to the OpenShift Enterprise cluster nodes.

endif::showscript[]
