== Application Environment

.Object Names

* `new-app` objects normally named after source repository or image
* Can set name of the application produced by adding `--name` flag

* To create `new-app` artifacts with different name:
+
----
$ oc new-app https://github.com/openshift/ruby-hello-world --name=myapp
----

.Object Project or Namespace

* `new-app` creates objects in current project

* To tell `new-app` to create objects in different project, use `-n|--namespace`
 flag

* To create `new-app` artifacts in different project:
+
----
$ oc new-app https://github.com/openshift/ruby-hello-world -n myproject
----




ifdef::showscript[]

=== Transcript
Objects created by `new-app` are normally named after the source repository or
 the image used to generate them.

You can set the name of the objects produced by adding the `--name` flag to the
 command.

Normally `new-app` creates objects in the current project. To tell it to create
 objects in a different project that you have access to, use the
  `-n|--namespace` flag.


endif::showscript[]
