== Summary
:noaudio:

In this Module we covered:


* Overview
* Source To Image
* Source To Image Builds
* Creating New Applications
- Create App from Source Code
- Create App from Image
- Create App from Template
* Modify Application Environment
* Advanced Application Creation
* Using the Web Console


ifdef::showscript[]

=== Transcript

This module covered the following topics:

* Concepts such as build and deployment automation; the definition of
Source-to-Image, or S2I; the build process; the `BuildConfig` object; and build
strategies.
Creating an S2I build, including creating the build file and understanding the
various sections of the build file: `Service,`, `ImageStreams`, `BuildConfig`,
`DeploymentConfig`, and `templates`
* Deploying an S2I build image, including creating the build environment,
starting the build, and using the web console to create an S2I build.

* we learned how to deploy applications from "Source" or "Image" using the
*oc new-app* CLI tool or the web console, and learned a little about templates
and advanced application creation.

endif::showscript[]
