:toc2:
:icons: images/icons
:numbered:
= Labs: Creating Applications

toc::[]

== Labs Overview


* Lab: Deploy an Application Using the Web Console
- Lab Scenario: In this lab you will deploy an application based on a code
 repository follow the build logs using the OpenShift Enterprise Web Console and
  CLI.

* Lab: Create Customized Build script
- Lab Scenario: In this lab you will create an application from a forked git
   repository, you will inject a custom build script and, start a rebuild from
    the web console and follow the logs to review your custom script messages.

== Lab: Deploy an Application Using the Web Console

* Lab: Deploy an Application Using the Web Console
- Lab Scenario: In this lab you will deploy an application based on a code
 repository follow the build logs using the OpenShift Enterprise Web Console and
  CLI.



=== Create an Application using the OpenShift Web Console

.Connect and explore the Web Console

. Use your browser to connect to the OpenShift Web Console at : link:https://master00-GUID.oslab.opentlc.com:8443[https://master00-GUID.oslab.opentlc.com:8443]

.. If you haven't already, accept the "Untrusted Certificate"

. Authenticate as "andrew" with the password "r3dh4t1!"

. Take a 3 minutes to explore your existing projects.



.Create a new project

. To return to the Projects view, click the "Projects drop down list and select
 "View all projects".

. Click the blue "New Project" button in the top right corner.

. Enter Project Name, Display Name and Description
.. For "Name" enter: my-ruby-project
.. For "Display Name" enter: My Ruby Example Project
.. For "Description" enter: what ever you want.

. Once the project is created, you will be directed to the "Select Image or
 Template" screen.

.Create a new Application

. In the "Select Image or Template" screen, type the word "ruby" into the search

 bar to filter the available Instant Apps, Templates and Builder Images.
. Select the "ruby:2.0" builder image from the right hand side.

. Enter the Name and Git Repository URL
.. For "Name" enter: my-ruby-hello-world
.. For "Git Repository URL" enter: https://github.com/openshift/ruby-hello-world

. Click "Show advanced build and deployment options" and explore the options
...Note that you can decide if you want a route create for your application.
.. Note that you can define triggers and environment variables for the deployment.
.. Change the Scaling parameter to 3
.. Enter a label : "environment" with the value "dev"

. Accept and start the application.
.. Review the information presented.

. Click "Go to Overview", you will be directed to the application overview screen.
. You can see a build is in progress, press "View Logs"
.. Review the log as the build progresses.
TIP: If we wanted to do this in the command line we would have run:
 `oc new-app https://github.com/openshift/ruby-hello-world -l  environment=dev`
  and `oc scale` to increase the number of replicas.

.Scalling a deployment and the Topology View

. Go back to your application's "Overview" screen by pressing the "Overview"
 button on the upper left side.
. Click the "^" button twice to increase the number of replicas to "5"
.. The button is next to the circle with the current number of pods (3 pods
   before scaling)
. Hover over "Browse" and select "Pods", Have a look at your new pods.

. Go back to your application's "Overview" screen by pressing the "Overview"
 button on the upper left side.
. The current and default view is of the "Overview" screen is the "Tile view",
 to switch to the "Topology View" click the button on the upper right hand side
  that looks like this "<" character or like a social media type "share button"
   (it isn't)
.. Click the different objects and consider their relationships.



== Lab: Create Customized Build script

* Lab: Create Customized Build script
- Lab Scenario: In this lab you will create an application from a forked git
 repository, you will inject a custom build script and, start a rebuild from the
  web console and follow the logs to review your custom script messages.


NOTE: OpenShift Enterprise 3 supports customization of both the build and run
 processes. Generally speaking, this involves modifying the various S2I scripts
  from the builder image. When OpenShift Enterprise builds your code, it checks
   to see if any of the scripts in the `.sti/bin` folder of your repository
    override or supercede the builder image's scripts. If so, it executes the
     repository script instead.

You can find more information on the scripts, their execution during the
 process, and customization at
  link:https://docs.openshift.com/enterprise/3.1/creating_images/index.html[https://docs.openshift.com/enterprise/3.1/creating_images/index.html]


=== Clone a repository and launch application from a local copy

. Authenticate as "marina" to OpenShift Enterprise
.. Connect to the OpenShift Enterprise master following the same steps you used
 previously.
.. When prompted, enter the following username and a password:
** *Username*: `marina`
** *Password*: `r3dh4t1!`
+
----
[root@master00-GUID ~]# su - marina
[marina@master00-GUID ~]$ oc login -u marina --insecure-skip-tls-verify --server=https://master00-${guid}.oslab.opentlc.com:8443
----

[marina@master00-GUID ~]$ oc new-project custom-s2i-script --display-name="Custom S2I Build Script" \
    --description="This is the project we use to learn how to create a customized build script"


=== Fork the Repository

NOTE: This lab requires a github account, if you don't have one you can create
 one quickly, they are free and very useful.

. Using the Git web interface, fork the following Git repository:
link:https://github.com/openshift/ruby-hello-world[https://github.com/openshift/ruby-hello-world.]

. To fork this into your own account, click *Fork* in the upper-right corner of
 the GitHub web UI.
.. You should now have a repository called under your account, something similar
 to :  "https://github.com/yourname/ruby-hello-world/", where "yourname" would
  be your git user name.

. Clone the "https://github.com/yourname/ruby-hello-world" repository, so we
 can make changes to it locally and use it to test our customized script.
+
CAUTION: Make sure you replace "yourname" with you git account user name in the
 commands bellow.
+
----
[marina@master00-c0fe ~]$ git clone https://github.com/yourname/ruby-hello-world
Cloning into 'ruby-hello-world'...
remote: Counting objects: 249, done.
remote: Total 249 (delta 0), reused 0 (delta 0), pack-reused 249
Receiving objects: 100% (249/249), 36.79 KiB | 0 bytes/s, done.
Resolving deltas: 100% (86/86), done.
----

. Create an application using the "oc new-app" using the local repository
+
----
[marina@master00-c0fe ~]$ cd ruby-hello-world/
[marina@master00-c0fe ruby-hello-world]$ oc new-app .
----

. View the current build status and build logs.
+
----
[marina@master00-c0fe]$ oc get builds
NAME                 TYPE      FROM         STATUS    STARTED         DURATION
ruby-hello-world-1   Docker    Git@master   Running   9 seconds ago   9s
----

. View the build log.
+
----
[marina@master00-c0fe ]$ oc logs -f builds/ruby-hello-world-1
...                 ...
... Omitted Output  ...
...                 ...
Removing intermediate container 049a12eb5ca5
Successfully built 995028e8bee2
I1127 02:41:37.640510       1 docker.go:86] Pushing image 172.30.42.118:5000/custom-s2i-script/ruby-hello-world:latest ...
I1127 02:44:25.867627       1 docker.go:90] Push successful
----

. Check to see that your pod has deployed
+
----
[marina@master00-c0fe ]$ oc get pods
NAME                       READY     STATUS      RESTARTS   AGE
ruby-hello-world-1-70mlb   1/1       Running     0          12s
ruby-hello-world-1-build   0/1       Completed   0          9m
----


=== Add a Script to the repository

. In a new tab in your web browser, open the following URL and copy all of the
 text: link:http://www.opentlc.com/download/ose_implementation/resources/3.1/assemble[http://www.opentlc.com/download/ose_implementation/resources/3.1/assemble]

. Go to your GitHub repository for your application from the previous lab.

. In the GitHub web UI, navigate to the `.sti/bin` folder.

. Click the *+* button at the top (to the right of `bin` in the breadcrumbs).

. Name your file `assemble`.

. In the GitHub UI, paste the contents you copied earlier into the text area.

. Enter a commit message.

. Click *Commit*.



=== Create a new application from your repository using the custom build script.

. Use your browser to connect to the OpenShift Web Console at :
link:https://master00-GUID.oslab.opentlc.com:8443[https://master00-GUID.oslab.opentlc.com:8443]
.. If you haven't already, accept the "Untrusted Certificate"

. Authenticate as "marina" with the password "r3dh4t1!"
. Select the "Custom S2I Build Script" project
Click the blue "New Project" button in the top right corner.

. Enter Project Name, Display Name and Description
.. For "Name" enter: my-custom
.. For "Display Name" enter: My custom assemble script project
.. For "Description" enter: what ever you want.

. Once the project is created, you will be directed to the "Select Image or
Template" screen.

. In the "Select Image or Template" screen, type the word "ruby" into the search
 bar to filter the available Instant Apps, Templates and Builder Images.
. Select the "ruby:2.0" builder image from the right hand side.

. Enter the Name and Git Repository URL
.. For "Name" enter: my-custom-builder-test
.. For "Git Repository URL" enter: https://github.com/yourname/ruby-hello-world
+
CAUTION: Make sure you replace "yourname" with you git account user name in the
 commands bellow.

. Follow the logs of the build process
.. Watch for your custom assemble script message to confirm the custom script was used:
+
----
2015-04-27T22:23:24.110630393Z ---> CUSTOM S2I ASSEMBLE COMPLETE
----
