:scrollbar:
:data-uri:
:toc2:
:icons: images/icons

== Deploy an S2I Build

:numbered:

In this lab, you create a simple S2I build. As part of this process, you create a `BuildConfig` object and build an image using the S2I build process. You also create the pod, service, and route for your S2I build image.

* Authenticate to OpenShift Enterprise and Choose Your Project
* Create Your S2I Description
* Start Your Build
* Create Your First Image (Sinatra)
* Use the Web Console

== Authenticate to OpenShift Enterprise and Choose Your Project

. On the `master` host, use `oadm` to create a project called `hello-s2i`, and assign an administrative user to it.
+
----

[root@master00-GUID ~]# oadm new-project hello-s2i --display-name="Hello Source2Image" \
    --description="This is the project we use to learn about Source to Image builds" \
      --node-selector='region=primary' --admin=andrew
----

. If you have not done so already, switch to user `andrew` and authenticate to OpenShift Enterprise as this user.
+
----

[root@master00 ~]# su - andrew
[andrew@master00 ~]$ guid=`hostname|cut -f2 -d-|cut -f1 -d.`
[andrew@master00 ~]$ oc login -u andrew --insecure-skip-tls-verify --server=https://master00-${guid}.oslab.opentlc.com:8443

----

. Change the context to the `hello-s2i` project.
+
----

[andrew@master00 ~]$ oc project hello-s2i
Now using project "hello-s2i" on server "https://master00-GUID.oslab.opentlc.com:8443".

----

. Check your current context by viewing `~/.kube/config` and running a quick test.
+
----

[andrew@master00 ~]$ grep current ~/.kube/config
current-context: hello-s2i/master00-GUID-oslab-opentlc-com:8443/andrew

----

== Create Your S2I Description

For this activity, you use a prebuilt and preconfigured code repository. This repository is an extremely simple application of the `Hello World` type.

. Go to https://github.com/openshift/simple-openshift-sinatra-S2I. You will use this application's source code.

. Take a minute to review the repository.
. Create the instructions and configuration for your image using the default image suggested by the builder.
+
----

[andrew@master00 ~]$ oc new-app https://github.com/openshift/simple-openshift-sinatra-STI.git -o json | tee ~/simple-sinatra.json
----

. Look at the JSON that you generated.
+
----
[andrew@master00 ~]$ cat ~/simple-sinatra.json

----

== Start Your Build


. Create the build components using `oc create` on the `BuildConfig` file.
+
----

[andrew@master00 ~]$ oc create -f ~/simple-sinatra.json

----

. View the output of the last command.
+
----

[andrew@master00 ~]$ for i in buildconfig deploymentconfig service; do echo $i; oc get $i; echo -e "\n\n"; done


----

* After the build is complete, you should see output similar to the following:
+
----
NAME                           TYPE      SOURCE
simple-openshift-sinatra-S2I   Source    https://github.com/openshift/simple-openshift-sinatra-S2I.git

deploymentconfig
NAME                           TRIGGERS                    LATEST VERSION
simple-openshift-sinatra-S2I   ConfigChange, ImageChange   2

service
NAME                       LABELS    SELECTOR                                        IP(S)           PORT(S)
simple-openshift-sinatra   <none>    deploymentconfig=simple-openshift-sinatra-S2I   172.30.64.255   8080/TCP

----

. View the running pods in real time.
+
----

[andrew@master00 ~]$ watch oc get pods

----

* For the first few minutes, you will see the following error. It will soon resolve itself.
+
----

NAME                                   READY     REASON                                                               RESTARTS   AGE
simple-openshift-sinatra-S2I-1-o72am   0/1       Error: image library/simple-openshift-sinatra-S2I:latest not found   0          1m

----

* Eventually you will see something similar to the following:
+
----

NAME                                   READY     REASON       RESTARTS   AGE
simple-openshift-sinatra-S2I-1-build   0/1       ExitCode:0   0          2m
simple-openshift-sinatra-S2I-2-cpp9t   1/1       Running      0          7m
...
CTRL+C

----
+
[NOTE]
If you see that the pod has failed to deploy, do not worry. This happens before your image is created and resolves itself after the image build process is complete.


. View the current build status and build logs.
+
----

[andrew@master00 ~]$ oc get builds
NAME                             TYPE      STATUS     POD
simple-openshift-sinatra-S2I-1   Source    Complete   simple-openshift-sinatra-S2I-1-build

----

. View the build log.
+
----
[andrew@master00 ~]$ oc build-logs simple-openshift-sinatra-S2I-1
....
....
....
I0702 05:36:50.618747       1 S2I.go:246] Successfully built 172.30.133.153:5000/sinatra/simple-openshift-sinatra-S2I
I0702 05:36:50.703511       1 cleanup.go:23] Removing temporary directory /tmp/S2I235763477
I0702 05:36:50.703600       1 fs.go:99] Removing directory '/tmp/S2I235763477'
I0702 05:36:50.727475       1 cfg.go:46] PUSH_DOCKERCFG_PATH=/var/run/secrets/openshift.io/push/.dockercfg
I0702 05:36:50.733088       1 cfg.go:64] Using serviceaccount user for Docker authentication
I0702 05:36:50.733130       1 S2I.go:96] Using provided push secret for pushing 172.30.133.153:5000/sinatra/simple-openshift-sinatra-S2I image
I0702 05:36:50.733157       1 S2I.go:99] Pushing 172.30.133.153:5000/sinatra/simple-openshift-sinatra-S2I image ...
I0702 05:39:46.967064       1 S2I.go:103] Successfully pushed 172.30.133.153:5000/sinatra/simple-openshift-sinatra-S2I



----

. Make sure to check the progress on the web console.

== Create Your First Image (Sinatra)

. After your build is complete, verify your pod and service.
+
----

[andrew@master00 ~]$ curl `oc get services | grep sin | awk '{print $4":"$5}' | awk -F'/' '{print $1}'`
Hello, Sinatra!

----

. Add a route to make the application publicly accessible.
+
----

[andrew@master00 ~]$ oc expose service simple-openshift-sinatra \
  --hostname=mysinatra.cloudapps-${guid}.oslab.opentlc.com



[andrew@master00 ~]$ oc get routes
NAME                       HOST/PORT                                        PATH      SERVICE                    LABELS
simple-openshift-sinatra   mysinatra.cloudapps-f4fc.oslab.opentlc.com             simple-openshift-sinatra

[andrew@master00 ~]$ curl http://mysinatra.cloudapps-${guid}.oslab.opentlc.com
Hello, Sinatra!
----

== Use the Web Console

Using what you learned, create an application using the web console and the command line.

. Create a project called `nodejs`.
. Go to the application repository at https://github.com/openshift/nodejs-ex.
. Use the `nodejs:0.10` image.
. Create a route and expose the service to the world under the name http://nodejs.cloudapps-GUID.oslab.opentlc.com/.
. Try to explore the `oc edit route` command.
. Make sure the application has for replicas.

[NOTE]
At this point, the web console can create a local route. To create an external route, use `oc expose` or edit the existing route with `oc edit route`.
